// Content is sourced exclusively from the SoSe 2023 course-project
// documentation (Bauhaus-Universität Weimar, team of 4): the questionnaire
// study, the think-aloud test report, and the photographed v1/v2 prototype
// artefacts in ./media. Evidence lock: every number, quote, and finding in
// this file exists in that documentation. The five metrics below are the
// ONLY quantitative results the study produced — no completion rates, no
// SUS, no time-on-task exist, and none may be added here.
//
// Media convention: media/v1/ is the version that was TESTED (screens A-L,
// matching the handwritten flow cheatsheet's letter vocabulary); media/v2/
// is the post-test revision (A-M; M is the per-resident menu that change 2
// introduced). Do not reverse this.
// Card-level fields (id/status/title/tags/thumbnails/card*) live in
// ./card.js — eagerly aggregated site-wide — and are spread here so the
// detail page sees one object.
import card from './card';
import thumbnailImg from './media/smarthome.png';

// v1 — the tested prototype
// The flow map is the full tested set laid out with torn-paper arrows —
// the manifest pairs it with v2/00-flow-map.jpg as the closing image. It
// opens the Solution galleries now that the hero is the generated
// illustration.
import v1FlowMap from './media/v1/flow-map.jpg';
import v1A from './media/v1/A.jpg';
import v1B from './media/v1/B.jpg';
import v1C from './media/v1/C.jpg';
import v1D from './media/v1/D.jpg';
import v1E from './media/v1/E.jpg';
import v1F from './media/v1/F.jpg';
import v1G from './media/v1/G.jpg';
import v1H from './media/v1/H.jpg';
import v1I from './media/v1/I.jpg';
import v1J from './media/v1/J.jpg';
import v1K from './media/v1/K.jpg';
import v1L from './media/v1/L.jpg';
import v1Cheatsheet from './media/v1/flow-cheatsheet.jpg';
import bottomSheetsVideo from './media/v1/bottom-sheets.mp4';
import bottomSheetsPoster from './media/v1/13-sheet-interaction-poster.jpg';

// Session documentation. Only ONE of the report's five session photographs
// is verifiably from the v1 test sessions: this one (report Picture 2).
// Pictures 1, 3, 4 and 5 all show post-revision artifacts in frame (the
// five-name "Jake" rosters, the kebab-menu Manage Residents sheet) and are
// therefore not wired as session documentation — see the audit notes in
// the project memory. Do not add them with a session caption.
import sessionToggle from './media/session/picture-2a-participantB-toggle-room.jpg';

// NOTE: the storyboards in media/storyboards/ are deliberately NOT wired.
// They depict a different concept from the same coursework (a supported-
// housing assistive service — Task 1; this prototype was Task 2) and are
// reserved for their own future entry. Do not present them as this
// product's scenarios.

// Discovery chart — generated by scripts/generate-smart-home-chart.mjs
// from the questionnaire's raw response sheet (which stays out of the repo).
import discoveryChart from './media/charts/discovery-difficulties.png';

// v2 flow map — the closing image, paired against the hero's v1 layout.
// The source JPEG, shipped unmodified (it arrived misnamed .png).
import v2FlowMap from './media/v2/00-flow-map.jpg';

// v2 — the post-test revision
import v2A from './media/v2/A.jpg';
import v2K from './media/v2/K.jpg';
import v2L from './media/v2/L.jpg';
import v2M from './media/v2/M.jpg';

export const projectData = {
  ...card,
  timeline: "SoSe 2023",

  heroImage: thumbnailImg,
  heroIsGenerated: true, // hero generated with Google Gemini — renders the credit

  methods: [
    { en: "Questionnaire study (N=24)",              de: "Fragebogenstudie (N=24)" },
    { en: "Think-aloud usability testing (N=2)",     de: "Think-Aloud-Usability-Testing (N=2)" },
    { en: "Low-fidelity paper prototyping",          de: "Low-Fidelity-Papierprototyping" },
    { en: "Qualitative coding & thematic analysis",  de: "Qualitative Kodierung & thematische Analyse" },
    { en: "Information architecture & flow mapping", de: "Informationsarchitektur & Flow-Mapping" },
    { en: "Iterative design revision",               de: "Iterative Designüberarbeitung" },
  ],

  // The complete set of real numbers this study produced. Nothing else
  // exists — see the evidence-lock note at the top of this file.
  metrics: [
    { value: "24", label: { en: "questionnaire responses (of 30 people approached)", de: "Fragebogen-Antworten (von 30 angefragten Personen)" } },
    { value: "2", label: { en: "think-aloud usability test participants", de: "Think-Aloud-Testteilnehmende" } },
    { value: "12", label: { en: "screens across 4 documented task flows", de: "Screens über 4 dokumentierte Task-Flows" } },
    { value: "4", label: { en: "design changes made from test findings", de: "aus Testbefunden umgesetzte Designänderungen" } },
  ],

  techStack: ["Google Forms"],

  about: {
    en: "A four-person course project at Bauhaus-Universität Weimar (summer semester 2023) about what smart-home apps get wrong about shared living. The design problem was never device control — existing apps solve that. It was the social layer of a shared household: who may add a device, who may remove a housemate, who may override someone else mid-use. A questionnaire study (24 responses) framed the territory, a 12-screen paper prototype made a governance model tangible, two think-aloud sessions tested it, and four design changes — each documented as a verbatim participant quote, the change it prompted, and a before/after photograph pair — closed the loop.",
    de: "Ein vierköpfiges Kursprojekt an der Bauhaus-Universität Weimar (Sommersemester 2023) über das, was Smart-Home-Apps am geteilten Wohnen missverstehen. Das Designproblem war nie die Gerätesteuerung — die lösen bestehende Apps. Es war die soziale Ebene eines geteilten Haushalts: Wer darf ein Gerät hinzufügen, wer eine:n Mitbewohner:in entfernen, wer jemanden mitten in der Nutzung übersteuern? Eine Fragebogenstudie (24 Antworten) steckte das Terrain ab, ein Papierprototyp mit 12 Screens machte ein Governance-Modell greifbar, zwei Think-Aloud-Sitzungen testeten es, und vier Designänderungen — jede dokumentiert als wörtliches Teilnehmenden-Zitat, daraus folgende Änderung und Vorher-Nachher-Fotopaar — schlossen den Kreis.",
  },

  challenge: {
    en: "Smart-home apps model a home as one owner and a set of devices. A shared flat fits neither assumption: residents come and go, devices belong to some people and are used by everyone, and the moment two people want the same lamp at once is a social negotiation, not a technical conflict. The project framed exactly that gap — membership, permissions, and simultaneous use — as the design problem.",
    de: "Smart-Home-Apps modellieren ein Zuhause als eine:n Besitzer:in und eine Menge von Geräten. Auf eine geteilte Wohnung passt beides nicht: Mitbewohner:innen kommen und gehen, Geräte gehören einzelnen und werden von allen genutzt, und der Moment, in dem zwei Personen gleichzeitig dieselbe Lampe wollen, ist eine soziale Aushandlung, kein technischer Konflikt. Genau diese Lücke — Mitgliedschaft, Berechtigungen und gleichzeitige Nutzung — rahmte das Projekt als Designproblem.",
  },

  solution: {
    en: "A 12-screen paper prototype covering four documented task flows, all anchored on one home screen. Onboarding runs scanning → naming → access → confirmation, with a three-step progress indicator that deliberately stops at the confirmation screen. Governance is built into the everyday paths rather than an admin area: who may use a device is chosen at setup, residents are invited by link, and a device in use can be locked while in use — resolving simultaneous access without a queue. The galleries below show the tested v1 version, grouped by flow.",
    de: "Ein Papierprototyp mit 12 Screens über vier dokumentierte Task-Flows, alle verankert auf einem Home-Screen. Das Onboarding läuft Scannen → Benennen → Zugriff → Bestätigung, mit einem dreistufigen Fortschrittsindikator, der bewusst am Bestätigungs-Screen endet. Governance steckt in den Alltagspfaden statt in einem Admin-Bereich: Wer ein Gerät nutzen darf, wird beim Einrichten festgelegt, Mitbewohner:innen werden per Link eingeladen, und ein Gerät in Benutzung lässt sich während der Nutzung sperren — gleichzeitiger Zugriff wird so ohne Warteschlange aufgelöst. Die Galerien unten zeigen die getestete v1-Version, nach Flows gruppiert.",
  },

  design: {
    en: "The revision is the most documented part of the project. Both test transcripts were coded into four categories — positive feedback, negative feedback, questions, ideas and suggestions — and four changes were made, each traceable to a verbatim quote from the sessions. They are shown below exactly as they happened: the quote, the change it prompted, and both photographs — the tested v1 screen on the left, the revised v2 screen on the right. The revision also fixed a defect the test itself exposed only indirectly: the resident roster differed across three v1 screens — two residents on one, three on another, five on a third, with the same person written “Drake” on one card and “Jake” on another. The v2 screens normalise the roster everywhere.",
    de: "Die Überarbeitung ist der am besten dokumentierte Teil des Projekts. Beide Test-Transkripte wurden in vier Kategorien kodiert — positives Feedback, negatives Feedback, Fragen, Ideen und Vorschläge — und vier Änderungen umgesetzt, jede rückführbar auf ein wörtliches Zitat aus den Sitzungen. Sie sind unten genau so gezeigt, wie sie passiert sind: das Zitat, die daraus folgende Änderung und beide Fotografien — links der getestete v1-Screen, rechts der überarbeitete v2-Screen. Die Überarbeitung behob auch einen Defekt, den der Test selbst nur indirekt offenlegte: Die Bewohnerliste unterschied sich über drei v1-Screens hinweg — zwei Personen auf einem, drei auf einem anderen, fünf auf einem dritten, dieselbe Person einmal als „Drake“ und einmal als „Jake“ beschriftet. Die v2-Screens normalisieren die Liste überall.",
  },

  methodology: {
    en: "Phase 1 — Discovery. A questionnaire (Google Forms) was chosen over interviews, focus groups, and shadowing: it fit the timeline, and it let respondents answer at their own pace, which supported confidentiality and autonomy. It was piloted with a small group before distribution to check for ambiguity and leading questions; consent was obtained and responses were anonymous. Questions were sequenced deliberately — demographics, then habits, then needs — so respondents were not steered toward an attitude about smart homes early. Of 30 people approached, 24 responded. Roughly a third reported difficulty syncing devices; a quarter named remote adjustment of settings as a persistent pain point. Segmentation produced two named groups — students and part-time employees, and full-time employees — plus an “others” bucket, each with a documented attitude toward smart-home apps and a separate attitude toward mobile services generally. The user profile explicitly included cognitive, visual, and mobility impairment: accessibility was scoped at discovery, not bolted on later. Phase 2 — Evaluation. Two think-aloud sessions in a controlled setting, each participant seated individually with a facilitator. Audio was recorded and photographs taken; participants were briefed on recording and anonymity. The facilitator used probing questions when participants went quiet and observed facial expressions; each session ended with a retrospective debrief. Participant A — 31, a junior software developer. Participant B — 43, with a degree in an unrelated field. Both are iOS users; neither had used a smart-home app before. Transcripts were coded into four categories: positive feedback, negative feedback, questions, and ideas/suggestions.",
    de: "Phase 1 — Discovery. Ein Fragebogen (Google Forms) wurde Interviews, Fokusgruppen und Shadowing vorgezogen: Er passte in den Zeitrahmen, und er ließ die Befragten in ihrem eigenen Tempo antworten, was Vertraulichkeit und Autonomie unterstützte. Vor der Verteilung wurde er mit einer kleinen Gruppe pilotiert, um mehrdeutige und suggestive Fragen zu finden; Einwilligung wurde eingeholt, die Antworten waren anonym. Die Fragen waren bewusst sequenziert — Demografie, dann Gewohnheiten, dann Bedürfnisse —, damit die Befragten nicht früh auf eine Haltung zu Smart Homes gelenkt wurden. Von 30 angefragten Personen antworteten 24. Rund ein Drittel berichtete von Schwierigkeiten beim Synchronisieren von Geräten; ein Viertel nannte das Anpassen von Einstellungen aus der Ferne als anhaltenden Schmerzpunkt. Die Segmentierung ergab zwei benannte Gruppen — Studierende und Teilzeitbeschäftigte sowie Vollzeitbeschäftigte — plus eine „Sonstige“-Gruppe, jede mit einer dokumentierten Haltung zu Smart-Home-Apps und einer separaten Haltung zu mobilen Diensten allgemein. Das Nutzerprofil schloss kognitive, visuelle und motorische Beeinträchtigungen ausdrücklich ein: Barrierefreiheit wurde in der Discovery verankert, nicht nachträglich angebaut. Phase 2 — Evaluation. Zwei Think-Aloud-Sitzungen in kontrollierter Umgebung, jede:r Teilnehmende einzeln mit einer Moderatorin. Audio wurde aufgezeichnet, Fotos wurden gemacht; die Teilnehmenden wurden über Aufzeichnung und Anonymität aufgeklärt. Die Moderatorin stellte Nachfragen, wenn Teilnehmende verstummten, und beobachtete Gesichtsausdrücke; jede Sitzung endete mit einem retrospektiven Debriefing. Teilnehmerin A — 31, Junior-Softwareentwicklerin. Teilnehmer B — 43, Abschluss in einem fachfremden Feld. Beide iOS-Nutzer:innen; keine:r hatte zuvor eine Smart-Home-App verwendet. Die Transkripte wurden in vier Kategorien kodiert: positives Feedback, negatives Feedback, Fragen und Ideen/Vorschläge.",
  },

  results: {
    en: "The findings worth keeping are the ones that did not become quick fixes. A dead end surfaced in a flow we thought was finished: Participant A selected both devices at the scanning step, but only one carried into setup, and the confirmation screen had no way back — she noticed immediately and asked what had happened to the second device. Frames were read as the only tappable things: Participant B tapped only elements with a visible button border, engaging the boxed room selector on the device settings screen and treating the unframed rows beside it as labels. Destructive actions produced anxiety before they produced errors: encountering “delete this room”, Participant A worried aloud about triggering it accidentally and proposed moving room management to a dedicated screen — a structural objection, not a cosmetic one. The method itself was a finding: both participants needed to backtrack, neither could do it while holding the cards, and both ended up laying the prototype out on the floor — A sorting it into order first, B improvising late. And both participants opened every screen by reading its title aloud, which is why the “which home am I in?” gap surfaced on four separate screens. Two participants is a thin sample, and the original report says so. Revisiting the artifacts, the resident roster inconsistency across three tested screens is a defect a heuristic review would have caught before it reached a participant. The same revisiting surfaced a documentation lesson: most of the report's session photographs turn out to show the revised cards rather than the ones tested — the set was re-photographed after the changes were made. The sessions themselves are evidenced by the transcript and by the four changes that came out of them, but I'd now photograph artifacts at the moment of testing rather than afterwards.",
    de: "Die Befunde, die es zu behalten lohnt, sind die, die keine schnellen Fixes wurden. In einem Flow, den wir für fertig hielten, zeigte sich eine Sackgasse: Teilnehmerin A wählte beim Scannen beide Geräte aus, aber nur eines wurde ins Setup übernommen, und der Bestätigungs-Screen bot keinen Weg zurück — sie bemerkte es sofort und fragte, was mit dem zweiten Gerät passiert sei. Rahmen wurden als das einzig Antippbare gelesen: Teilnehmer B tippte nur Elemente mit sichtbarem Button-Rand, nutzte auf dem Geräteeinstellungs-Screen den umrahmten Raumwähler und behandelte die rahmenlosen Zeilen daneben als Beschriftung. Destruktive Aktionen erzeugten Angst, bevor sie Fehler erzeugten: Beim Anblick von „Raum löschen“ sorgte sich Teilnehmerin A laut vor versehentlichem Auslösen und schlug vor, die Raumverwaltung auf einen eigenen Screen zu verlegen — ein struktureller Einwand, kein kosmetischer. Die Methode selbst war ein Befund: Beide Teilnehmenden mussten zurückspringen, keine:r konnte das mit den Karten in der Hand, und beide legten den Prototyp am Ende auf dem Boden aus — A sortierte ihn vorher in Reihenfolge, B improvisierte spät. Und beide Teilnehmenden eröffneten jeden Screen, indem sie seinen Titel laut vorlasen — weshalb die Lücke „In welchem Zuhause bin ich?“ auf vier verschiedenen Screens auftauchte. Zwei Teilnehmende sind eine dünne Stichprobe, und der Originalbericht sagt das auch. Beim erneuten Durchsehen der Artefakte ist die inkonsistente Bewohnerliste über drei getestete Screens hinweg ein Defekt, den eine heuristische Prüfung gefunden hätte, bevor er eine:n Teilnehmende:n erreicht. Dasselbe Durchsehen förderte eine Dokumentations-Lektion zutage: Die meisten Sitzungsfotos des Berichts zeigen die überarbeiteten Karten statt der getesteten — das Set wurde nach den Änderungen erneut fotografiert. Die Sitzungen selbst sind durch das Transkript und die vier daraus entstandenen Änderungen belegt; heute würde ich Artefakte im Moment des Testens fotografieren, nicht danach.",
  },

  // What this study cannot support. The thin sample is named in the
  // original report; the rest follows from the method and the artefacts.
  limitations: [
    {
      en: "Two think-aloud participants is enough to expose a dead end and a misread affordance, not to establish how often either occurs or how severe it is. The original report says so, and no wider round followed.",
      de: "Zwei Think-Aloud-Teilnehmende genügen, um eine Sackgasse und eine fehlgelesene Affordanz aufzudecken — nicht, um deren Häufigkeit oder Schweregrad zu bestimmen. Der Originalbericht sagt das auch, und eine breitere Runde folgte nicht.",
    },
    {
      en: "Both testers were iOS users who had never used a smart-home app, and neither was tested inside an actual shared household — the social situation the design is about was described to them, not lived during the session.",
      de: "Beide Testpersonen waren iOS-Nutzer:innen, die noch nie eine Smart-Home-App verwendet hatten, und keine wurde in einem tatsächlich geteilten Haushalt getestet — die soziale Situation, um die es im Design geht, wurde ihnen beschrieben, nicht in der Sitzung erlebt.",
    },
    {
      en: "The questionnaire (24 of 30 people approached) was distributed through the team's own reach, so it framed the territory and named pain points; it was never a representative sample of shared-flat residents.",
      de: "Der Fragebogen (24 von 30 angefragten Personen) wurde über die Reichweite des Teams verteilt — er steckte das Terrain ab und benannte Schmerzpunkte, war aber nie eine repräsentative Stichprobe von WG-Bewohnenden.",
    },
    {
      en: "A paper prototype cannot produce the conflict the project is about: no device latency, no second resident acting at the same moment. Simultaneous use could only be walked through, never experienced.",
      de: "Ein Papierprototyp kann den Konflikt, um den es geht, nicht erzeugen: keine Gerätelatenz, keine zweite Person, die im selben Moment handelt. Gleichzeitige Nutzung ließ sich nur durchsprechen, nie erleben.",
    },
    {
      en: "The v2 revision was never put in front of a participant, so the four changes are reasoned responses to observed problems — not changes shown to have fixed them.",
      de: "Die v2-Überarbeitung lag nie einer Testperson vor; die vier Änderungen sind daher begründete Antworten auf beobachtete Probleme — nicht Änderungen, deren Wirkung belegt ist.",
    },
    {
      en: "The photographic record is weaker than the sessions were: most session photographs in the report show the revised cards, because the set was re-photographed after the changes. What was tested is evidenced by the transcript, not by the photos.",
      de: "Die fotografische Dokumentation ist schwächer als die Sitzungen selbst: Die meisten Sitzungsfotos im Bericht zeigen die überarbeiteten Karten, weil das Set nach den Änderungen neu fotografiert wurde. Belegt ist das Getestete durch das Transkript, nicht durch die Fotos.",
    },
  ],

  // "academic", like the other university projects (gaze, embraceme):
  // adoption in the product sense doesn't apply. The body states only what
  // the documentation contains — the course ended at the v2 revision; no
  // second test round exists in the report.
  outcome: {
    body: {
      en: "A university course project — adoption in the product sense doesn't apply. What the course closed on is the revised v2 prototype: four changes, each documented as a participant quote, the change it prompted, and a before/after photograph pair. The revision itself was never put in front of another participant — re-testing it is where a next session would have to start.",
      de: "Ein universitäres Kursprojekt — Adoption im produktbezogenen Sinne ist hier nicht anwendbar. Der Kurs endete mit dem überarbeiteten v2-Prototyp: vier Änderungen, jede dokumentiert als Teilnehmenden-Zitat, daraus folgende Änderung und Vorher-Nachher-Fotopaar. Die Überarbeitung selbst lag nie wieder einer Testperson vor — ihr erneuter Test wäre der Startpunkt einer nächsten Sitzung.",
    },
    adoption: "academic",
  },

  // Verbatim transcript quotes from the two think-aloud sessions — the
  // evidence for findings 1–3 in Results. Sourced from the report's
  // transcript table (section 5.1); wording untouched.
  verbatims: [
    {
      quote: {
        en: "Now I can go to the device… but what happened to the other device that I selected two steps ago? … there is not even any back button here…",
        de: "Jetzt kann ich zum Gerät gehen … aber was ist mit dem anderen Gerät passiert, das ich vor zwei Schritten ausgewählt habe? … Hier gibt es nicht einmal einen Zurück-Button …",
      },
      attribution: {
        en: "Participant A, screen E — discovering the onboarding dead end",
        de: "Teilnehmerin A, Screen E — beim Entdecken der Onboarding-Sackgasse (Zitate aus dem Englischen übersetzt)",
      },
    },
    {
      quote: {
        en: "I'm worried about this option... What if I delete it accidentally?",
        de: "Diese Option macht mir Sorgen … Was, wenn ich es versehentlich lösche?",
      },
      attribution: {
        en: "Participant A, screen F (room view) — on “delete this room”, before proposing a dedicated room-management screen",
        de: "Teilnehmerin A, Screen F (Raumansicht) — zu „Delete this room“, bevor sie einen eigenen Raumverwaltungs-Screen vorschlug",
      },
    },
    {
      quote: {
        en: "what can I do with this radar? Is it clickable?",
        de: "Was kann ich mit diesem Radar machen? Ist es klickbar?",
      },
      attribution: {
        en: "Participant B, screen B — the frames-are-tappable pattern, in his own words",
        de: "Teilnehmer B, Screen B — das Muster „nur Gerahmtes ist antippbar“, in seinen eigenen Worten",
      },
    },
  ],

  figures: {
    solution: [
      {
        type: "image",
        src: v1FlowMap,
        span: 2,
        label: { en: "The tested set", de: "Das getestete Set" },
        title: { en: "The full v1 prototype, laid out as a flow map", de: "Der vollständige v1-Prototyp, als Flow-Karte ausgelegt" },
        description: {
          en: "All 12 screens and both bottom sheets, connected with torn-paper directional arrows — the exact set the two think-aloud sessions tested. The closing image at the end of the page shows the revised v2 counterpart the four changes produced.",
          de: "Alle 12 Screens und beide Bottom Sheets, verbunden mit Richtungspfeilen aus gerissenem Papier — genau das Set, das die beiden Think-Aloud-Sitzungen getestet haben. Das Schlussbild am Seitenende zeigt das überarbeitete v2-Gegenstück, das die vier Änderungen hervorgebracht haben.",
        },
        alt: {
          en: "The tested v1 paper prototype laid out as a flow map: home, room view, device control, the onboarding screens, profile and both bottom sheets, connected by torn-paper arrows",
          de: "Der getestete v1-Papierprototyp als ausgelegte Flow-Karte: Home, Raumansicht, Gerätesteuerung, die Onboarding-Screens, Profil und beide Bottom Sheets, verbunden durch Pfeile aus gerissenem Papier",
        },
        caption: { en: "v1 · the full tested set — its revised counterpart closes the page", de: "v1 · das vollständige getestete Set — sein überarbeitetes Gegenstück beschließt die Seite" },
      },
      {
        type: "image",
        src: v1A,
        span: 2,
        label: { en: "The anchor screen", de: "Der Anker-Screen" },
        title: { en: "Home — every flow starts here", de: "Home — jeder Flow beginnt hier" },
        description: {
          en: "A horizontal carousel of homes at the top, rooms as toggle rows, and a frequently-used device strip. All four documented flows depart from this screen.",
          de: "Oben ein horizontales Karussell der Zuhause, Räume als Toggle-Zeilen, darunter eine Leiste häufig genutzter Geräte. Alle vier dokumentierten Flows starten auf diesem Screen.",
        },
        alt: {
          en: "Hand-drawn paper prototype home screen: 'Josh's Home' card in a carousel, room list with toggles, frequently used devices, tab bar with Add Device, Home, Profile",
          de: "Handgezeichneter Papierprototyp-Home-Screen: Karte „Josh's Home“ im Karussell, Raumliste mit Toggles, häufig genutzte Geräte, Tab-Leiste mit Add Device, Home, Profile",
        },
        caption: { en: "v1 · screen A — home", de: "v1 · Screen A — Home" },
      },
      {
        type: "image",
        src: v1B,
        span: 2,
        label: { en: "Flow 1 · onboarding a device", de: "Flow 1 · Gerät hinzufügen" },
        title: { en: "Scanning, with a live found-count", de: "Scannen, mit Live-Fundzähler" },
        description: {
          en: "Scanning → naming → access → confirmation. A three-step progress indicator runs through the first three screens and deliberately stops at the confirmation. The found-devices list grows during the scan — which is exactly where the test later surfaced a dead end.",
          de: "Scannen → Benennen → Zugriff → Bestätigung. Ein dreistufiger Fortschrittsindikator begleitet die ersten drei Screens und endet bewusst vor der Bestätigung. Die Liste gefundener Geräte wächst während des Scans — genau hier legte der Test später eine Sackgasse offen.",
        },
        alt: {
          en: "Paper prototype scanning screen: radar sketch searching for compatible devices nearby, found list with Dryer and Smart Light, each with a select button, live count of found devices",
          de: "Papierprototyp-Scan-Screen: Radar-Skizze sucht kompatible Geräte in der Nähe, Fundliste mit Dryer und Smart Light, je mit Select-Button, Live-Zähler der Funde",
        },
        caption: { en: "v1 · screen B — add a device", de: "v1 · Screen B — Gerät hinzufügen" },
      },
      {
        type: "image",
        src: v1C,
        printHidden: true,
        alt: {
          en: "Paper prototype naming screen: device name field prefilled 'Smart Light', room list with an inline 'add new room' action",
          de: "Papierprototyp-Benennungs-Screen: Namensfeld mit „Smart Light“ vorausgefüllt, Raumliste mit Inline-Aktion „Add new room“",
        },
        caption: { en: "v1 · screen C — naming, with inline room creation", de: "v1 · Screen C — Benennen, mit Inline-Raumanlage" },
      },
      {
        type: "image",
        src: v1D,
        printHidden: true,
        alt: {
          en: "Paper prototype access screen: 'Choose device users' checklist of residents, decided at device setup",
          de: "Papierprototyp-Zugriffs-Screen: Checkliste „Choose device users“ der Bewohner:innen, festgelegt beim Einrichten",
        },
        caption: { en: "v1 · screen D — per-device access chosen at setup", de: "v1 · Screen D — Gerätezugriff beim Einrichten gewählt" },
      },
      {
        type: "image",
        src: v1E,
        printHidden: true,
        alt: {
          en: "Paper prototype confirmation screen: checkmark, 'your device has been successfully added', a single 'Go to device' action and no back affordance",
          de: "Papierprototyp-Bestätigungs-Screen: Haken, „your device has been successfully added“, einzige Aktion „Go to device“, keine Zurück-Option",
        },
        caption: { en: "v1 · screen E — confirmation; the progress indicator has deliberately ended", de: "v1 · Screen E — Bestätigung; der Fortschrittsindikator ist hier bewusst zu Ende" },
      },
      // Note: the v1 device-control screen (G) shows a "Manage Access" row
      // that is absent from the v2 shot, and the report's list of post-test
      // changes does not mention this screen. v1 is treated as canonical
      // here and no iteration story is built on it.
      {
        type: "image",
        src: v1G,
        span: 2,
        label: { en: "Flow 2 · controlling and sharing", de: "Flow 2 · Steuern und Teilen" },
        title: { en: "Device control: brightness mapping and named presets", de: "Gerätesteuerung: Helligkeits-Mapping und benannte Presets" },
        description: {
          en: "Room view → device control → device settings → two bottom sheets. The control screen maps brightness onto a slider and offers named presets; sharing constraints live in the same flow rather than an admin area.",
          de: "Raumansicht → Gerätesteuerung → Geräteeinstellungen → zwei Bottom Sheets. Der Steuerungs-Screen bildet Helligkeit auf einen Slider ab und bietet benannte Presets; Regeln fürs Teilen wohnen im selben Flow statt in einem Admin-Bereich.",
        },
        alt: {
          en: "Paper prototype smart light control screen: brightness slider, named presets Focus, Chill and Vibe, add-new-preset action, manage access row, and a lock-while-in-use toggle",
          de: "Papierprototyp-Steuerungs-Screen der Smart Light: Helligkeits-Slider, benannte Presets Focus, Chill und Vibe, Aktion für neues Preset, Zeile „Manage Access“ und ein „Lock while in use“-Toggle",
        },
        caption: { en: "v1 · screen G — smart light control", de: "v1 · Screen G — Smart-Light-Steuerung" },
      },
      {
        type: "image",
        src: v1F,
        printHidden: true,
        alt: {
          en: "Paper prototype room view: Living Room device list with Speaker, Smart TV, Air Conditioner, Smart Light, add-new-device action and a delete-this-room action",
          de: "Papierprototyp-Raumansicht: Geräteliste des Wohnzimmers mit Speaker, Smart TV, Air Conditioner, Smart Light, Aktion „Add new device“ und „Delete this room“",
        },
        caption: { en: "v1 · screen F — room view", de: "v1 · Screen F — Raumansicht" },
      },
      {
        type: "image",
        src: v1H,
        printHidden: true,
        alt: {
          en: "Paper prototype device settings screen: edit device users, change room with the current room in a boxed selector, delete device",
          de: "Papierprototyp-Geräteeinstellungen: Edit device users, Change room mit aktuellem Raum im umrahmten Wähler, Delete device",
        },
        caption: { en: "v1 · screen H — device settings", de: "v1 · Screen H — Geräteeinstellungen" },
      },
      {
        type: "image",
        src: v1I,
        printHidden: true,
        alt: {
          en: "Paper prototype bottom sheet for selecting a room, its paper cut with rounded top corners",
          de: "Papierprototyp-Bottom-Sheet zur Raumwahl, das Papier mit abgerundeten oberen Ecken zugeschnitten",
        },
        caption: {
          en: "v1 · sheet I — select room. Both sheets are cut with rounded top corners, so the paper itself carries the component's affordance",
          de: "v1 · Sheet I — Raum wählen. Beide Sheets sind mit abgerundeten oberen Ecken geschnitten — das Papier selbst trägt die Affordanz der Komponente",
        },
      },
      {
        type: "image",
        src: v1J,
        printHidden: true,
        alt: {
          en: "Paper prototype bottom sheet for editing device users, a checklist of residents with a done action",
          de: "Papierprototyp-Bottom-Sheet zum Bearbeiten der Gerätenutzer:innen, Checkliste der Bewohner:innen mit Done-Aktion",
        },
        caption: { en: "v1 · sheet J — edit device users", de: "v1 · Sheet J — Gerätenutzer:innen bearbeiten" },
      },
      {
        type: "video",
        src: bottomSheetsVideo,
        poster: bottomSheetsPoster,
        span: 2,
        alt: {
          en: "3.6-second clip: a paper bottom sheet slides up over the device settings screen, operated by hand",
          de: "3,6-Sekunden-Clip: Ein Papier-Bottom-Sheet schiebt sich von Hand über den Geräteeinstellungs-Screen",
        },
        caption: {
          en: "The sheets in motion — a 3.6-second clip of the bottom sheet sliding over the device settings screen. The only motion asset of the study; no still conveys it",
          de: "Die Sheets in Bewegung — ein 3,6-Sekunden-Clip des Bottom Sheets über dem Geräteeinstellungs-Screen. Das einzige Bewegtbild der Studie; kein Standbild transportiert es",
        },
      },
      {
        type: "image",
        src: v1K,
        span: 2,
        label: { en: "Flow 3 · governing the household", de: "Flow 3 · Den Haushalt verwalten" },
        title: { en: "Residents, invited by link", de: "Bewohner:innen, eingeladen per Link" },
        description: {
          en: "Residents with invite-by-link → per-resident actions → account. Membership is a first-class part of the app, not a settings afterthought — this screen is also where the test produced its second design change.",
          de: "Bewohner:innen mit Link-Einladung → Aktionen pro Person → Konto. Mitgliedschaft ist ein vollwertiger Teil der App, kein Nachgedanke in den Einstellungen — auf diesem Screen entstand auch die zweite Designänderung des Tests.",
        },
        alt: {
          en: "Paper prototype home settings screen: editable home name, add/remove residents list with inline remove actions, invite new resident with a link, delete home",
          de: "Papierprototyp-Home-Settings-Screen: editierbarer Name des Zuhauses, Bewohnerliste mit Inline-Remove-Aktionen, Link-Einladung neuer Bewohner:innen, Delete Home",
        },
        caption: { en: "v1 · screen K — home settings", de: "v1 · Screen K — Home Settings" },
      },
      {
        type: "image",
        src: v1L,
        printHidden: true,
        alt: {
          en: "Paper prototype profile screen: avatar, name, email and password rows with edit actions, your-devices strip with a view-all card, log out and delete account",
          de: "Papierprototyp-Profil-Screen: Avatar, Zeilen für Name, E-Mail und Passwort mit Edit-Aktionen, Geräteleiste mit View-All-Karte, Log-out und Delete Account",
        },
        caption: { en: "v1 · screen L — account", de: "v1 · Screen L — Konto" },
      },
    ],

    design: [
      // Pair 1 — quote → change → before/after. v1 left, v2 right.
      {
        type: "image",
        src: v1A,
        label: { en: "Change 1 · Participant A, screen A", de: "Änderung 1 · Teilnehmerin A, Screen A" },
        title: { en: "A selection indicator for the active home", de: "Ein Auswahlindikator für das aktive Zuhause" },
        description: {
          en: "“the Rooms belong to which Home? it's a bit unclear” — the home carousel gave no cue which home the rooms below belong to. The change: a selection indicator on the active home card.",
          de: "„the Rooms belong to which Home? it's a bit unclear“ („Zu welchem Zuhause gehören die Räume? Das ist etwas unklar“) — das Karussell zeigte nicht, zu welchem Zuhause die Räume darunter gehören. Die Änderung: ein Auswahlindikator auf der aktiven Karte.",
        },
        alt: {
          en: "Before, v1: the home screen's carousel with no indication of which home is selected",
          de: "Vorher, v1: das Home-Karussell ohne Hinweis, welches Zuhause ausgewählt ist",
        },
        caption: { en: "before · v1", de: "Vorher · v1" },
      },
      {
        type: "image",
        src: v2A,
        alt: {
          en: "After, v2: the same home screen, now with a green highlighter bracket along the bottom and right edge of the Josh's Home card marking it as selected",
          de: "Nachher, v2: derselbe Home-Screen, jetzt mit grüner Textmarker-Klammer an Unter- und rechter Kante der Karte „Josh's Home“ als Auswahlmarkierung",
        },
        caption: {
          en: "after · v2 — the green highlighter bracket along the bottom and right edge of the “Josh's Home” card is the fix: it marks the selected home",
          de: "Nachher · v2 — die grüne Textmarker-Klammer an Unter- und rechter Kante der Karte „Josh's Home“ ist der Fix: Sie markiert das ausgewählte Zuhause",
        },
        takeaway: {
          en: "Both participants read every screen title aloud, and the “which home am I in?” gap surfaced on four separate screens — this one marker answers it at the source.",
          de: "Beide Teilnehmenden lasen jeden Screen-Titel laut, und die Lücke „In welchem Zuhause bin ich?“ zeigte sich auf vier Screens — diese eine Markierung beantwortet sie an der Quelle.",
        },
      },
      // Pair 2
      {
        type: "image",
        src: v1K,
        label: { en: "Change 2 · Participant A, screen K", de: "Änderung 2 · Teilnehmerin A, Screen K" },
        title: { en: "From inline remove to a per-resident menu", de: "Von Inline-Remove zum Menü pro Person" },
        description: {
          en: "“I can see the REMOVE buttons, but I don't see any ADD buttons” — the roster offered removal as its only visible per-resident action. The change: the inline remove is replaced by a per-resident menu covering both removal and role assignment.",
          de: "„I can see the REMOVE buttons, but I don't see any ADD buttons“ („Ich sehe die REMOVE-Buttons, aber keine ADD-Buttons“) — die Liste bot Entfernen als einzige sichtbare Aktion pro Person. Die Änderung: Das Inline-Remove weicht einem Menü pro Person für Entfernen und Rollenvergabe.",
        },
        alt: {
          en: "Before, v1: home settings with an inline REMOVE action beside each resident",
          de: "Vorher, v1: Home Settings mit Inline-REMOVE neben jeder Person",
        },
        caption: { en: "before · v1", de: "Vorher · v1" },
      },
      {
        type: "image",
        src: v2K,
        alt: {
          en: "After, v2: 'Manage residents' with a three-dot menu per resident instead of inline remove, and the roster normalised to five residents",
          de: "Nachher, v2: „Manage residents“ mit Drei-Punkte-Menü pro Person statt Inline-Remove, die Bewohnerliste überall auf fünf Personen normalisiert",
        },
        caption: {
          en: "after · v2 — a ⋮ menu per resident; the erased inline REMOVE is still faintly visible on the paper",
          de: "Nachher · v2 — ein ⋮-Menü pro Person; das wegradierte Inline-REMOVE ist auf dem Papier noch schwach zu sehen",
        },
        takeaway: {
          en: "A structural change, not a relabel: one affordance per resident now carries every membership action, and the roster is consistent across all revised screens.",
          de: "Eine strukturelle Änderung, kein Umbenennen: Eine Affordanz pro Person trägt jetzt alle Mitgliedschafts-Aktionen, und die Bewohnerliste ist über alle überarbeiteten Screens konsistent.",
        },
      },
      {
        type: "image",
        src: v2M,
        span: 2,
        alt: {
          en: "The v2 per-resident menu itself, a small paper popover with two actions: remove user and make admin",
          de: "Das v2-Menü pro Person, ein kleines Papier-Popover mit zwei Aktionen: Remove User und Make Admin",
        },
        caption: {
          en: "the menu behind change 2's ⋮ affordance — removal and role assignment in one place (v2, screen M)",
          de: "das Menü hinter der ⋮-Affordanz aus Änderung 2 — Entfernen und Rollenvergabe an einem Ort (v2, Screen M)",
        },
      },
      // Pair 3
      {
        type: "image",
        src: v1L,
        label: { en: "Change 3 · Participant A, screen L", de: "Änderung 3 · Teilnehmerin A, Screen L" },
        title: { en: "An edit affordance on the avatar", de: "Eine Edit-Affordanz auf dem Avatar" },
        description: {
          en: "“I also like to be able to add/edit my profile picture” — the profile's avatar was display-only. The change: an edit affordance on the avatar itself.",
          de: "„I also like to be able to add/edit my profile picture“ („Ich möchte auch mein Profilbild hinzufügen/bearbeiten können“) — der Avatar im Profil war reine Anzeige. Die Änderung: eine Edit-Affordanz direkt auf dem Avatar.",
        },
        alt: {
          en: "Before, v1: profile screen with a plain avatar and no edit affordance",
          de: "Vorher, v1: Profil-Screen mit schlichtem Avatar ohne Edit-Affordanz",
        },
        caption: { en: "before · v1", de: "Vorher · v1" },
      },
      {
        type: "image",
        src: v2L,
        alt: {
          en: "After, v2: the profile avatar now carries a pencil edit affordance",
          de: "Nachher, v2: der Profil-Avatar trägt jetzt eine Stift-Affordanz zum Bearbeiten",
        },
        caption: { en: "after · v2 — a pencil on the avatar", de: "Nachher · v2 — ein Stift auf dem Avatar" },
      },
      // Pair 4 — same screen pair as 3; the second change on L.
      {
        type: "image",
        src: v1L,
        label: { en: "Change 4 · Participant A, screen L", de: "Änderung 4 · Teilnehmerin A, Screen L" },
        title: { en: "“View all” promoted to the section header", de: "„View all“ in den Abschnittskopf befördert" },
        description: {
          en: "“you can move the VIEW ALL button on top, similar to the design of the previous pages” — in v1, view-all sat as a fourth card at the end of the device strip. The change promotes it to a section-header link, matching the pattern the home screen already uses.",
          de: "„you can move the VIEW ALL button on top, similar to the design of the previous pages“ („Ihr könnt den VIEW-ALL-Button nach oben setzen, wie auf den vorherigen Seiten“) — in v1 saß View-all als vierte Karte am Ende der Geräteleiste. Die Änderung befördert ihn zum Link im Abschnittskopf, dem Muster des Home-Screens folgend.",
        },
        alt: {
          en: "Before, v1: the your-devices strip ends in a 'view all' card cut off at the screen edge",
          de: "Vorher, v1: die Geräteleiste endet in einer am Screenrand angeschnittenen „View all“-Karte",
        },
        caption: { en: "before · v1", de: "Vorher · v1" },
      },
      {
        type: "image",
        src: v2L,
        alt: {
          en: "After, v2: 'view all' now sits in the your-devices section header, matching the home screen's all-devices pattern",
          de: "Nachher, v2: „View all“ sitzt jetzt im Kopf des Geräte-Abschnitts, analog zum All-Devices-Muster des Home-Screens",
        },
        caption: {
          en: "after · v2 — “view all ›” in the section header, as on the home screen",
          de: "Nachher · v2 — „View all ›“ im Abschnittskopf, wie auf dem Home-Screen",
        },
        takeaway: {
          en: "Participant A's own words named the principle: consistency with “the design of the previous pages”. The fix is the pattern the app already had.",
          de: "Teilnehmerin A benannte das Prinzip selbst: Konsistenz mit „dem Design der vorherigen Seiten“. Der Fix ist das Muster, das die App schon hatte.",
        },
      },
    ],

    methodology: [
      {
        type: "image",
        src: v1Cheatsheet,
        span: 2,
        label: { en: "Flow mapping", de: "Flow-Mapping" },
        title: { en: "The facilitator's flow cheatsheet", de: "Der Flow-Spickzettel der Moderatorin" },
        description: {
          en: "Four hand-written cards documenting every task flow in the letter vocabulary the screens are named by: add a device (A–B–C–D–E–G–H), device flow (A–F–G–H), profile (A–L), home options (A–K) — including the conditional branches into the two bottom sheets I and J.",
          de: "Vier handgeschriebene Karten dokumentieren jeden Task-Flow im Buchstaben-Vokabular der Screens: Gerät hinzufügen (A–B–C–D–E–G–H), Geräte-Flow (A–F–G–H), Profil (A–L), Home-Optionen (A–K) — samt der bedingten Verzweigungen in die beiden Bottom Sheets I und J.",
        },
        alt: {
          en: "Four handwritten cheatsheet cards listing the screen sequences of the four task flows, with conditional arrows into bottom sheets I and J",
          de: "Vier handgeschriebene Spickzettel-Karten mit den Screen-Sequenzen der vier Task-Flows und bedingten Pfeilen in die Bottom Sheets I und J",
        },
        caption: { en: "the facilitator's branching script for the four task flows", de: "das Verzweigungsskript der Moderatorin für die vier Task-Flows" },
      },
      // Chart provenance: the study itself never visualised the 24
      // responses. This figure is tallied directly from the raw response
      // sheet by scripts/generate-smart-home-chart.mjs — made for the case
      // study FROM the primary data, which is exactly what the caption
      // discloses. Never restyle it into implying the study produced it.
      {
        type: "image",
        src: discoveryChart,
        span: 2,
        label: { en: "Discovery data", de: "Discovery-Daten" },
        title: {
          en: "What respondents find difficult in smart-home apps",
          de: "Was Befragte an Smart-Home-Apps schwierig finden",
        },
        description: {
          en: "The questionnaire's multi-select difficulty question — verbatim: “What do you generally find difficult while using these apps?” — tallied per option. Device syncing (5 mentions among the 16 who answered — roughly a third) and remote adjustment of settings (4 — a quarter) are the two pain points the discovery findings cite, and the flows answered them directly.",
          de: "Die Multi-Select-Frage des Fragebogens zu Schwierigkeiten — im Original: „What do you generally find difficult while using these apps?“ — pro Option ausgezählt. Geräte-Synchronisierung (5 Nennungen unter den 16 Antwortenden — rund ein Drittel) und das Anpassen von Einstellungen aus der Ferne (4 — ein Viertel) sind die beiden Schmerzpunkte, die die Discovery-Befunde zitieren, und die Flows beantworteten sie direkt.",
        },
        alt: {
          en: "Horizontal bar chart of difficulty mentions: connection problems 7, syncing devices 5, adjusting settings remotely 4, overall usability and UX 4, finding settings and controls 3, understanding the features 2, using them with multiple people 1, cross-platform compatibility (write-in) 1; set apart, nothing difficult 2. Syncing and remote adjustment are marked as having shaped the prototype",
          de: "Horizontales Balkendiagramm der Schwierigkeits-Nennungen: Verbindungsprobleme 7, Geräte-Synchronisierung 5, Einstellungen aus der Ferne anpassen 4, allgemeine Usability und UX 4, Einstellungen und Bedienelemente finden 3, Funktionen verstehen 2, Nutzung mit mehreren Personen 1, Plattformübergreifende Kompatibilität (Freitext) 1; abgesetzt: nichts schwierig 2. Synchronisierung und Fernanpassung sind als prototyp-prägend markiert",
        },
        caption: {
          en: "charted for this case study from the raw response sheet — the study itself never visualised the questionnaire data",
          de: "für diese Fallstudie aus dem rohen Antwortdatensatz erstellt — die Studie selbst hat die Fragebogendaten nie visualisiert",
        },
      },
      {
        type: "image",
        src: sessionToggle,
        label: { en: "Session documentation", de: "Sitzungsdokumentation" },
        alt: {
          en: "Participant B's hands holding the paper home screen over an open laptop, thumb simulating a room toggle; slight motion blur",
          de: "Die Hände von Teilnehmer B halten den Papier-Home-Screen über einem offenen Laptop, der Daumen simuliert einen Raum-Toggle; leichte Bewegungsunschärfe",
        },
        caption: {
          en: "Participant B simulating a toggle to activate a room on the home screen — shot over an open laptop mid-session; the imperfection is the evidence",
          de: "Teilnehmer B simuliert einen Toggle, um einen Raum auf dem Home-Screen zu aktivieren — mitten in der Sitzung über einem offenen Laptop fotografiert; die Unvollkommenheit ist der Beleg",
        },
      },
    ],
  },

  conclusion: [
    {
      type: "image",
      src: v2FlowMap,
      span: 2,
      label: { en: "Closing image", de: "Schlussbild" },
      title: { en: "The revised flow, laid out", de: "Der überarbeitete Flow, ausgelegt" },
      description: {
        en: "The Solution galleries opened on the tested v1 set laid out with torn-paper arrows; the page closes on the revised v2 set the four changes produced. The selection indicator, the per-resident menu with its overlay, the edit affordance on the avatar, and the promoted view-all are all in place — and the roster reads the same on every card.",
        de: "Die Solution-Galerien begannen mit dem getesteten v1-Set samt Pfeilen aus gerissenem Papier; die Seite endet mit dem überarbeiteten v2-Set, das die vier Änderungen hervorgebracht haben. Der Auswahlindikator, das Menü pro Person mit seinem Overlay, die Edit-Affordanz auf dem Avatar und das beförderte View-all sind an ihrem Platz — und die Bewohnerliste liest sich auf jeder Karte gleich.",
      },
      alt: {
        en: "The revised v2 paper prototype laid out as a flow map with torn-paper arrows: home, living room, smart light, device settings and both bottom sheets across the middle; manage residents with the remove-user/make-admin overlay at the top; the onboarding flow with the normalised five-name roster down the left; profile with view-all in the section header at the centre",
        de: "Der überarbeitete v2-Papierprototyp als ausgelegte Flow-Karte mit Pfeilen aus gerissenem Papier: Home, Wohnzimmer, Smart Light, Geräteeinstellungen und beide Bottom Sheets in der Mitte; Manage Residents mit dem Remove-User/Make-Admin-Overlay oben; der Onboarding-Flow mit der normalisierten Fünf-Namen-Liste links; Profil mit View-all im Abschnittskopf in der Mitte",
      },
      caption: {
        en: "v2 · the full revised set — compare the v1 layout that opens the Solution galleries",
        de: "v2 · das vollständige überarbeitete Set — zum Vergleich die v1-Auslage am Anfang der Solution-Galerien",
      },
    },
  ],

  tagEvidence: [
    { tag: "Questionnaire Study", evidence: "methodology: Google Forms questionnaire, piloted before distribution, consent obtained, responses anonymous, 24 of 30 approached responded; metrics: \"24 questionnaire responses\"", status: "evidenced" },
    { tag: "Think-Aloud Testing", evidence: "methodology: two think-aloud sessions in a controlled setting with facilitator, audio recording, probing questions and retrospective debrief; results: the five findings; metrics: \"2 think-aloud usability test participants\"", status: "evidenced" },
    { tag: "Paper Prototyping", evidence: "solution: 12-screen paper prototype across 4 flows; figures.solution: photographed v1 screens A–L including the rounded-corner bottom sheets and the motion clip", status: "evidenced" },
    { tag: "Qualitative Coding", evidence: "methodology: \"Transcripts were coded into four categories: positive feedback, negative feedback, questions, and ideas/suggestions\"; design: every change traceable to a coded verbatim quote", status: "evidenced" },
    { tag: "Thematic Analysis", evidence: "methodology: segmentation of questionnaire responses into two named groups plus an others bucket, each with documented attitudes toward smart-home apps and mobile services generally", status: "evidenced" },
    { tag: "Information Architecture", evidence: "solution: governance built into the everyday paths (access at setup, invite-by-link, lock while in use); results: Participant A's structural objection to where room management lives", status: "evidenced" },
    { tag: "User Flow Mapping", evidence: "figures.methodology: the handwritten flow cheatsheet documenting all four flows with conditional branches; the hero image is the v1 flow map laid out with torn-paper arrows", status: "evidenced" },
    { tag: "Iterative Design", evidence: "design: four quote → change → before/after pairs, v1 tested and v2 revised; figures.design shows each pair photographically", status: "evidenced" },
    { tag: "Accessibility", evidence: "methodology: \"The user profile explicitly included cognitive, visual, and mobility impairment: accessibility was scoped at discovery\"; the concept kept a voice-command microphone always accessible for users who struggle to read or navigate the app — scoped and designed for, but not tested with impaired participants", status: "thin" },
    { tag: "Smart Home", evidence: "challenge: the domain framing — membership, permissions and simultaneous use in a shared smart home; the entire prototype is a smart-home control app", status: "evidenced" },
    { tag: "Google Forms", evidence: "techStack: [\"Google Forms\"]; methodology: the questionnaire ran on Google Forms and was piloted before distribution", status: "evidenced" },
  ],
};

export default projectData;
