// Generated by scripts/generate-chat-knowledge.mjs — do not edit by hand.
// Derived from src/data/data.json and src/projects/*/<slug>.data.js (English locale).
export default {
 "profile": {
  "name": "Sanaz Yazdanjoo",
  "role": "UX Engineer",
  "tagline": "I speak both ‘user’ & ‘developer’.",
  "positioning": "I study how people use technology, uncover their needs and challenges, turn those findings into product decisions, build the interfaces that put those decisions into practice, and validate whether they work.",
  "profileSummary": "UX Engineer bridging research, design & usability, and implementation & validation. With an M.Sc. in Human-Computer Interaction and a Software Engineering background, I move from evidence about user needs to product decisions, working interfaces, and validated outcomes.",
  "impactStats": [
   {
    "value": "N=30",
    "label": "Controlled eye-tracking experiment"
   },
   {
    "value": "120+",
    "label": "Study participants across projects"
   },
   {
    "value": "Since 2015",
    "label": "Digital-product experience across frontend, QA/usability & UX engineering"
   }
  ],
  "bioParagraphs": [
   "I'm a UX Engineer with an M.Sc. in Human-Computer Interaction and a B.E. in Software Engineering. My path through frontend development, QA and HCI research taught me to look at digital products from both sides: what people need and what teams can realistically build. Today I bring those perspectives together in research, design & usability, and implementation & validation."
  ],
  "experience": [
   {
    "company": "Institut für Berufsbildung und Sozialmanagement (IBS)",
    "role": "UX Engineer & Project Assistant",
    "date": "12/2024 – Present",
    "impactMetrics": [
     "13-step paper process, 4 return loops, 9 actors",
     "1,734 automated tests, CI-enforced requirement traceability",
     "25 problems documented, each evidence-graded"
    ],
    "tasks": [
     "Mapped the as-is reimbursement process across 9 actor roles — 13 steps with 4 return loops — using UML swimlane activity diagrams, 5W1H problem framing and stakeholder mapping. Evidence base: more than a year administering the process as project assistant (collecting receipts, consolidating Excel sheets, calculating participants’ reimbursements), 2 expert interviews (project management, accounting), a working meeting with the administration team, and an open participant survey.",
     "Clustered the findings into a problem register of 25 documented problems, each carrying an evidence grade — confirmed, indicative, hypothesis, untested — and derived numbered FR/NFR requirements, a role-based sitemap and seven provenance-labelled personas from it. The survey was designed to falsify my own assumptions: it reversed one of my priorities and added 6 problems I had not seen from the inside.",
     "Built the replacement application single-handedly (React, TypeScript, Vite, Node.js/Fastify, SQLite, Vitest): five roles with scoped navigation and route guards across four role home screens, a role-keyed status transition table enforced in the repository layer, and a reimbursement amount that is not persisted — every screen that shows it calls the same pure domain package, with the calculation trace on screen. The only stored amount is the figure imported from the old spreadsheet, kept solely to flag a discrepancy. 1,734 automated tests, root and server suites, both run in CI.",
     "Wired requirement traceability into the build: a CI test fails when a requirement or problem id cited in source has no row in the requirements register, so a citation can never quietly lose its source. The guard checks citation to row, not row to implementation, and the register says so.",
     "Extracted the design system before the high-fidelity screens: the 9 lane colours of the research activity diagram became the application's role palette unchanged, so an actor in the research reads as the same actor in the app. A CI test fails the build when a colour token in the CSS token file and the Tailwind config drift apart.",
     "Secured the Fastify (Node.js) backend with session authentication (argon2id), CSRF tokens on every mutating route, global and per-route rate limits, and default-deny access control in the repository layer. Login hashes against a placeholder for unknown accounts so response time cannot leak whether an address exists, and every request re-checks the credential version, so a password change ends other sessions immediately.",
     "Designed the data handling for privacy: participant data lives in the local SQLite database and is mirrored only to the institute's own Nextcloud, event logging is pseudonymous, and cookies and authorization headers are redacted from server logs. A CI test scans the built bundle for any hostname outside an allowlist; another scans for real participant names. The one third-party request is an optional Google Maps embed for an address a staff member types.",
     "Designed the summative usability evaluation and instrumented it into the application itself — guided tasks per role, a pseudonymous local event log, an end-of-session questionnaire. Dogfooding on development traffic caught three bugs in the measurement instruments themselves. Sessions with users are pending deployment for daily use. Project communication, interviews and the administration-team meeting all ran in German."
    ],
    "arcNote": "The full chain in one project: research inside the process, evidence-graded problems, numbered requirements, a working application, and an instrumented evaluation."
   },
   {
    "company": "Bauhaus-Universität Weimar",
    "role": "UX Engineer / Researcher — Master's Thesis",
    "date": "10/2025 – 05/2026",
    "impactMetrics": [
     "N=30 within-subjects, 3×2×6, Latin-square",
     "60% preferred the gaze hybrid; mouse SUS 85.2",
     "Self-built TypeScript + Python gaze pipeline"
    ],
    "tasks": [
     "Built the entire experimental platform independently — a TypeScript frontend with a Python backend on the Pupil Labs Neon eye tracker's real-time API — implementing MAGIC Pointing, a gaze-augmented Ninja Cursors variant, stimulus presentation and trial-level logging.",
     "Ran a two-stage study: an exploratory pre-study (n=20 interviews, thematic analysis), then a controlled within-subjects experiment in a 3×2×6 design (n=30, Latin-square counterbalanced), comparing both gaze-assisted techniques against a mouse baseline on a physical dual-display workstation.",
     "Analysed movement time, repeat rate and SUS in R (RM-ANOVA, Friedman). 60% of participants preferred the gaze-supported Ninja Cursors variant although the mouse scored highest on SUS (85.2) — predictability and user trust beat raw speed.",
     "Concluded with a conditional design recommendation: gaze assistance should trigger only for large cross-screen relocations, not for every pointing movement."
    ],
    "arcNote": "Research rigour plus the engineering to run it: I designed the experiment and built the platform it needed."
   },
   {
    "company": "deskbird × Bauhaus-Universität Weimar",
    "role": "UX Researcher — University–Industry Research Project",
    "date": "10/2023 – 03/2024",
    "impactMetrics": [
     "My concept won the client vote",
     "3 concepts → 1, evidence-decided",
     "n=57 survey · n=6 contextual inquiry"
    ],
    "tasks": [
     "Ran end-to-end user research in a six-person team for a B2B SaaS product in the hybrid-work sector: online survey (n=57), six 90-minute remote contextual inquiries, and stakeholder interviews.",
     "Synthesised the findings into three competing concepts; the deskbird team voted and chose mine, delivered as a high-fidelity prototype with implementation recommendations for their upcoming sprints."
    ],
    "arcNote": "Research turned into a product direction the client chose — in a team, with stakeholders."
   },
   {
    "company": "Bauhaus-Universität Weimar",
    "role": "Web Designer & Content Manager — Working Student",
    "date": "04/2023 – 09/2023",
    "impactMetrics": [
     "Accessibility-validated components",
     "Corporate design compliance, TYPO3"
    ],
    "tasks": [
     "Developed responsive frontend components (HTML/CSS) and maintained dynamic content on the university's TYPO3 pages.",
     "Checked components against the corporate design system and web accessibility standards."
    ],
    "arcNote": "Accessibility and design-system compliance checked on real components, not in theory."
   },
   {
    "company": "TDSoftware",
    "role": "QA Engineer — Working Student",
    "date": "04/2022 – 06/2022",
    "impactMetrics": [
     "Cross-functional defect triage pre-release",
     "Heuristic evaluation + REST validation"
    ],
    "tasks": [
     "Acceptance testing and heuristic evaluations with the frontend development team, prioritising and resolving bugs prior to release.",
     "Validated REST endpoints and backend interfaces with Postman."
    ],
    "arcNote": "Validation before release: acceptance tests and heuristic evaluation alongside the frontend team."
   },
   {
    "company": "Part Software Group",
    "role": "Usability & QA Engineer",
    "date": "07/2020 – 07/2021",
    "impactMetrics": [
     "Co-established the company's first manual-testing group",
     "Trained 4 QA members",
     "Heuristic evaluation across 5+ products"
    ],
    "tasks": [
     "Helped set up the first structured pre-release testing group at the 500+ employee software group, trained its 4 QA members, and introduced TestLink for test-case management.",
     "Ran acceptance testing and structured heuristic evaluations across 5+ web and mobile products — checking UI against standards and validating APIs with Postman, catching usability problems before release rather than after."
    ],
    "arcNote": "Where usability and QA met: structured testing that caught usability problems before release."
   },
   {
    "company": "Mega-Tech",
    "role": "UI Developer / R&D Developer (started as Intern)",
    "date": "09/2015 – 07/2020",
    "impactMetrics": [
     "10+ WordPress & WooCommerce sites shipped",
     "SEO & performance optimisation across client sites",
     "Cross-browser & cross-device QA"
    ],
    "tasks": [
     "Delivered 10+ WordPress and WooCommerce websites (corporate, e-commerce, portfolio), including cross-browser and cross-device optimisation.",
     "SEO and performance optimisation was a standing part of the delivery brief: getting client sites onto page 1 of Google for their target keywords. The agency's own site ranked there.",
     "Moved from WordPress UI development into R&D work — nopCommerce e-commerce builds and Unity projects, clarifying requirements directly with clients."
    ],
    "arcNote": "Five years shipping production frontends — the feasibility instinct behind every recommendation I make now."
   },
   {
    "company": "Black Citrus",
    "role": "QA Engineer — Internship via Mega-Tech (remote)",
    "date": "06/2015 – 09/2015",
    "impactMetrics": [
     "First industry role, straight after the B.E.",
     "Remote QA for an Australian team"
    ],
    "tasks": [
     "Manually tested the web application projects of Black Citrus, an Australian company, working remotely — placed there as an intern through Mega-Tech directly after finishing the bachelor thesis."
    ],
    "arcNote": "First industry role: learning how software fails by testing it."
   }
  ],
  "education": [
   {
    "school": "Bauhaus-Universität Weimar",
    "degree": "M.Sc. Human-Computer Interaction",
    "year": "10/2021 – 05/2026",
    "grade": "Final grade: 1.7 · Thesis: 1.5 · 120 ECTS",
    "note": "Continuously enrolled at Bauhaus-Universität Weimar since 10/2021; the first semester ran in the M.Sc. Computer Science for Digital Media before I transferred to Human-Computer Interaction, and its coursework counts toward the HCI degree.",
    "awards": [
     "Thesis: Gaze-Assisted Input in Dual-Display Environments — A Comparative Evaluation of MAGIC Pointing, Ninja Cursors, and a Mouse Baseline"
    ]
   },
   {
    "school": "Khayyam Higher Education Centre",
    "degree": "B.E. Software Engineering",
    "year": "10/2010 – 06/2015"
   }
  ],
  "skills": {
   "Core Expertise": [
    "UX Research",
    "Usability Engineering",
    "Requirements Engineering",
    "Interaction Design",
    "Usability Evaluation",
    "Mixed-Methods Research",
    "Information Architecture",
    "Web Accessibility (WCAG 2.1 AA)"
   ],
   "Research & Evaluation": [
    "Stakeholder & Expert Interviews",
    "Contextual Inquiry",
    "Survey Design",
    "Controlled Experiments",
    "Eye-Tracking (Pupil Labs Neon)",
    "Thematic Analysis",
    "Affinity Diagramming",
    "Persona Development",
    "Process Mapping (UML Swimlanes, 5W1H)",
    "Heuristic Evaluation",
    "Formative & Summative Usability Testing",
    "Prototype & Hardware/Software Evaluation",
    "Usability Metrics (SUS, task success, error rate, time on task)",
    "Repeated-Measures ANOVA in R",
    "B2B User Research"
   ],
   "Technical Implementation": [
    "React",
    "TypeScript",
    "JavaScript (ES6+)",
    "HTML",
    "CSS",
    "Tailwind CSS",
    "Vite",
    "Design Systems",
    "Figma",
    "Node.js (Fastify)",
    "REST APIs",
    "SQLite",
    "Python",
    "Unit & Integration Testing (Vitest)",
    "Requirements Traceability (FR/NFR)",
    "Authentication & Security (argon2id, CSRF)",
    "Git & GitHub",
    "Vercel",
    "AI-assisted development (Claude Code, GitHub Copilot)"
   ],
   "Quality Assurance": [
    "Acceptance Testing",
    "Test-Case Management (TestLink)",
    "REST API Validation (Postman)",
    "Cross-Browser & Cross-Device QA"
   ],
   "Additional Technical Experience": [
    "WordPress",
    "WooCommerce",
    "nopCommerce",
    "E-Commerce",
    "TYPO3",
    "Unity",
    "Physical Prototyping (inflatables, Arduino, pneumatic actuators, capacitive sensors)",
    "Real-Time Device APIs (Pupil Labs Neon)",
    "OpenAI API",
    "SEO & Performance Optimisation"
   ]
  },
  "languages": [
   {
    "name": "English",
    "level": "C1 (Fluent)",
    "language": "English"
   },
   {
    "name": "German",
    "level": "C1 (DSH-2)",
    "language": "German"
   },
   {
    "name": "Persian",
    "level": "Native",
    "language": "Persian"
   }
  ],
  "certifications": [
   {
    "title": "M.Sc. Human-Computer Interaction",
    "provider": "Bauhaus-Universität Weimar, Faculty of Media",
    "year": "2026",
    "type": "degree",
    "topic": "academic",
    "featured": false,
    "skills": [
     "HCI Research",
     "Physiological Computing",
     "Usability Engineering",
     "Design Theory"
    ],
    "verifyUrl": "",
    "detail": "Graduated 12 May 2026. Final grade 1.7, 120 ECTS, Faculty of Media. Thesis: Gaze-Assisted Input in Dual-Display Environments — A Comparative Evaluation of MAGIC Pointing, Ninja Cursors, and a Mouse Baseline (1.5, 24 ECTS), defence 1.5 (6 ECTS). Strongest module: HCI Specialisation — Physiological Computing: Determination and Manipulation of User Characteristics (1.0). Two graded research projects: Research Project I — Inflatables for Data Physicalization and Tangible Interaction (1.6, 18 ECTS), and Research Project II — User-Centered Design in Practice: Designing a Digital Product to Encourage Social Interactions in Hybrid Workplaces (1.3, 12 ECTS)."
   },
   {
    "title": "DSH-2 (German Language Proficiency for University Admission)",
    "provider": "Sprachenzentrum, Bauhaus-Universität Weimar",
    "year": "2026",
    "date": "2026-02-16",
    "type": "language",
    "topic": "academic",
    "featured": true,
    "skills": [
     "German C1"
    ],
    "verifyUrl": "",
    "detail": "Examined 16 February 2026, while writing the Master's thesis. DSH-2 certifies differentiated written and spoken ability and grants unrestricted admission to every degree programme at any German university. Reached from A2 through one institution's own course sequence at the Sprachenzentrum: A2 (2021/22), B1 (2024), B2 intensive (2025), then DSH preparation."
   },
   {
    "title": "German B2 — Intensive Course",
    "provider": "Sprachenzentrum, Bauhaus-Universität Weimar",
    "year": "2025",
    "date": "2025-02-12",
    "type": "language",
    "topic": "academic",
    "featured": false,
    "skills": [
     "German B2"
    ],
    "verifyUrl": "",
    "detail": "Intensive course, 1 October 2024 to 12 February 2025, closing with an examination equivalent in form and standard to the Goethe-Zertifikat B2. Passing it is the prerequisite for the Sprachenzentrum's DSH preparation course."
   },
   {
    "title": "German B1 — Grundstufe",
    "provider": "Sprachenzentrum, Bauhaus-Universität Weimar",
    "year": "2024",
    "date": "2024-07-10",
    "type": "language",
    "topic": "academic",
    "featured": false,
    "skills": [
     "German B1"
    ],
    "verifyUrl": "",
    "detail": "Around 300 contact hours, 2 April to 10 July 2024, closing with an examination equivalent to the Zertifikat Deutsch als Fremdsprache at CEFR level B1. Result: gut."
   },
   {
    "title": "Figma 101 Workshop",
    "provider": "Human-Computer Interaction Group, Bauhaus-Universität Weimar",
    "year": "2025",
    "type": "workshop",
    "topic": "design",
    "featured": true,
    "skills": [
     "Figma",
     "Auto Layout",
     "Design Systems",
     "Prototyping"
    ],
    "verifyUrl": "",
    "detail": "Auto Layout, wireframe libraries, design systems and prototyping — three assignments, concluding in a mini portfolio."
   },
   {
    "title": "Designing for Human: Design Thinking & Behaviour Science to Solve Any Problem",
    "provider": "Bauhaus-Universität Weimar",
    "year": "2024",
    "type": "course",
    "topic": "strategy",
    "featured": false,
    "skills": [
     "Design Thinking",
     "Behavioural Science"
    ],
    "verifyUrl": "",
    "detail": "Graded university module, summer semester 2024 (1.1, 3 ECTS): design thinking combined with behavioural science as a problem-solving method."
   },
   {
    "title": "Designing Accessible Components in Figma",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-09-20",
    "duration": "1 h 11 min",
    "type": "course",
    "topic": "accessibility",
    "featured": false,
    "skills": [
     "Computer Accessibility",
     "Figma"
    ],
    "verifyUrl": "",
    "detail": "Building components that stay usable with assistive technology — contrast, focus order, and annotation conventions inside Figma."
   },
   {
    "title": "20 Rules for Visual Communication",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-09-03",
    "duration": "2 h 2 min",
    "type": "course",
    "topic": "design",
    "skills": [
     "Visual Communication"
    ],
    "verifyUrl": "",
    "detail": "Composition, hierarchy, type and colour rules for making a message legible at a glance."
   },
   {
    "title": "Design Thinking: Understanding the Process",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-09-03",
    "type": "course",
    "topic": "strategy",
    "skills": [
     "Design Thinking",
     "Product Development"
    ],
    "verifyUrl": "",
    "detail": "The full double-diamond loop — empathise, define, ideate, prototype, test — and where each phase pays off in product work."
   },
   {
    "title": "Figma Essential Training: The Basics",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-09-03",
    "duration": "1 h 37 min",
    "type": "course",
    "topic": "design",
    "skills": [
     "Figma"
    ],
    "verifyUrl": "",
    "detail": "Frames, components, styles and shared libraries — the working vocabulary behind every file I hand to developers."
   },
   {
    "title": "UX Deep Dive: Usability Testing",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-06-02",
    "duration": "26 min",
    "type": "course",
    "topic": "research",
    "featured": false,
    "skills": [
     "Usability Testing"
    ],
    "verifyUrl": "",
    "detail": "Planning a test, writing non-leading tasks, moderating, and turning observations into prioritised findings."
   },
   {
    "title": "UX Design 7: Implementation Planning",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-06-02",
    "duration": "18 min",
    "type": "course",
    "topic": "strategy",
    "skills": [
     "User Experience Design"
    ],
    "verifyUrl": "",
    "detail": "Handing a design over: scoping, sequencing and documenting what engineering actually needs to build it."
   },
   {
    "title": "UX for Web Forms",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-05-26",
    "duration": "2 h 18 min",
    "type": "course",
    "topic": "engineering",
    "skills": [
     "Forms Development",
     "User Experience"
    ],
    "verifyUrl": "",
    "detail": "Field design, inline validation, error recovery and accessible labelling for the forms that carry most conversions."
   },
   {
    "title": "UX Design 1: Overview",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-05-25",
    "duration": "13 min",
    "type": "course",
    "topic": "strategy",
    "skills": [
     "User Experience Design"
    ],
    "verifyUrl": "",
    "detail": "How the phases of a UX process fit together, and which deliverable belongs to which phase."
   },
   {
    "title": "UX Design 2: Analyzing User Data",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-05-25",
    "duration": "30 min",
    "type": "course",
    "topic": "research",
    "skills": [
     "User Analysis"
    ],
    "verifyUrl": "",
    "detail": "Turning raw research data into patterns — affinity mapping, segmentation, and reading quantitative signals honestly."
   },
   {
    "title": "XML Essential Training",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-05-21",
    "duration": "3 h 52 min",
    "type": "course",
    "topic": "engineering",
    "skills": [
     "XML",
     "Schemas",
     "XSLT"
    ],
    "verifyUrl": "",
    "detail": "Document structure, DTDs and schemas, namespaces, XPath and XSLT transformations."
   },
   {
    "title": "Using AI in the UX Design Process",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-05-20",
    "duration": "1 h 7 min",
    "type": "course",
    "topic": "ai",
    "featured": false,
    "skills": [
     "Artificial Intelligence for Design",
     "User Experience Design"
    ],
    "verifyUrl": "",
    "detail": "Where generative AI genuinely speeds up research synthesis, ideation and content drafting — and where it quietly misleads."
   },
   {
    "title": "A Design Thinking Approach to Putting the Customer First",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-04-28",
    "duration": "27 min",
    "type": "course",
    "topic": "strategy",
    "skills": [
     "Customer-Focused Design"
    ],
    "verifyUrl": "",
    "detail": "Keeping the customer's problem — not the team's assumptions — at the centre of a design decision."
   },
   {
    "title": "UX Design 3: Creating Personas",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-04-17",
    "duration": "25 min",
    "type": "course",
    "topic": "research",
    "skills": [
     "User Personas"
    ],
    "verifyUrl": "",
    "detail": "Building personas from evidence rather than invention, and keeping them usable once the project moves on."
   },
   {
    "title": "UX Design 5: Creating Scenarios and Storyboards",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-04-17",
    "duration": "20 min",
    "type": "course",
    "topic": "research",
    "skills": [
     "User Experience Design",
     "Storyboarding"
    ],
    "verifyUrl": "",
    "detail": "Narrating a user's context as a scenario, then drawing it out as a storyboard the whole team can argue with."
   },
   {
    "title": "Agile User Experience Design and Research",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-04-12",
    "duration": "59 min",
    "type": "course",
    "topic": "strategy",
    "featured": false,
    "skills": [
     "Agile Methodologies",
     "UX Research"
    ],
    "verifyUrl": "",
    "detail": "Fitting research and design into sprint cadence — continuous discovery, lean deliverables, and testing one sprint ahead."
   },
   {
    "title": "Using Style Guides to Bridge Design and Development",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-04-07",
    "duration": "50 min",
    "type": "course",
    "topic": "design",
    "skills": [
     "User Interface Design",
     "Style Guides",
     "User Experience Design"
    ],
    "verifyUrl": "",
    "detail": "Style guides and design systems as the shared contract between a design file and the components that ship."
   },
   {
    "title": "Student Volunteer — Mensch und Computer 2022",
    "provider": "Gesellschaft für Informatik (GI e.V.) · ACM In-Cooperation",
    "year": "2022",
    "type": "recognition",
    "topic": "academic",
    "featured": false,
    "skills": [
     "Session Chairing",
     "Conference Operations"
    ],
    "verifyUrl": "",
    "detail": "Session and workshop support at Europe's largest HCI conference series (~600 participants), hosted by TU Darmstadt."
   },
   {
    "title": "Student Volunteer — Joint Conference on Serious Games 2022",
    "provider": "JCSG 2022, Bauhaus-Universität Weimar",
    "year": "2022",
    "date": "2022-09-23",
    "type": "recognition",
    "topic": "academic",
    "featured": false,
    "skills": [
     "Conference Operations",
     "Speaker Support"
    ],
    "verifyUrl": "",
    "detail": "Venue setup, guest welcome and speaker support across the two conference days, 22–23 September 2022 in Weimar."
   },
   {
    "title": "Frontend Development",
    "provider": "Part College",
    "year": "2021",
    "type": "course",
    "topic": "engineering",
    "featured": true,
    "skills": [
     "Frontend Development"
    ],
    "verifyUrl": "",
    "detail": "Frontend development course offered through Part College, completed with certificate while working at Part Software Group."
   },
   {
    "title": "Python Programming",
    "provider": "Technical & Vocational Training Organization",
    "year": "2019",
    "type": "certification",
    "topic": "engineering",
    "featured": true,
    "skills": [
     "Python"
    ],
    "verifyUrl": "",
    "detail": "Certified training in Python programming."
   }
  ],
  "contact": {
   "location": "Weimar, Germany",
   "email": "sanaz.yazdanjoo@gmail.com",
   "linkedin": "https://www.linkedin.com/in/sanaz-yazdanjoo/",
   "github": "https://github.com/SanazYazdanjoo",
   "website": "https://yazdanjoo.de",
   "availability": "I currently live in Weimar but open to relocate.",
   "timezone": "CET (UTC+1)"
  }
 },
 "projects": [
  {
   "title": "Gaze-Assisted Input in Dual-Display Environments",
   "page": "/projects/gaze-assisted-input",
   "status": "published",
   "subtitle": "A Comparative Evaluation of MAGIC Pointing, Ninja Cursors, and a Mouse Baseline",
   "tagline": "Can gaze make cross-screen pointing faster — without sacrificing user trust?",
   "role": "UX Engineer (Master's Thesis)",
   "year": "2025–2026",
   "timeline": "10/2025 – 04/2026 · defence 05/2026",
   "context": "M.Sc. thesis",
   "tags": [
    "TypeScript",
    "React",
    "Python",
    "Eye-Tracking",
    "Real-Time API Integration",
    "Mixed-Methods Research",
    "Experimental Design",
    "Semi-Structured Interviews",
    "Thematic Analysis",
    "Quantitative UX Research",
    "Statistical Analysis (ANOVA)",
    "SUS Evaluation",
    "Figma"
   ],
   "techStack": [
    "TypeScript",
    "Pupil Labs Neon",
    "Real-Time API",
    "AprilTag Marker Mapping",
    "Python",
    "React"
   ],
   "methods": [
    "Custom TypeScript Architecture",
    "Within-Subjects Experiment (3×2×6)",
    "Real-Time Data Logging",
    "Repeated-Measures ANOVA",
    "SUS Evaluation",
    "Reflexive Thematic Analysis"
   ],
   "metrics": [
    {
     "value": "2",
     "label": "gaze techniques engineered from scratch in TypeScript"
    },
    {
     "value": "N=30",
     "label": "within-subjects experiment"
    },
    {
     "value": "η²ₚ=.690",
     "label": "technique × distance interaction"
    },
    {
     "value": "60%",
     "label": "preferred the gaze-hybrid (Ninja)"
    }
   ],
   "about": "A Master's thesis asking whether eye gaze can make pointing across two screens faster without costing users their trust in the cursor. I built the entire experiment software in TypeScript, connected it to a head-mounted eye tracker, and compared two gaze-assisted techniques — MAGIC Pointing and Ninja Cursors — against a plain mouse with 30 participants.",
   "challenge": "Multi-display workstations are everywhere, yet the mouse alone makes cross-display pointing costly: long pointer transits, cursor re-acquisition after bezel crossings, and attentional switches between screens. Prior work proposed gaze-assisted hybrids, but few controlled studies had compared MAGIC Pointing and Ninja Cursors against a mouse baseline in a dual-display setting — a comparison explicitly called for as future work by Räihä & Špakov (2009).",
   "solution": "I engineered the complete technical architecture and evaluation framework. This included building a dual-display eye-tracking apparatus (Pupil Labs Neon, real-time streaming API, AprilTag surface mapping) and developing performant TypeScript implementations of MAGIC Pointing (gaze-triggered cursor warp with manual fine-tuning) and a gaze-augmented Ninja Cursors variant (one persistent cursor per screen, activated by gaze). Both were then evaluated against a standard mouse baseline in reciprocal pointing tasks.",
   "methodology": "A two-phase mixed-methods design. Phase I: a formative pre-study (n=20) using semi-structured interviews and a Figma-based workspace visualisation task, analysed with reflexive thematic analysis, which grounded the lab configuration in real dual-display practice. Phase II: a controlled within-subjects experiment (N=30) with a 3×2×6 factorial design — input method × target size × distance (875–3226 px) — measuring movement time, repeat rate, and SUS, analysed with repeated-measures ANOVA (Greenhouse–Geisser corrected, Tukey post-hoc).",
   "results": "A significant technique × distance interaction (η²ₚ = .690) revealed a crossover: the mouse was fastest for short distances, but Ninja Cursors significantly outperformed it at the two intermediate cross-screen distances (1684 and 2243 px) and converged at the longest (3226 px). MAGIC was consistently slowest — its warp coupled gaze noise directly to landing accuracy, producing the highest repeat rate on small targets (4.69%), while Ninja's small-target repeat rate matched the mouse baseline (3.30%). SUS ranked Mouse (85.2) > Ninja (72.6) > MAGIC (55.9), with MAGIC alone falling below the 68-point acceptability threshold — yet 60% of participants named Ninja their most preferred method, and 63% named MAGIC their least preferred.",
   "limitations": [
    "Short-term exposure. The study captured first impressions, not long-term adaptation — and the mouse's familiarity is a confound the design could not remove. Whether the coordination overhead 18 of 30 participants described falls away as the gaze techniques are internalised needs a longitudinal design.",
    "Hardware-related discomfort. Fourteen of thirty participants reported frame pressure, eye fatigue, or degraded tracking as prescription-glasses wearers — all of which likely reflect the apparatus rather than gaze-based interaction as a paradigm.",
    "Laboratory task versus real work. Reciprocal pointing isolates target acquisition; it does not carry window management, context switching, variable target densities, or the periods of cursor disengagement in which the re-acquisition benefit of gaze would show most clearly.",
    "Missing endpoint data. Miss/timeout outcomes and trial-level endpoint coordinates were not retained in the cleaned export, so ISO-style effective measures and throughput could not be computed — and repeat rate could not be decomposed into its breakdown types.",
    "Sample characteristics. Participants were largely researchers and professionals in technology-related roles, which limits how far the results generalise to other populations.",
    "Distance and screen transition are confounded. The six distance levels do not pair within-screen and cross-screen movements at matched amplitudes, so the effect of crossing the bezel cannot be separated from the effect of distance — no claim about the boundary's own contribution is made from these data. The asymmetry was deliberate: the geometry copies a real dual-display workstation rather than an artificially symmetric one. A matched-pairs design would settle it."
   ],
   "implications": "Gaze assistance should be a context-aware accelerator, not an always-on replacement. Three design directions follow from the data: adaptive activation using the screen boundary itself as the trigger, semantic snapping toward UI elements to fix MAGIC's landing penalty, and stronger visual differentiation of the active cursor in multi-cursor designs. For UI engineers, predictability and system trust — not raw speed alone — determine whether users adopt a novel interaction pattern.",
   "outcome": {
    "body": "This is a Master's thesis, not a commercially deployed system — adoption in the product sense doesn't apply the way it would for a shipped feature. The three design directions named in the Implications section are the concrete output the completed work delivered.",
    "adoption": "academic"
   },
   "process": [
    {
     "phase": "discover",
     "type": "Semi-structured Interviews",
     "title": "Characterising Real Multi-Display Work",
     "annotation": "20 participants (researchers and tech/design professionals) recreated their workstation on a shared Figma canvas, then discussed screen roles, input preferences, and cross-display pain points in ~30-minute sessions. Analysed with reflexive thematic analysis.",
     "insight": "Cursor loss was a real, named pain point: participants described 'shaking' the mouse to find the pointer, and 14 of 20 reported neck strain or eye fatigue. This directly motivated the focus on cross-display target acquisition."
    },
    {
     "phase": "discover",
     "type": "Workspace Visualisation",
     "title": "Grounding the Lab Setup in Reality",
     "annotation": "Participants' recreated configurations revealed dominant patterns: side-by-side dual displays, laptop + external monitor (12/20), and near-universal mouse use (17/20) even on laptops.",
     "insight": "The lab apparatus copied what people actually use — side-by-side dual displays, mouse as the manual device, and a height-adjustable desk to address the ergonomic strain participants reported."
    },
    {
     "phase": "define",
     "type": "Experimental Design",
     "title": "A 3×2×6 Within-Subjects Protocol",
     "annotation": "Three input methods (Mouse, MAGIC Pointing, gaze-augmented Ninja Cursors) × two target sizes × six distances (875–3226 px); input-method and target-size order counterbalanced with a balanced Latin square. Measures: movement time, repeat rate, and SUS per method block.",
     "insight": "Treating distance as a categorical factor was deliberate — the six levels mix within-screen and cross-screen movements, which is exactly where the techniques were expected to diverge."
    },
    {
     "phase": "design",
     "type": "Frontend Engineering",
     "title": "TypeScript Architecture & Real-Time Gaze Pipeline",
     "annotation": "Engineered the complete experiment software from scratch in TypeScript. Interfaced with the Pupil Labs Neon head-mounted tracker via its real-time streaming API — a Python backend service relays the tracker's stream to the browser frontend — using AprilTag-based surface mapping to translate gaze onto each display. Implemented MAGIC (gaze-triggered warp, 20 px landing offset) and a gaze-augmented Ninja variant (one cursor per screen, gaze-based switching, 150 ms guard).",
     "insight": "The two techniques distribute risk differently on a system level: MAGIC couples gaze precision to every landing, while Ninja uses gaze only for the coarse display switch — an architectural difference that later explained the entire results pattern."
    },
    {
     "phase": "deliver",
     "type": "Quantitative Analysis",
     "title": "RM-ANOVA: A Distance-Dependent Crossover",
     "annotation": "Repeated-measures ANOVA on log-transformed movement time (n=24 after data-quality exclusions), Greenhouse–Geisser corrected, Tukey post-hoc, run in R. Significant technique × distance interaction (η²ₚ = .690, p < .001).",
     "insight": "Mouse won at short distances — but Ninja significantly beat it at the two intermediate cross-screen distances (1684 and 2243 px) and converged at the longest. Gaze assistance pays off precisely where the bezel crossing is the dominant cost."
    },
    {
     "phase": "deliver",
     "type": "SUS + Thematic Analysis",
     "title": "Trust Beats Speed",
     "annotation": "SUS after each block (N=30): Mouse 85.2, Ninja 72.6, MAGIC 55.9 (Friedman p < .001) — MAGIC the only technique below the 68-point acceptability threshold. Reflexive thematic analysis of open feedback surfaced seven primary themes, from the 'transport advantage' (23/30) to the 'landing penalty' (22/30).",
     "insight": "60% preferred Ninja despite the mouse's higher SUS — participants framed it as 'best of both worlds.' Predictability and trust, not raw speed, determined acceptance."
    }
   ],
   "verbatims": [
    {
     "quote": "Sometimes when I'm very much focused on the task, I just don't get [where the cursor] is, and then I have to shake it.",
     "attribution": "P03 (engineer), Phase I pre-study (n=20) — on losing the cursor in everyday multi-display work"
    },
    {
     "quote": "It's a mix of Mouse and MAGIC — you get the best out of both. It makes switching monitors faster while putting less strain on the eyes.",
     "attribution": "P21 on Ninja Cursors, Phase II study (N=30) — 60% preferred it despite the mouse scoring higher on SUS"
    }
   ],
   "cardOutcome": "Gaze wins over long cross-screen distances and loses over short ones; trust in the cursor decided preference."
  },
  {
   "title": "Digitalising IBS Travel Reimbursements",
   "page": "/projects/digitalising-ibs-travel-reimbursements",
   "status": "in-progress",
   "subtitle": "From paper forms and scattered Excel files to one traceable reimbursement workflow",
   "tagline": "A reimbursement process researched from the inside, translated into requirements, and rebuilt as a working application.",
   "role": "Solo — UX Research, Usability Engineering, UI Design & Frontend Development",
   "year": "2026",
   "timeline": "2026 · ongoing",
   "context": "In-house project",
   "tags": [
    "UX Research",
    "Stakeholder Interviews",
    "Survey Design",
    "Thematic Analysis",
    "Process Mapping (UML)",
    "Requirements Engineering",
    "Requirements Traceability",
    "Information Architecture",
    "State Machine Modelling",
    "Wireframing",
    "Design Systems",
    "Prototyping",
    "Usability Evaluation (instrumented)",
    "React",
    "TypeScript",
    "Node.js / Fastify",
    "Automated Testing (Vitest)",
    "Privacy by Design",
    "GDPR / DSGVO"
   ],
   "evidenceChain": [
    {
     "stage": "Research",
     "note": "More than a year administering the process as project assistant, two expert interviews, a working meeting with the administration team, and an open participant survey."
    },
    {
     "stage": "Synthesis",
     "note": "25 documented problems, each carrying an evidence grade: confirmed, indicative, hypothesis, untested."
    },
    {
     "stage": "Requirements",
     "note": "Numbered FR/NFR requirements traced to their source problems; a CI test fails the build on a citation without a source."
    },
    {
     "stage": "Design",
     "note": "A role-based information architecture, an explicit claim state machine, wireframes before high-fidelity screens, and a design system whose role palette is the research diagram’s lane colours."
    },
    {
     "stage": "Implementation",
     "note": "One React/TypeScript application with a Fastify backend: five role views, and an amount that is recomputed on every screen with its calculation trace visible."
    },
    {
     "stage": "Quality",
     "note": "1,734 automated tests, session authentication, CSRF and rate limits, local-only participant data, and bundle scans for stray hostnames and real names."
    },
    {
     "stage": "Validation",
     "pending": true,
     "note": "A summative usability evaluation is instrumented into the app — guided tasks, a pseudonymous event log, a questionnaire. It runs once the app is deployed for daily use; measured outcomes are not yet available."
    }
   ],
   "techStack": [
    "React",
    "TypeScript",
    "Vite",
    "Tailwind CSS",
    "Vitest",
    "Node.js / Fastify",
    "SQLite",
    "ExcelJS",
    "Nextcloud WebDAV",
    "Figma Make",
    "Claude Code (AI-assisted development)"
   ],
   "methods": [
    "Insider process observation (>1 year)",
    "Expert interviews (n=2) + administration working meeting",
    "Ongoing anonymous participant survey (n=6)",
    "Document & artefact analysis",
    "Thematic analysis / evidence grading",
    "Stakeholder & AS-IS process mapping",
    "Requirements traceability",
    "Built-in usability evaluation instrumentation"
   ],
   "metrics": [
    {
     "value": "13",
     "label": "steps in the AS-IS reimbursement process"
    },
    {
     "value": "4",
     "label": "return loops in the mapped process"
    },
    {
     "value": "9",
     "label": "actors across the end-to-end service"
    },
    {
     "value": "43+",
     "label": "days in one traced claim · minimum for that case, not an average"
    }
   ],
   "about": "I spent more than a year administering this reimbursement process as a project assistant — collecting paper receipts, consolidating several Excel files, checking attendance, and calculating reimbursements. That gave me deep process knowledge, but I treated it as a set of assumptions to test rather than as research evidence on its own. I combined insider observation with expert interviews, an administration working meeting, an ongoing participant survey, and artefact analysis, then translated the verified problems into requirements and a working application. The demo is deployed for team feedback; formal usability evaluation is still pending.",
   "challenge": "Travel reimbursement depended on paper attendance records, several Excel files, manual calculations, and hand-offs across nine actors. The same information was copied repeatedly, creating delays and opportunities for mistakes. Participants had no reliable confirmation after submitting documents, no visible calculation, and no claim status. In the ongoing survey, 4/6 respondents did not know how their amount was calculated, 5/6 had no reliable way to know whether their documents had arrived, and 4/6 named processing time as their main difficulty. One traced claim remained unpaid after 43+ days. The failure was structural, not clerical.",
   "solution": "I replaced the fragmented workflow with one role-based application for attendance, supporting-document submission, reimbursement calculation, approval, and claim tracking. Participants can upload documents and see the state of their claim; staff work from the same attendance and reimbursement data instead of copying information between spreadsheets. Calculations are rebuilt from shared rules and the formula trace remains visible to reviewers. The participant upload flow is designed for phone use, while responsive support across the full authenticated application is still in progress. The current system covers the workflow up to payment; the final accounting payment step remains outside the application.",
   "design": "I carried the research model into the interface instead of inventing a separate visual language. The role colours from the AS-IS swimlane map became the application role palette, supported by a compact type scale, status chips, note states, buttons, and form states. This keeps the same actor cues visible from research artefact to working screen.",
   "wireframe": "I used low-fidelity wireframes to resolve information hierarchy and workflow logic against the numbered requirements before applying visual styling. The high-fidelity version kept the same structure and added the final attendance vocabulary, morning/afternoon states, role cues, exception highlighting, and completion feedback. The comparison below shows the same attendance-month screen from sketch to wireframe to deployed view.",
   "methodology": "The research-to-build chain is explicit. I treated insider observations as hypotheses, checked them through interviews, the administration working session, the ongoing participant survey, and artefact analysis, then clustered the evidence into a 25-problem register with evidence grades. Those problems became numbered requirements, information architecture, state rules, and wireframes. One example closes the loop: 4/6 respondents did not understand the reimbursement calculation → transparent calculation became a requirement → one shared calculation module now produces a visible formula trace → automated tests protect the requirement links. The same traceability also exposes gaps: confirmation after submission is only partially implemented, so the page does not present it as solved.",
   "results": "The current evidence describes the existing process and the mechanisms implemented in the replacement. The working demo is deployed for team feedback, and internal testing has already exposed three instrumentation bugs. Formal usability sessions have not run, so I do not claim reduced processing time, fewer errors, better usability, or adoption yet. Those outcomes will be reported only after the evaluation is completed.",
   "limitations": [
    "The participant survey is currently n=6, self-selected, and so far limited to the blended/online cohort; the in-person cohort and travel-pass holders are not yet represented.",
    "Two expert interviews represent project management and accounting. Lecturers were not interviewed; their part of the workflow is mapped from artefacts and my own process observation.",
    "The 43+ day figure is one traced claim. It was still unpaid when observation stopped, so it is a minimum for that case — not an average or a distribution.",
    "Formal usability evaluation of the new system has not run. The page therefore reports implemented mechanisms and baseline evidence, not measured improvement over the paper process."
   ],
   "process": [
    {
     "phase": "discover",
     "type": "Research",
     "title": "Turn insider knowledge into testable questions",
     "annotation": "I combined more than a year of process observation with two expert interviews, one administration working meeting, an ongoing anonymous participant survey (n=6), and document analysis.",
     "insight": "Because I already knew the workflow, the research goal was to challenge my assumptions, not to confirm them."
    },
    {
     "phase": "define",
     "type": "Evidence",
     "title": "Map the failure and grade the evidence",
     "annotation": "The AS-IS map exposed 13 steps, four return loops, and nine actors. Thematic clustering produced a register of 25 documented problems, each linked to its evidence source.",
     "insight": "Survey findings also changed the roadmap: I had treated phone-width support as secondary, but participants reported that phone submission mattered. Responsive participant use moved up the priority list; the full signed-in phone layout is still in progress."
    },
    {
     "phase": "design",
     "type": "Requirements & design",
     "title": "Translate findings into explicit product rules",
     "annotation": "The problem register became numbered requirements, a role-based information architecture, an explicit claim state model, and low- and high-fidelity wireframes.",
     "insight": "The service map covers nine actors. Seven composite, evidence-backed role profiles document the perspectives used during design; five roles directly work through dedicated application views."
    },
    {
     "phase": "deliver",
     "type": "Implementation",
     "title": "Carry the same requirements into working code",
     "annotation": "I built the role-based application in React and TypeScript with shared calculation rules, an explicit claim state machine, access controls, local data adapters, and automated tests.",
     "insight": "Example: 4/6 survey respondents did not understand the reimbursement calculation. That became a requirement for transparent amounts, implemented as one shared calculation with a visible formula trace and protected by automated checks."
    },
    {
     "phase": "deliver",
     "type": "Evaluation",
     "title": "Deploy first, measure the change next",
     "annotation": "The demo is deployed for stakeholder feedback. Guided tasks, pseudonymous local event logging, and an end-of-session questionnaire are already built into the application for the formal usability evaluation.",
     "insight": "No post-launch improvement is claimed yet. The evaluation instruments exist; the user sessions have not run."
    }
   ],
   "verbatims": [
    {
     "quote": "No, I just take the amount as it comes.",
     "attribution": "Survey respondent on checking the reimbursement calculation · translated from German"
    },
    {
     "quote": "The processing time is the hardest part for me.",
     "attribution": "Survey respondent · four of six named processing time as their main difficulty · translated from German"
    },
    {
     "quote": "I don’t check it.",
     "attribution": "Survey respondent on knowing whether submitted documents arrived · translated from German"
    }
   ],
   "cardOutcome": "Research mapped 13 steps, reversed a priority, surfaced 6 missed problems, and carried the 9-actor colour model into the demo."
  },
  {
   "title": "Encouraging Social Interactions in Hybrid Work",
   "page": "/projects/deskbird-hybrid-work",
   "status": "published",
   "subtitle": "Industry UX Research Project with deskbird × Bauhaus-Universität Weimar",
   "tagline": "Reconnecting hybrid teams through evidence-based social feature design.",
   "role": "UX Researcher (team of 6)",
   "year": "2023–2024",
   "timeline": "10/2023 – 03/2024",
   "context": "Industry project · deskbird",
   "tags": [
    "User-Centered Design",
    "Mixed-Methods Research",
    "Stakeholder Interviews",
    "Contextual Inquiry",
    "Survey Design",
    "Competitive Analysis",
    "Affinity Diagramming",
    "Requirements Engineering",
    "Concept Development",
    "Interaction Design",
    "High-Fidelity Prototyping",
    "Usability Testing",
    "Figma",
    "B2B SaaS"
   ],
   "techStack": [
    "Figma",
    "FigJam",
    "Online Survey Tools"
   ],
   "methods": [
    "Heuristic Evaluation (admin & end user)",
    "Competitive & State-of-the-Art Review",
    "Stakeholder Interviews",
    "Online Survey",
    "Pilot Studies (think-aloud survey pilot, two contextual inquiry pilots)",
    "Remote Contextual Inquiry (90 min)",
    "Semi-structured Follow-up Interviews (30 min)",
    "Interpretation Sessions & Contextual Design Models",
    "Affinity Diagramming",
    "Requirements Engineering",
    "User Story Mapping & Release Planning",
    "Concept Development & Prototyping",
    "Usability Testing & Iteration"
   ],
   "metrics": [
    {
     "value": "57",
     "label": "survey respondents"
    },
    {
     "value": "6",
     "label": "contextual inquiries + follow-ups"
    },
    {
     "value": "~75%",
     "label": "say they relate more to colleagues whose personal details they know"
    },
    {
     "value": "3 → 1",
     "label": "concepts presented to deskbird; one selected by vote"
    }
   ],
   "about": "An industry UX research project with deskbird and Bauhaus-Universität Weimar on why hybrid teams lose their everyday social connection. In a team of six we ran the full user-centred design process — stakeholder interviews, a 57-person survey, and six contextual inquiries — to establish how a social feature should work before it reached the roadmap. The outcome is 'Interest-Based Communities', my concept, selected by deskbird's stakeholders and delivered as a research-backed high-fidelity prototype.",
   "challenge": "Hybrid work reduced spontaneous social interactions: employees felt less integrated and new joiners struggled to connect. deskbird — a B2B SaaS platform for desk booking and hybrid week planning — wanted evidence, not assumptions, on how a social feature should work before committing it to the product roadmap.",
   "solution": "We designed 'Interest-Based Communities': employees add interests to their profile, see colleagues' interests, and create or get invited to interest-based events. The concept connects both office-based and remote staff and was delivered as a high-fidelity prototype with development recommendations, grounded in every research finding along the way.",
   "methodology": "We followed the full UCD process in an industry setting. Two competitive reviews framed the scope: the hybrid-work engagement landscape (Microsoft Viva, Workvivo, Donut for Slack, Happeo, and ~25 others) to establish what a social feature could be, and deskbird's direct desk-booking competitors (Flexopus, Condeco, Deskly, Robin, Kadence, Yoffix, Seatti, and others) to establish what was already shipping. A heuristic evaluation of the existing deskbird app — walked through as both admin and end user, with user-flow analysis — mapped the product itself. A literature review of social features in workplace systems, working from Lyons and Lessard's distinction between key and supportive social features, gave the concept work a vocabulary. Stakeholder interviews across marketing, product management, product design, and customer support defined brand identity, consumer aspirations, and the social-feature scope. A ten-section online survey opening with a consent block (57 respondents, mainly aged 25–34, IT industry, hybrid workers recruited via convenience and snowball sampling) quantified work conditions, social interaction states, communication channels, and privacy preferences; it was piloted with the think-aloud method before launch, and its open-ended responses set the focus for what came next. Six 90-minute remote contextual inquiries — observing product managers, engineers, designers, and analysts in their real hybrid workday, half from home and half from the office — were each paired with a 30-minute semi-structured follow-up interview, then worked through in team interpretation sessions. Two inquiry pilots preceded the recorded sessions.",
   "results": "Socialisation happens during breaks, and office breaks differ fundamentally from home-office breaks; the office is preferred for real interactions and faster communication while home office wins on convenience and fewer distractions; and nearly three-quarters of survey respondents agreed that knowing personal details about a colleague makes them relate more. Interaction across seniority levels and departments emerged as a persistent barrier. These findings shaped three competing concepts (Chat2Meet, Flows & Breaks, Interest-Based Communities); Interest-Based Communities was selected, refined into the final prototype, and validated in user testing sessions that returned positive feedback on usability and feature understanding.",
   "limitations": [
    "Survey respondents were recruited by convenience and snowball sampling, which biases the sample toward the team's own networks.",
    "Roughly three-quarters of respondents were aged 25–34 and about two-thirds worked in technology, so the sample under-represents deskbird's wider enterprise customer base.",
    "All six contextual inquiry participants worked in the IT industry, so the observed workday patterns are specific to that setting.",
    "Usability testing validated feature understanding and interaction, not adoption or effect on actual social connection — that would need a longitudinal study after launch.",
    "Two of the five planned study areas — emotional aspects of hybrid work, and social events and team building — were not run. Those questions were answered from survey responses alone rather than from dedicated study."
   ],
   "outcome": {
    "body": "At the final presentation, deskbird's stakeholders said they liked the concept and intended to build it in upcoming sprints. That is a stated intention recorded at handover — not confirmed delivery. The research team had no visibility into deskbird's backlog after the project ended, and I have not since verified whether the feature shipped. It is listed here as unconfirmed rather than claimed as adoption.",
    "adoption": "unknown"
   },
   "process": [
    {
     "phase": "discover",
     "type": "Heuristic Evaluation & Competitive Review",
     "title": "Learning the Product and the Landscape",
     "annotation": "Before talking to anyone we walked the existing deskbird app end to end, once as an admin and once as an end user, mapping its user flows and its existing social surface — annotating every screen against Nielsen's heuristics, colour-coded by which one was in question. In parallel we reviewed two landscapes: the engagement-platform set (Microsoft Viva Engage, Workvivo, Happeo, Haiilo, Staffbase, Donut for Slack, Sococo, Gather Town and others) and deskbird's direct desk-booking competitors (Flexopus, Deskly, Kadence, Seatti, Envoy, Yoffix and others), feature by feature.",
     "insight": "Presence data was not the gap: Flexopus, Deskly, Kadence, Seatti, Envoy and Yoffix all shipped some form of colleague finder, and our own review notes deskbird had the equivalent. What none of them did was use that data to create a connection. The social layer sat on top of work as a feed, a channel, or a chat — separate from the planning flow people were already in. The opening was to build the social feature into the scheduling surface rather than beside it."
    },
    {
     "phase": "discover",
     "type": "Stakeholder Interviews",
     "title": "Aligning on Scope with deskbird",
     "annotation": "Interviews across marketing, product management, product design, and customer support surfaced three insight clusters: brand identity (minimalist, usability-driven UX), consumer aspirations (fewer clicks, no extra browser tabs), and the social-feature mandate — transparent, non-intrusive, attracting people back to the office.",
     "insight": "The business goal ('attract people back to the office') and the user goal ('meaningful connection') were not the same thing — the requirements had to answer both."
    },
    {
     "phase": "discover",
     "type": "Scoping",
     "title": "Defining What a Social Feature Meant Here",
     "annotation": "Before scoping anything we wrote our own working definition: social features within deskbird are the functionalities that facilitate communication, collaboration, and community-building among employees in a hybrid workspace. Five candidate types sat inside it — centralised activity feeds, virtual or physical collaboration spaces, in-app messaging, customisable user profiles, and automated notifications and alerts.",
     "insight": "Naming the five types made the trade-off visible. Three of them — feeds, messaging, notifications — add a channel, which ran against the stakeholder mandate for something non-intrusive and free of extra browser tabs. Customisable user profiles was the type the concept work ended up building on."
    },
    {
     "phase": "discover",
     "type": "Online Survey",
     "title": "Quantifying Hybrid Social Life (N=57)",
     "annotation": "A ten-section instrument opening with a consent block: multiple-choice, rating, and open-ended questions across work conditions, social preferences, social interaction in work life, the role of the company, communication channels, emotional aspects, and privacy preferences. It was piloted with the think-aloud method and revised before launch. Respondents were mainly juniors aged 25–34 in the IT industry, across various company sizes. Participation was screened on currently or recently working in a hybrid setting.",
     "insight": "Nearly three-quarters agreed that knowing personal details about a colleague makes them relate more — the single strongest signal pointing toward interest-based connection. Respondents were open about gender, relationship status, and birthday, but split on age, hobbies, and personal milestones, which set a boundary for what any profile could ask for."
    },
    {
     "phase": "discover",
     "type": "Remote Contextual Inquiry",
     "title": "Observing the Hybrid Workday in Context (N=6)",
     "annotation": "Six 90-minute remote observations of hybrid workers in their real workplace — product manager, software engineer, customer success manager, product designer, UX working student, business analyst — followed by 30-minute semi-structured interviews to clarify observations and capture desires for improvement. Participants had to be in the office at least once a week, gender was distributed evenly, and half were observed from home and half from the office so the two settings could be compared directly. Two pilots preceded the recorded sessions. The open-ended survey answers set what we went looking for: how people decide between home and office, how they feel about office events, how they connect with colleagues.",
     "insight": "Breaks are when socialisation happens — and breaks at the office differ fundamentally from breaks at home. Participants wanted variety and meaningful social breaks — and to be left undisturbed when they needed focus."
    },
    {
     "phase": "define",
     "type": "Interpretation Sessions & Affinity Diagram",
     "title": "Six Workdays into One Picture",
     "annotation": "Each inquiry was worked through in a team interpretation session. Observations became numbered affinity notes tagged to the participant they came from, and each participant's workday was modelled from five angles — sequence, relationship, collaboration, identity, and physical setup. The five model types were divided across the team so that each one was built consistently across all six participants; I owned the collaboration model. The wall was then built in five passes: gather every note, group by observed pattern, write blue labels, consolidate blue into pink, and read actionable ideas off the top.",
     "insight": "Six themes came out of the wall: interruption and focus, work breaks, socialising at the workplace, what drives the choice between home and office, communication habits, and bonding at work. Because every note stayed tagged to its participant, any requirement could be walked back to the observation behind it."
    },
    {
     "phase": "define",
     "type": "Requirements Synthesis",
     "title": "From Findings to Requirement Categories",
     "annotation": "Findings were synthesised into functional, environmental, user, and data requirements: foster interaction across seniority levels and around shared interests, integrate seamlessly on every platform, stay accessible to both remote and on-site staff, stay intuitive for all users, and collect data privacy-first. Each entry carried the interview or exploration it came from, and the matrix went through a second pass after critique — one round mixed ideas in with requirements, and those were pulled back out into the ideation phase where they belonged.",
     "insight": "Interaction between different seniority levels and departments was where connecting stayed hardest — any concept had to lower that threshold, not just add another chat channel. The questions the matrix could not answer became three scoped follow-up studies: social interaction at the workplace, privacy preferences around social data, and communication channels."
    },
    {
     "phase": "design",
     "type": "Concept Development",
     "title": "Three Concepts, One Winner",
     "annotation": "Each of the three affinity sections was taken through visioning and then into concepts, and the pooled results were consolidated into five directions: efficient and engaging communication, interest-based events and social networking, personalised and optimised breaks, intelligent notifications and alerts, and well-being and productivity. Each direction was owned by one team member, who took it through a concept pack — background verbatims, a jobs-to-be-done statement, target users, target companies, a concept-level competitor review, a feature MVP breakdown, and a storyboard — and defended it in a review round where every concept received written feedback and a clarity check. Interest-based events and social networking was mine. Narrowing five to three was a scoping decision made in a brainstorming session as the project neared its end, not a scored comparison: personalised breaks and well-being overlapped enough to be merged by their owners into Flows & Breaks, intelligent notifications was dropped by group consensus, and the remaining three went to deskbird's stakeholders as Chat2Meet, Flows & Breaks, and Interest-Based Communities.",
     "insight": "My first storyboard proposed a matching mechanic: the system compares two profiles for shared interests and announces a match. A reviewer's note on the board read \"not too much dating up\", and the concern held — an interest feature that reads as a dating app is not something people will put a real hobby into at work. The matching mechanic was cut and the concept kept the parts that survived scrutiny: interests on the profile, colleagues' interests visible, and events built from what people already share. Groups, channels, buddy matching, and in-app calling all went with it."
    },
    {
     "phase": "design",
     "type": "Story Mapping & User Flows",
     "title": "Slicing the Concept into Three Releases",
     "annotation": "The selected concept was mapped as a user story map across four epics — customising the profile, managing interests as admin, creating events as admin, and connecting users — sliced into three releases. User flows were drawn for the first release covering three paths: the end user selecting interests, a second user viewing someone's profile, and the admin creating a tagged event with its invitation and notification logic.",
     "insight": "Privacy was scoped into the first release rather than deferred — interest visibility could be switched off at the profile level from the start, with finer per-interest controls held back for release three. That sequencing came straight out of the survey's split reaction to sharing personal details."
    },
    {
     "phase": "deliver",
     "type": "High-Fidelity Prototype",
     "title": "Interest-Based Communities Prototype",
     "annotation": "Final prototype: add your own interests, see colleagues' interests, get invited to events, and create events for like-minded people — accessible to both remote and on-site staff, and extended into the Slack side panel so it did not become another browser tab. Adding interests runs as a three-step flow — an onboarding prompt, a picker showing how many colleagues share each interest, and a confirmation that explains what changes as a result. Event creation lets an organiser choose invitees by name or team, by interest, or all employees, and the events list splits into all events and my interests events with RSVP counts on each. Validated in user testing sessions (feature understanding, usability issues), iteratively refined, and delivered to deskbird with documentation and development recommendations.",
     "insight": "Success indicators were defined up front and written to fit deskbird's own feature-launch process, which included a metric-definition step: number of interests created, profiles with interests, interest-based events, and attendees — making the feature's impact measurable post-launch."
    }
   ],
   "cardOutcome": "A survey and six contextual inquiries became three concepts; deskbird's stakeholders chose mine as the high-fidelity prototype."
  },
  {
   "title": "EmbraceMe – An Inflatable Soft Robot for Emotional Care",
   "page": "/projects/embraceme-soft-robotics",
   "status": "published",
   "subtitle": "A Pneumatic Soft-Robotic Hugging Interface, Exhibited & Evaluated in Public",
   "tagline": "Engineering a soft-robotic hug — and reporting where it fell short.",
   "role": "HCI Researcher & Prototyping Engineer (team of 3)",
   "year": "2023",
   "timeline": "Summer semester 2023",
   "context": "University research project",
   "tags": [
    "Soft Robotics",
    "Human-Robot Interaction",
    "Shape-Changing Interfaces",
    "Literature Review",
    "Competitive Analysis",
    "Physical Prototyping",
    "Material Testing",
    "Arduino",
    "Sensor Integration",
    "Interaction Design",
    "Data Physicalization",
    "Exhibition Research"
   ],
   "techStack": [
    "Arduino",
    "Festo 5/3 Solenoid Valve",
    "5-Pad Capacitive Touch Sensor",
    "TPU (heat-sealed)",
    "Foam Fabrication",
    "LED Feedback"
   ],
   "methods": [
    "Literature Review",
    "Comparative Analysis of Prior Systems",
    "Iterative Physical Prototyping",
    "Material Testing",
    "Public Exhibition & Observation",
    "Critical Reflection (Data Physicalization Framework)"
   ],
   "metrics": [
    {
     "value": "Public",
     "label": "exhibition with live user observation"
    },
    {
     "value": "3",
     "label": "prototype iterations to a working hug"
    },
    {
     "value": "3s / 9s",
     "label": "inflate–deflate cycle timing"
    },
    {
     "value": "80×16",
     "label": "cm PneuNet foam arms"
    }
   ],
   "about": "A soft-robotics project exploring whether a machine can deliver the calming effect of a hug. In a team of three I designed and built EmbraceMe, a standalone hugging robot with inflatable PneuNet foam arms driven by an Arduino and a capacitive touch sensor. We exhibited it publicly and observed real visitors using it — documenting both what delighted them and where the design fell short.",
   "challenge": "Physical touch like hugging releases oxytocin and measurably reduces stress — but not everyone has access to it: loved ones may be distant, or contact may be unsafe. We set out to build an inflatable soft-robotic interface delivering Deep Pressure Stimulation through a standalone hugging experience, gentle enough for direct human contact.",
   "solution": "A standalone hugging bot built on a mannequin frame with PneuNet bending-actuator arms: foam limbs (80×16 cm) with 45° triangular cuts housing heat-sealed TPU air chambers. A 5-pad capacitive touch sensor on the chest triggers inflation when a user leans in for a hug; a Festo 5/3 solenoid valve and timed Arduino logic (3s inflate, 9s deflate) regulate pressure, with an LED feedback cycle (green: ready, white: hugging, blinking red: resetting) communicating system state.",
   "methodology": "We grounded the design in a literature review of interpersonal touch, Deep Pressure Stimulation, and soft robotics, and a comparative analysis of prior hugging systems (Hug Over a Distance, Huggy Pajama, HugShirt, HuggieBot 3.0, MIT's Huggable, and Bauhaus's own Hugging Suit) to identify their gaps — partial body coverage, static holds, and no emotional context. Two actuation techniques were evaluated (soft-growing vs. PneuNet bending); the standalone form factor decided for inclusivity determined the PneuNet approach. The prototype then went through iterative material testing before public exhibition with observation and user feedback.",
   "results": "At a public university exhibition, visitors described the interaction as fun and surprising — the bot 'waking up' to hug back was the standout moment. The evaluation also surfaced honest design failures: some users read the pink, muscular arms as uncanny and avoided full contact, and without clear signifiers, nobody could guess how to initiate a hug unprompted. My individual follow-up applied Offenhuber's data physicalization framework to propose the next iteration: emotion-recognition data (wearables, mood tracking) mapped to arm extension and hug intensity, turning a binary-triggered mechanism into an emotionally adaptive interface.",
   "limitations": [
    "The exhibition evaluation was open observation and informal feedback, not a protocol: no task set, no structured interview, and no session notes were retained that would let a finding be recounted or a frequency stated.",
    "Nothing about the calming effect was measured. Deep Pressure Stimulation carries that claim in the literature; this prototype produced no physiological data and no self-reports of its own.",
    "Exhibition visitors are self-selecting and were watched in a social, playful setting — close to the opposite of the private moment of distress the concept was written for.",
    "There was one build and no comparison condition — no human hug, no static weighted alternative — so the observed reactions cannot be attributed to the soft-robotic actuation rather than to the novelty of the object.",
    "Arm length, cut geometry and the 3s/9s inflation timing were fixed for one body size. Fit, pressure and comfort across different bodies — and for the impaired users the concept names — were never tested.",
    "The redesign proposed in the individual reflection report — emotion-recognition data driving arm extension and hug intensity — was never built or evaluated; it remains an argument, not a result."
   ],
   "outcome": {
    "body": "EmbraceMe was not iterated into a second physical prototype after the exhibition — the group deliverable ended at the evaluated build. The follow-on work is a documented redesign proposal (individual report), not a shipped or roadmapped system, and no organisation has committed to building it.",
    "decisions": [
     "The visible design failures (uncanny arm aesthetics, no signifiers for initiating a hug) were not patched within the group project — they were carried into an individual critical-reflection report instead.",
     "The redesign proposal rejected the binary-trigger mechanism outright, replacing it with emotion-recognition data driving arm extension and hug intensity, with user autonomy, explicit consent, and privacy-first handling defined as guardrails before any such system would be built."
    ],
    "adoption": "academic"
   },
   "process": [
    {
     "phase": "discover",
     "type": "Literature Review",
     "title": "Deep Pressure Stimulation & Interpersonal Touch",
     "annotation": "Reviewed research on interpersonal touch, oxytocin response, and DPS therapy (weighted blankets as the canonical example), alongside soft robotics and shape-changing interface literature.",
     "insight": "Hugging is one of the most desired affectionate touches, with measurable stress-reduction effects — but replicating human hugging exactly was out of scope. The goal became a soft, warm embrace, not a simulation of a person."
    },
    {
     "phase": "discover",
     "type": "Comparative Analysis",
     "title": "Mapping the Gaps in Prior Hugging Systems",
     "annotation": "Analysed Hug Over a Distance, Huggy Pajama, HugShirt, HuggieBot 3.0, MIT's Huggable, and the Bauhaus Hugging Suit — comparing wearable vs. standalone forms, actuation, and sensing.",
     "insight": "Every prior system shared two gaps: partial-body sensory coverage and zero emotional context. Devices sense touch, not feelings — this framed both our prototype and my later data physicalization critique."
    },
    {
     "phase": "define",
     "type": "Form & Technique Decision",
     "title": "Backpack vs. Standalone",
     "annotation": "Two concepts sketched: a portable backpack using soft-growing (vine robot) arms, and a standalone figure using PneuNet bending actuators. Chose standalone after consultation, for inclusivity across body sizes and open access at the exhibition.",
     "insight": "The form-factor decision cascaded into the actuation technique: standalone required PneuNet bending arms that hold their position in space without a skeleton — the project's hardest engineering constraint."
    },
    {
     "phase": "design",
     "type": "Iterative Material Testing",
     "title": "Balloons → Transparent TPU → Yellow TPU",
     "annotation": "Proof-of-concept with balloons in slotted foam validated the bending mechanism. Transparent TPU replaced them for durability — but deformed irregularly after repeated inflation, breaking the curvature. Final iteration: stiffer yellow TPU chambers with regulated airflow to prevent bursting.",
     "insight": "Material properties drove interaction quality: consistent chamber volume was the difference between a controlled embrace and an erratic one. Slot spacing (10 cm) and chamber size (8×6 cm) were tuned empirically across numerous arm samples."
    },
    {
     "phase": "design",
     "type": "Sensing & Feedback System",
     "title": "Touch-Triggered Hugging with an LED Feedback Cycle",
     "annotation": "A 5-pad capacitive touch sensor on the bot's chest detects a user leaning in; Arduino opens the Festo 5/3 valve for 3 seconds to inflate, holds pressure during the hug, then vents for 9 seconds on release. LED states (green/white/blinking red) communicate readiness, hugging, and reset.",
     "insight": "Timings were derived through trial-and-error experimentation — long enough to hold a firm hug, short enough to protect the chambers from over-inflation."
    },
    {
     "phase": "deliver",
     "type": "Public Exhibition & Observation",
     "title": "What Visitors Actually Did",
     "annotation": "Exhibited at a university event open to academic and non-academic visitors. Observed interactions and collected impressions: delight at the bot 'waking up,' but also uncanny-valley reactions to its form and confusion about how to initiate contact without our explanation.",
     "insight": "Two design failures: aesthetic choices triggered avoidance in some users, and the interface lacked signifiers — curiosity did not translate into interaction without designer intervention."
    },
    {
     "phase": "deliver",
     "type": "Critical Reflection & Redesign Proposal",
     "title": "From Binary Trigger to Emotional Data (Individual Report)",
     "annotation": "Applied Offenhuber's data physicalization framework to critique the prototype: it followed a physical process triggered by binary signals and conveyed no emotional message. Proposed a redesign where emotion-recognition data (wearables, mood tracking) drives soft-growing arms — extension length and warmth mapped to the user's distress level, hug rhythm synced to heartbeat.",
     "insight": "The reflection reframed the project's failure as a data problem, not a hardware problem — and defined ethical guardrails: user autonomy over hug intensity, explicit consent, and privacy-first handling of emotional data."
    }
   ],
   "cardOutcome": "The hug delighted visitors — but without signifiers nobody could start one unprompted; the interaction, not the hardware, fell short."
  },
  {
   "title": "Smart Home Control for Shared Households",
   "page": "/projects/smart-home-control",
   "status": "published",
   "subtitle": "A Paper-Prototype Study of the Social Layer: Who May Add, Share, and Govern Devices",
   "tagline": "Who may add a device, remove a housemate, or override someone mid-use? The questions existing smart-home apps don't answer.",
   "role": "UX Researcher (team of 4)",
   "year": "2023",
   "timeline": "SoSe 2023",
   "context": "University course project",
   "tags": [
    "Questionnaire Study",
    "Think-Aloud Testing",
    "Paper Prototyping",
    "Qualitative Coding",
    "Thematic Analysis",
    "Information Architecture",
    "User Flow Mapping",
    "Iterative Design",
    "Accessibility",
    "Smart Home",
    "Google Forms"
   ],
   "techStack": [
    "Google Forms"
   ],
   "methods": [
    "Questionnaire study (N=24)",
    "Think-aloud usability testing (N=2)",
    "Low-fidelity paper prototyping",
    "Qualitative coding & thematic analysis",
    "Information architecture & flow mapping",
    "Iterative design revision"
   ],
   "metrics": [
    {
     "value": "24",
     "label": "questionnaire responses (of 30 people approached)"
    },
    {
     "value": "2",
     "label": "think-aloud usability test participants"
    },
    {
     "value": "12",
     "label": "screens across 4 documented task flows"
    },
    {
     "value": "4",
     "label": "design changes made from test findings"
    }
   ],
   "about": "A four-person course project at Bauhaus-Universität Weimar (summer semester 2023) about what smart-home apps get wrong about shared living. The design problem was never device control — existing apps solve that. It was the social layer of a shared household: who may add a device, who may remove a housemate, who may override someone else mid-use. A questionnaire study (24 responses) framed the territory, a 12-screen paper prototype made a governance model tangible, two think-aloud sessions tested it, and four design changes — each documented as a verbatim participant quote, the change it prompted, and a before/after photograph pair — closed the loop.",
   "challenge": "Smart-home apps model a home as one owner and a set of devices. A shared flat fits neither assumption: residents come and go, devices belong to some people and are used by everyone, and the moment two people want the same lamp at once is a social negotiation, not a technical conflict. The project framed exactly that gap — membership, permissions, and simultaneous use — as the design problem.",
   "solution": "A 12-screen paper prototype covering four documented task flows, all anchored on one home screen. Onboarding runs scanning → naming → access → confirmation, with a three-step progress indicator that deliberately stops at the confirmation screen. Governance is built into the everyday paths rather than an admin area: who may use a device is chosen at setup, residents are invited by link, and a device in use can be locked while in use — resolving simultaneous access without a queue. The galleries below show the tested v1 version, grouped by flow.",
   "design": "The revision is the most documented part of the project. Both test transcripts were coded into four categories — positive feedback, negative feedback, questions, ideas and suggestions — and four changes were made, each traceable to a verbatim quote from the sessions. They are shown below exactly as they happened: the quote, the change it prompted, and both photographs — the tested v1 screen on the left, the revised v2 screen on the right. The revision also fixed a defect the test itself exposed only indirectly: the resident roster differed across three v1 screens — two residents on one, three on another, five on a third, with the same person written “Drake” on one card and “Jake” on another. The v2 screens normalise the roster everywhere.",
   "methodology": "Phase 1 — Discovery. A questionnaire (Google Forms) was chosen over interviews, focus groups, and shadowing: it fit the timeline, and it let respondents answer at their own pace, which supported confidentiality and autonomy. It was piloted with a small group before distribution to check for ambiguity and leading questions; consent was obtained and responses were anonymous. Questions were sequenced deliberately — demographics, then habits, then needs — so respondents were not steered toward an attitude about smart homes early. Of 30 people approached, 24 responded. Roughly a third reported difficulty syncing devices; a quarter named remote adjustment of settings as a persistent pain point. Segmentation produced two named groups — students and part-time employees, and full-time employees — plus an “others” bucket, each with a documented attitude toward smart-home apps and a separate attitude toward mobile services generally. The user profile explicitly included cognitive, visual, and mobility impairment: accessibility was scoped at discovery, not bolted on later. Phase 2 — Evaluation. Two think-aloud sessions in a controlled setting, each participant seated individually with a facilitator. Audio was recorded and photographs taken; participants were briefed on recording and anonymity. The facilitator used probing questions when participants went quiet and observed facial expressions; each session ended with a retrospective debrief. Participant A — 31, a junior software developer. Participant B — 43, with a degree in an unrelated field. Both are iOS users; neither had used a smart-home app before. Transcripts were coded into four categories: positive feedback, negative feedback, questions, and ideas/suggestions.",
   "results": "The findings worth keeping are the ones that did not become quick fixes. A dead end surfaced in a flow we thought was finished: Participant A selected both devices at the scanning step, but only one carried into setup, and the confirmation screen had no way back — she noticed immediately and asked what had happened to the second device. Frames were read as the only tappable things: Participant B tapped only elements with a visible button border, engaging the boxed room selector on the device settings screen and treating the unframed rows beside it as labels. Destructive actions produced anxiety before they produced errors: encountering “delete this room”, Participant A worried aloud about triggering it accidentally and proposed moving room management to a dedicated screen — a structural objection, not a cosmetic one. The method itself was a finding: both participants needed to backtrack, neither could do it while holding the cards, and both ended up laying the prototype out on the floor — A sorting it into order first, B improvising late. And both participants opened every screen by reading its title aloud, which is why the “which home am I in?” gap surfaced on four separate screens. Two participants is a thin sample, and the original report says so. Revisiting the artifacts, the resident roster inconsistency across three tested screens is a defect a heuristic review would have caught before it reached a participant. The same revisiting surfaced a documentation lesson: most of the report's session photographs turn out to show the revised cards rather than the ones tested — the set was re-photographed after the changes were made. The sessions themselves are evidenced by the transcript and by the four changes that came out of them, but I'd now photograph artifacts at the moment of testing rather than afterwards.",
   "limitations": [
    "Two think-aloud participants is enough to expose a dead end and a misread affordance, not to establish how often either occurs or how severe it is. The original report says so, and no wider round followed.",
    "Both testers were iOS users who had never used a smart-home app, and neither was tested inside an actual shared household — the social situation the design is about was described to them, not lived during the session.",
    "The questionnaire (24 of 30 people approached) was distributed through the team's own reach, so it framed the territory and named pain points; it was never a representative sample of shared-flat residents.",
    "A paper prototype cannot produce the conflict the project is about: no device latency, no second resident acting at the same moment. Simultaneous use could only be walked through, never experienced.",
    "The v2 revision was never put in front of a participant, so the four changes are reasoned responses to observed problems — not changes shown to have fixed them.",
    "The photographic record is weaker than the sessions were: most session photographs in the report show the revised cards, because the set was re-photographed after the changes. What was tested is evidenced by the transcript, not by the photos."
   ],
   "outcome": {
    "body": "A university course project — adoption in the product sense doesn't apply. What the course closed on is the revised v2 prototype: four changes, each documented as a participant quote, the change it prompted, and a before/after photograph pair. The revision itself was never put in front of another participant — re-testing it is where a next session would have to start.",
    "adoption": "academic"
   },
   "verbatims": [
    {
     "quote": "Now I can go to the device… but what happened to the other device that I selected two steps ago? … there is not even any back button here…",
     "attribution": "Participant A, screen E — discovering the onboarding dead end"
    },
    {
     "quote": "I'm worried about this option... What if I delete it accidentally?",
     "attribution": "Participant A, screen F (room view) — on “delete this room”, before proposing a dedicated room-management screen"
    },
    {
     "quote": "what can I do with this radar? Is it clickable?",
     "attribution": "Participant B, screen B — the frames-are-tappable pattern, in his own words"
    }
   ],
   "cardOutcome": "Two think-aloud sessions turned verbatim quotes into four documented design changes, each shown as a before-and-after pair."
  },
  {
   "title": "Designing This Portfolio",
   "page": "/projects/designing-this-site",
   "status": "published",
   "subtitle": "A Case Study in Designing Under Constraint — One Person as Researcher, Designer, Engineer, and QA",
   "tagline": "The site itself, documented as a case study: one codebase for screen, print, and two languages — every claim measured or marked pending.",
   "role": "Researcher, Designer, Frontend Engineer & QA (solo)",
   "timeline": "Ongoing · continuously iterated",
   "tags": [
    "React",
    "Vite",
    "Tailwind CSS",
    "Framer Motion",
    "React Router",
    "OpenAI API",
    "Prompt Engineering",
    "Design Systems",
    "Component Architecture",
    "Information Architecture",
    "Responsive Design",
    "Accessibility",
    "Performance Optimization",
    "SEO",
    "Internationalization (i18n)",
    "Print CSS",
    "Automated Testing (Vitest)"
   ],
   "techStack": [
    "React",
    "Vite",
    "Tailwind CSS",
    "Framer Motion",
    "React Router",
    "Vitest",
    "Testing Library",
    "ESLint"
   ],
   "methods": [
    "Component Architecture & Design Systems Engineering",
    "Bilingual Content Architecture (EN/DE)",
    "Print-CSS Engineering (screen-to-A4)",
    "Invariant / Contract Testing (Vitest)"
   ],
   "metrics": [
    {
     "value": "99",
     "label": "Lighthouse — Performance"
    },
    {
     "value": "100",
     "label": "Lighthouse — Accessibility"
    },
    {
     "value": "100",
     "label": "Lighthouse — Best Practices"
    },
    {
     "value": "100",
     "label": "Lighthouse — SEO"
    },
    {
     "pending": true,
     "label": "WCAG 2.1 AA contrast, all token pairs"
    },
    {
     "pending": true,
     "label": "Keyboard-only + first-click task success"
    },
    {
     "pending": true,
     "label": "CV print length (target: 1 A4 page)"
    },
    {
     "pending": true,
     "label": "5-second test — time to answer ‘what does she do?’"
    }
   ],
   "about": "A case study on the site you are reading. I built it alone: research, design, frontend, QA. It is React and Tailwind, and it has to work for three readers at once — a recruiter with thirty seconds, an engineer who opens the source, and a hiring manager holding the printed A4 CV. What follows are the trade-offs that came out of that.",
   "wireframe": "Every case study here uses one layout. Above the xl breakpoint it runs in three tracks: a sticky numbered section rail on the left that collapses to a 56-pixel number strip, the prose column in the middle at a 68ch measure (88ch once the rail is collapsed), and a pull-quote rail on the right. Below md the rail becomes a plain section index under the header — a wrapped list of numbered links that scrolls away with the page, because a pinned bar inside a phone's scroll container was the one part of the layout that kept misbehaving on iOS. Below xl the pull-quote is dropped: it only repeats a sentence from the paragraph next to it. The order is not just convention. Every case study renders through the same ProjectTemplate({ meta, children }), and a fixed SECTIONS array decides what can appear and when — a data key that is not in it cannot render. One caveat on the figures below: I wireframed this site in the browser, so they are drawn from the shipped layout code, not from sketches that came first.",
   "designSystem": "Ink & Bloom, in short: a warm paper-and-ink palette, one loud coral accent, and a gold highlighter used at most once per page. Bricolage Grotesque for display type, DM Sans for body, Caveat for handwritten notes, and Framer Motion draw-ins that all share one easing curve. The table below reads its values from theme.css at render time instead of copying them, so it updates with the site rather than drifting from it. Two rules the numbers don't state on their own: each accent has a -500 step for large text and shapes and a -600 step for anything small enough that WCAG AA bites, and the gold sits outside that split — it is a background wash, never a text colour. Every icon in the interface, from arrows and chevrons to the ? and ! marks, is drawn with the same ~1.6–1.8px nib in one component file, so no icon font or library ships in the bundle. The full specimen sheet is the living style guide linked under Prototype. The same system is also published as a Figma Make kit — tokens, styles, components and the drawn-line rules, linked below.",
   "results": "Lighthouse 13.4.0 against production (emulated desktop, 24 August 2026): Performance 99, Accessibility 100, Best Practices 100, SEO 100. Mobile emulation the same day: 77, held down by a 4.4-second Largest Contentful Paint. Ten days earlier performance was 66, with a 0.261 layout shift, 340 ms blocking time and roughly 733 KiB of unused JavaScript. What closed the gap: a route-skeleton fix for the layout shift, lazy loading on every case-study figure, dead chunks removed, and a card/data split that took all five case studies' prose off the shared path (aggregator chunk 57 KB → 3.9 KB gzipped). Two optimisations I looked at and dropped: LazyMotion would save an estimated 20–25 KB gzipped but touch 35 files in the hand-drawn animation system, and splitting the profile data would break the local editor that writes it. Neither is worth it at these scores. The honest gap left is mobile LCP — a client-rendered hero can't paint before the JavaScript lands. Still open: the manual WCAG 2.1 AA contrast pass across every token pair (the automated audit found no failing pair, which is not the same thing), the keyboard-only run through the primary path, confirmation the CV prints to exactly one A4 page, and the two planned tests — time to answer 'what does she do?' and first-click success on the navigation.",
   "limitations": [
    "Sole author and sole evaluator. Every judgement here — structure, wording, visual system — is mine and unreviewed; there is no second designer on record who disagreed with any of it.",
    "No user research has run on the site itself. The 5-second test and the first-click test are defined and pending, so every usability claim here describes a mechanism in the source, not an observed effect on a reader.",
    "The Lighthouse numbers are single lab runs under emulation, from one machine and one network. There is no field data from real visitors, and mobile LCP in particular is the metric emulation flatters least.",
    "An automated accessibility score of 100 is not conformance. The manual contrast pass across every token pair and the keyboard-only walkthrough are still open, and nobody has run the site with a screen reader or with assistive technology in an actual user's hands."
   ],
   "outcome": {
    "body": "No outcome yet. Once the sessions run, whatever actually changed goes here: a shipped fix, a reprioritised backlog item, or a finding that changed nothing.",
    "adoption": "deferred"
   }
  }
 ],
 "voluntary": [
  {
   "title": "Awareness Member",
   "year": "2024 – Present",
   "org": "Bauhaus-Universität Weimar",
   "desc": "Awareness team member supporting university-wide student initiatives — helping keep them safe, inclusive, and accessible."
  },
  {
   "title": "Welcome Tutor",
   "year": "2022 – 2026",
   "org": "BUW International Office",
   "desc": "Guided incoming international students through arrival, cultural adjustment, and the administrative processes of their first semesters."
  },
  {
   "title": "Student Volunteer",
   "year": "2024",
   "org": "Digital Leute"
  },
  {
   "title": "Student Volunteer",
   "year": "2022",
   "org": "JCSG & Mensch und Computer",
   "desc": "Session and workshop support at Mensch und Computer (TU Darmstadt) and conference operations at JCSG in Weimar."
  }
 ],
 "pages": {
  "home": "/",
  "projects": "/projects",
  "about": "/about",
  "cv": "/cv",
  "contact": "/contact",
  "credentials": "/credentials",
  "voluntary": "/voluntary"
 }
};
