// Generated by scripts/generate-chat-knowledge.mjs — do not edit by hand.
// Derived from src/data/data.json and src/projects/*/<slug>.data.js (English locale).
export default {
 "profile": {
  "name": "Sanaz Yazdanjoo",
  "role": "UX Engineer",
  "tagline": "I speak both ‘user’ & ‘developer’.",
  "positioning": "UX Engineer bridging mixed-methods research and production React.",
  "profileSummary": "I'm a UX Engineer with an M.Sc. in Human-Computer Interaction (Bauhaus-Universität Weimar), a B.E. in Software Engineering, and experience across user research, UI development, and software usability since 2015. I like working on both ends of a product: running mixed-methods user studies to understand what people actually need — and what's worth building — and then taking those findings all the way into responsive, accessible interfaces in React and TypeScript, backed by lightweight backends. I use AI-assisted development tools productively, while reviewing the generated code critically. The case studies below show how that plays out in real projects.",
  "impactStats": [
   {
    "value": "N=30",
    "label": "Controlled eye-tracking experiment"
   },
   {
    "value": "110+",
    "label": "Study participants across projects"
   },
   {
    "value": "Since 2015",
    "label": "Research, UI & usability experience"
   }
  ],
  "bioParagraphs": [
   "I'm a UX Engineer with an M.Sc. in Human-Computer Interaction (Bauhaus-Universität Weimar), a B.E. in Software Engineering, and experience across user research, UI development, and software usability since 2015. I like working on both ends of a product: running mixed-methods user studies to understand what people actually need — and what's worth building — and then taking those findings all the way into responsive, accessible interfaces in React and TypeScript, backed by lightweight backends. I work in English and German (both C1), and I'm open to interdisciplinary UX & Tech roles."
  ],
  "experience": [
   {
    "company": "Institut für Berufsbildung und Sozialmanagement (IBS)",
    "role": "Project Assistant & UX Engineer",
    "date": "12/2024 – Present",
    "impactMetrics": [
     "13-step paper workflow digitised",
     "1,734 automated tests, build-enforced requirement traceability",
     "GDPR-first data pipeline"
    ],
    "tasks": [
     "Engineered a role-based web application (React, TypeScript, Vite, SQLite) to digitalise a 13-step paper reimbursement workflow, replacing manual Excel tracking with an explicit claim state machine backed by 1,734 automated tests.",
     "Ran empirical UX research (5W1H, UML activity diagrams, stakeholder mapping) across the 9 actors of the paper process, which the system implements as 5 permission roles; structural workflow failures were translated into numbered requirements whose citations in code are kept traceable by a build-failing test.",
     "Built a strict GDPR/DSGVO-compliant data pipeline with local persistence adapters and Nextcloud WebDAV integrations, ensuring participant data never leaves internal institute servers.",
     "Secured the Fastify (Node.js) backend with session-based authentication (argon2id password hashing), CSRF protection, rate limiting, and server-side role checks, keeping each role view inside its permitted scope.",
     "Worked in German throughout the project, conducting expert validation interviews and task-based evaluations to refine inclusive features like mobile-first camera capture and guided step-by-step modes."
    ]
   },
   {
    "company": "Bauhaus-Universität Weimar",
    "role": "UX Engineer / Researcher — Master's Thesis",
    "date": "10/2025 – 05/2026",
    "impactMetrics": [
     "Key finding: trust beats raw speed",
     "N=30 within-subjects, 3 conditions",
     "TypeScript + Python gaze pipeline"
    ],
    "tasks": [
     "Independently developed the entire experimental platform — a TypeScript frontend with a Python backend bridging the Pupil Labs Neon eye tracker's real-time API — implementing complex gaze-assisted interaction techniques (MAGIC Pointing, Ninja Cursors), stimulus presentation, and performant data logging.",
     "Designed and conducted a controlled within-subjects experiment (n=30) comparing the developed input techniques against a mouse baseline in dual-display environments.",
     "Evaluated performance and user experience using mixed methods, analysing movement time and SUS in R; key finding for complex system development: predictability and user trust are more critical for adoption than raw speed."
    ]
   },
   {
    "company": "deskbird × Bauhaus-Universität Weimar",
    "role": "UX Researcher — Research Project",
    "date": "10/2023 – 03/2024",
    "impactMetrics": [
     "My concept won the client vote",
     "3 concepts → 1, evidence-decided",
     "n=57 survey · n=6 contextual inquiry"
    ],
    "tasks": [
     "Ran end-to-end user research as part of a six-person team for a B2B SaaS product in the hybrid work sector (surveys, contextual inquiries, stakeholder interviews).",
     "Synthesised research findings into three competing concepts; client stakeholders selected mine by vote, and it was delivered as a high-fidelity prototype with development recommendations for their upcoming sprints."
    ]
   },
   {
    "company": "Bauhaus-Universität Weimar",
    "role": "Web Designer & Content Manager — Working Student",
    "date": "04/2023 – 09/2023",
    "impactMetrics": [
     "Accessibility-validated components",
     "Corporate design compliance, TYPO3"
    ],
    "tasks": [
     "Developed responsive frontend components (HTML/CSS) and maintained dynamic content on the university's TYPO3 pages.",
     "Strictly adhered to corporate design guidelines and validated components against modern web accessibility standards."
    ]
   },
   {
    "company": "TDSoftware",
    "role": "QA Engineer — Working Student",
    "date": "04/2022 – 06/2022",
    "impactMetrics": [
     "Cross-functional defect triage pre-release",
     "Heuristic evaluation + REST validation"
    ],
    "tasks": [
     "Conducted acceptance testing and heuristic evaluations in close collaboration with the frontend development team to prioritise and resolve bugs prior to release.",
     "Technically validated REST endpoints and backend interfaces using Postman."
    ]
   },
   {
    "company": "Part Software Group",
    "role": "Usability & QA Engineer",
    "date": "07/2020 – 07/2021",
    "impactMetrics": [
     "Co-established the company's first manual-testing group",
     "Trained 4 QA members",
     "Heuristic evaluation across 5+ products"
    ],
    "tasks": [
     "Contributed to establishing the first manual acceptance-testing group at the 500+ employee software group and trained its 4 QA members, introducing TestLink for test-case management and more efficient bug-tracking workflows.",
     "Ran acceptance testing across web and mobile app projects — surfacing pain points from the end-user perspective, checking UI against standards, and improving overall product quality.",
     "Validated APIs with Postman on selected projects and conducted structured heuristic evaluations for 5+ digital products, collaborating closely with development teams to iteratively implement usability improvements."
    ]
   },
   {
    "company": "Mega-Tech",
    "role": "UI Developer / R&D Developer (started as Intern)",
    "date": "09/2015 – 07/2020",
    "impactMetrics": [
     "Page-1 Google rankings, 10+ client sites",
     "10+ sites shipped over 5 years",
     "Cross-browser & cross-device QA"
    ],
    "tasks": [
     "Developed 10+ WordPress and WooCommerce websites (corporate, e-commerce, portfolio) at the web agency, including cross-browser and cross-device optimization.",
     "Applied SEO and performance best practices, leading to page 1 Google search rankings for target keywords across 10+ client sites.",
     "Moved from WordPress UI development into R&D work across the agency's client web projects — including nopCommerce e-commerce builds and Unity-based projects."
    ]
   },
   {
    "company": "Black Citrus",
    "role": "QA Engineer — Internship via Mega-Tech (remote)",
    "date": "06/2015 – 09/2015",
    "impactMetrics": [
     "First industry role, straight after the B.E.",
     "Remote QA for an Australian team"
    ],
    "tasks": [
     "Started as an intern at Mega-Tech, outsourced as a QA engineer to Black Citrus, an Australian company — manually testing its web application projects remotely under Mega-Tech's supervision, directly after finishing the bachelor thesis."
    ]
   }
  ],
  "education": [
   {
    "school": "Bauhaus-Universität Weimar",
    "degree": "M.Sc. Human-Computer Interaction",
    "year": "2022 – 2026",
    "grade": "Final grade: 1.7",
    "awards": [
     "Thesis: Gaze-Assisted Input in Dual-Display Environments"
    ]
   },
   {
    "school": "Khayyam Higher Education Centre",
    "degree": "B.E. Software Engineering",
    "year": "10/2010 – 06/2015"
   }
  ],
  "skills": {
   "Frontend Engineering & Design": [
    "JavaScript (ES6+)",
    "TypeScript",
    "React",
    "HTML",
    "CSS",
    "Tailwind CSS",
    "Vite",
    "Web Accessibility",
    "Figma",
    "WordPress",
    "WooCommerce",
    "nopCommerce",
    "E-Commerce"
   ],
   "Backend & Data": [
    "Node.js (Fastify)",
    "SQLite",
    "REST APIs",
    "OpenAI API",
    "Authentication & Security (Argon2id, CSRF)"
   ],
   "UX Research & Testing": [
    "B2B User Research",
    "Mixed-Methods Research",
    "Requirements Engineering",
    "Usability Testing",
    "Controlled Experiments",
    "Eye-Tracking Evaluation (Pupil Labs)",
    "Contextual Inquiry",
    "Affinity Diagramming",
    "Stakeholder Interviews",
    "Questionnaire Design"
   ],
   "QA & Testing": [
    "Unit & Integration Testing (Vitest)",
    "Postman (REST API Validation)",
    "TestLink",
    "Heuristic Evaluation",
    "Acceptance Testing"
   ],
   "Analysis & Tools": [
    "Python",
    "R (Statistical Analysis)",
    "Git & GitHub",
    "Vercel",
    "Unity"
   ]
  },
  "languages": [
   {
    "name": "English",
    "level": "C1 (Fluent)"
   },
   {
    "name": "German",
    "level": "C1 (DSH-2)"
   },
   {
    "name": "Persian",
    "level": "Native"
   }
  ],
  "certifications": [
   {
    "title": "M.Sc. Human-Computer Interaction",
    "provider": "Bauhaus-Universität Weimar, Faculty of Media",
    "year": "2026",
    "type": "degree",
    "topic": "academic",
    "featured": false,
    "skills": [
     "HCI Research",
     "Visual Interfaces",
     "Design Theory"
    ],
    "verifyUrl": "",
    "detail": "Final grade 1.7 (gut), 120 ECTS. Thesis: Gaze-Assisted Input in Dual-Display Environments — a comparative evaluation of MAGIC Pointing, Ninja Cursors, and a mouse baseline. Thesis grade: 1.5."
   },
   {
    "title": "DSH-2 (German Language Proficiency for University Admission)",
    "provider": "Sprachenzentrum, Bauhaus-Universität Weimar",
    "year": "2026",
    "type": "language",
    "topic": "academic",
    "featured": true,
    "skills": [
     "German C1"
    ],
    "verifyUrl": "",
    "detail": "Unrestricted admission to all German degree programmes."
   },
   {
    "title": "Figma 101 Workshop",
    "provider": "Human-Computer Interaction Group, Bauhaus-Universität Weimar",
    "year": "2025",
    "type": "workshop",
    "topic": "design",
    "featured": true,
    "skills": [
     "Figma",
     "Auto Layout",
     "Design Systems",
     "Prototyping"
    ],
    "verifyUrl": "",
    "detail": "Auto Layout, wireframe libraries, design systems and prototyping — three assignments, concluding in a mini portfolio."
   },
   {
    "title": "Designing Accessible Components in Figma",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-09-20",
    "duration": "1 h 11 min",
    "type": "course",
    "topic": "accessibility",
    "featured": false,
    "skills": [
     "Computer Accessibility",
     "Figma"
    ],
    "verifyUrl": "",
    "detail": "Building components that stay usable with assistive technology — contrast, focus order, and annotation conventions inside Figma."
   },
   {
    "title": "20 Rules for Visual Communication",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-09-03",
    "duration": "2 h 2 min",
    "type": "course",
    "topic": "design",
    "skills": [
     "Visual Communication"
    ],
    "verifyUrl": "",
    "detail": "Composition, hierarchy, type and colour rules for making a message legible at a glance."
   },
   {
    "title": "Design Thinking: Understanding the Process",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-09-03",
    "type": "course",
    "topic": "strategy",
    "skills": [
     "Design Thinking",
     "Product Development"
    ],
    "verifyUrl": "",
    "detail": "The full double-diamond loop — empathise, define, ideate, prototype, test — and where each phase pays off in product work."
   },
   {
    "title": "Figma Essential Training: The Basics",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-09-03",
    "duration": "1 h 37 min",
    "type": "course",
    "topic": "design",
    "skills": [
     "Figma"
    ],
    "verifyUrl": "",
    "detail": "Frames, components, styles and shared libraries — the working vocabulary behind every file I hand to developers."
   },
   {
    "title": "UX Deep Dive: Usability Testing",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-06-02",
    "duration": "26 min",
    "type": "course",
    "topic": "research",
    "featured": false,
    "skills": [
     "Usability Testing"
    ],
    "verifyUrl": "",
    "detail": "Planning a test, writing non-leading tasks, moderating, and turning observations into prioritised findings."
   },
   {
    "title": "UX Design 7: Implementation Planning",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-06-02",
    "duration": "18 min",
    "type": "course",
    "topic": "strategy",
    "skills": [
     "User Experience Design"
    ],
    "verifyUrl": "",
    "detail": "Handing a design over: scoping, sequencing and documenting what engineering actually needs to build it."
   },
   {
    "title": "UX for Web Forms",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-05-26",
    "duration": "2 h 18 min",
    "type": "course",
    "topic": "engineering",
    "skills": [
     "Forms Development",
     "User Experience"
    ],
    "verifyUrl": "",
    "detail": "Field design, inline validation, error recovery and accessible labelling for the forms that carry most conversions."
   },
   {
    "title": "UX Design 1: Overview",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-05-25",
    "duration": "13 min",
    "type": "course",
    "topic": "strategy",
    "skills": [
     "User Experience Design"
    ],
    "verifyUrl": "",
    "detail": "How the phases of a UX process fit together, and which deliverable belongs to which phase."
   },
   {
    "title": "UX Design 2: Analyzing User Data",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-05-25",
    "duration": "30 min",
    "type": "course",
    "topic": "research",
    "skills": [
     "User Analysis"
    ],
    "verifyUrl": "",
    "detail": "Turning raw research data into patterns — affinity mapping, segmentation, and reading quantitative signals honestly."
   },
   {
    "title": "XML Essential Training",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-05-21",
    "duration": "3 h 52 min",
    "type": "course",
    "topic": "engineering",
    "skills": [
     "XML",
     "Schemas",
     "XSLT"
    ],
    "verifyUrl": "",
    "detail": "Document structure, DTDs and schemas, namespaces, XPath and XSLT transformations."
   },
   {
    "title": "Using AI in the UX Design Process",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-05-20",
    "duration": "1 h 7 min",
    "type": "course",
    "topic": "ai",
    "featured": false,
    "skills": [
     "Artificial Intelligence for Design",
     "User Experience Design"
    ],
    "verifyUrl": "",
    "detail": "Where generative AI genuinely speeds up research synthesis, ideation and content drafting — and where it quietly misleads."
   },
   {
    "title": "A Design Thinking Approach to Putting the Customer First",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-04-28",
    "duration": "27 min",
    "type": "course",
    "topic": "strategy",
    "skills": [
     "Customer-Focused Design"
    ],
    "verifyUrl": "",
    "detail": "Keeping the customer's problem — not the team's assumptions — at the centre of a design decision."
   },
   {
    "title": "UX Design 3: Creating Personas",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-04-17",
    "duration": "25 min",
    "type": "course",
    "topic": "research",
    "skills": [
     "User Personas"
    ],
    "verifyUrl": "",
    "detail": "Building personas from evidence rather than invention, and keeping them usable once the project moves on."
   },
   {
    "title": "UX Design 5: Creating Scenarios and Storyboards",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-04-17",
    "duration": "20 min",
    "type": "course",
    "topic": "research",
    "skills": [
     "User Experience Design",
     "Storyboarding"
    ],
    "verifyUrl": "",
    "detail": "Narrating a user's context as a scenario, then drawing it out as a storyboard the whole team can argue with."
   },
   {
    "title": "Agile User Experience Design and Research",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-04-12",
    "duration": "59 min",
    "type": "course",
    "topic": "strategy",
    "featured": false,
    "skills": [
     "Agile Methodologies",
     "UX Research"
    ],
    "verifyUrl": "",
    "detail": "Fitting research and design into sprint cadence — continuous discovery, lean deliverables, and testing one sprint ahead."
   },
   {
    "title": "Using Style Guides to Bridge Design and Development",
    "provider": "LinkedIn Learning",
    "year": "2024",
    "date": "2024-04-07",
    "duration": "50 min",
    "type": "course",
    "topic": "design",
    "skills": [
     "User Interface Design",
     "Style Guides",
     "User Experience Design"
    ],
    "verifyUrl": "",
    "detail": "Style guides and design systems as the shared contract between a design file and the components that ship."
   },
   {
    "title": "Student Volunteer — Mensch und Computer 2022",
    "provider": "Gesellschaft für Informatik (GI e.V.) · ACM In-Cooperation",
    "year": "2022",
    "type": "recognition",
    "topic": "academic",
    "featured": false,
    "skills": [
     "Session Chairing",
     "Conference Operations"
    ],
    "verifyUrl": "",
    "detail": "Session and workshop support at Europe's largest HCI conference series (~600 participants), hosted by TU Darmstadt."
   },
   {
    "title": "Student Volunteer — Joint Conference on Serious Games 2022",
    "provider": "JCSG 2022, Bauhaus-Universität Weimar",
    "year": "2022",
    "date": "2022-09-23",
    "type": "recognition",
    "topic": "academic",
    "featured": false,
    "skills": [
     "Conference Operations",
     "Speaker Support"
    ],
    "verifyUrl": "",
    "detail": "Venue setup, guest welcome and speaker support across the two conference days, 22–23 September 2022 in Weimar."
   },
   {
    "title": "Frontend Development",
    "provider": "Part College",
    "year": "2021",
    "type": "course",
    "topic": "engineering",
    "featured": true,
    "skills": [
     "Frontend Development"
    ],
    "verifyUrl": "",
    "detail": "Frontend development course offered through Part College, completed with certificate while working at Part Software Group."
   },
   {
    "title": "Python Programming",
    "provider": "Technical & Vocational Training Organization",
    "year": "2019",
    "type": "certification",
    "topic": "engineering",
    "featured": true,
    "skills": [
     "Python"
    ],
    "verifyUrl": "",
    "detail": "Certified training in Python programming."
   }
  ],
  "contact": {
   "location": "Weimar, Germany",
   "email": "sanaz.yazdanjoo@gmail.com",
   "linkedin": "https://www.linkedin.com/in/sanaz-yazdanjoo/",
   "github": "https://github.com/SanazYazdanjoo",
   "website": "https://yazdanjoo.de",
   "availability": "I currently live in Weimar but open to relocate.",
   "timezone": "CET (UTC+1)"
  }
 },
 "projects": [
  {
   "title": "Digitalising IBS Travel Reimbursements",
   "page": "/projects/digitalising-ibs-travel-reimbursements",
   "status": "in-progress",
   "subtitle": "From paper forms and a folder of Excel files to one traceable application",
   "tagline": "A reimbursement process whose only status update is the money arriving — researched from the inside, rebuilt from the evidence.",
   "role": "Solo — UX Research, UI Design, and Frontend Development",
   "year": "2026",
   "timeline": "2026 · four phases · ongoing",
   "context": "In-house project",
   "tags": [
    "UX Research",
    "Stakeholder Interviews",
    "Survey Design",
    "Thematic Analysis",
    "Persona Development",
    "Process Mapping (UML)",
    "Service Design",
    "Requirements Engineering",
    "Requirements Traceability",
    "Information Architecture",
    "State Machine Modelling",
    "Wireframing",
    "Low-Fidelity Wireframe",
    "High-Fidelity Wireframe",
    "Interaction Design",
    "Design Systems",
    "Prototyping",
    "Usability Evaluation (instrumented)",
    "Accessibility",
    "Data Visualization",
    "React",
    "TypeScript",
    "Node.js / Fastify",
    "SQLite",
    "Excel Automation (SheetJS)",
    "Automated Testing (Vitest)",
    "Claude Code",
    "Claude Design",
    "Figma Make",
    "Product Instrumentation",
    "Privacy by Design",
    "GDPR / DSGVO"
   ],
   "techStack": [
    "React",
    "TypeScript",
    "Vite",
    "Tailwind CSS",
    "Vitest",
    "Node.js Server (Fastify)",
    "Session Auth (argon2id) · CSRF · Rate Limiting",
    "SQLite",
    "SheetJS / Local Excel Files",
    "Nextcloud WebDAV Integration",
    "SVG (hand-authored diagrams)",
    "Claude Design (case-study figures, diagrams, early wireframes)",
    "Figma Make (clickable low-fidelity wireframe set)",
    "Claude Code (AI-assisted development)"
   ],
   "methods": [
    "Insider process observation (AS-IS)",
    "Expert interviews (n=2: project management, accounting) plus one working meeting with the administration team",
    "Participant survey (n=6 and open, anonymous, BL cohort so far)",
    "Document & artefact analysis",
    "Thematic analysis / affinity clustering",
    "Stakeholder mapping",
    "UML activity diagrams (swimlane)",
    "5W1H problem framing",
    "Persona development with provenance labelling",
    "Requirements traceability (FR / NFR / P-IDs)",
    "Information architecture & state modelling",
    "Single-case cycle-time observation (right-censored)",
    "Built-in usage instrumentation (pseudonymous, local-only)"
   ],
   "metrics": [
    {
     "value": "25",
     "label": "problems documented — six added by the participant survey"
    },
    {
     "value": "n=6",
     "label": "survey responses so far — the survey is open, and the in-person (Präsenzkurs) cohort is not yet reached"
    },
    {
     "value": "n=2",
     "label": "expert interviews — project management and accounting — plus a working meeting with the administration team"
    },
    {
     "value": ">1 yr",
     "label": "running the process myself before redesigning it — insider observation as the first evidence source"
    },
    {
     "value": "7",
     "label": "personas, each with its provenance stated"
    },
    {
     "value": "9",
     "label": "actors mapped across 13 steps and 4 return loops"
    },
    {
     "value": "43+",
     "label": "days and still unpaid — one claim traced end to end through the paper process: 8 days sitting unseen, 1 day of admin work, the rest downstream and invisible"
    },
    {
     "value": "0",
     "label": "reminders for private-vehicle (PKW) claims in the paper process — submitting depended entirely on the participant remembering"
    },
    {
     "value": "4/6",
     "label": "respondents do not know how their amount is calculated; two have stopped trying"
    },
    {
     "value": "1,734",
     "label": "automated tests — including guards that fail the build on an untraced requirement citation or a design-token drift"
    }
   ],
   "about": "I joined the institute as a project assistant and ran this reimbursement process myself for over a year — long enough to see that it was not just inefficient but a steady source of frustration and avoidable mistakes for everyone in it. With a Master’s in HCI I had the research methods to turn those observations into verified requirements, and as a frontend developer I could carry the same requirements into working code — so I proposed replacing the scattered spreadsheets with one integrated application, and built it. As of August 2026 the prototype is in active development: the team works with the deployed demo and feeds back, the screens are being consolidated through that feedback and instrumented testing before release as the real product, and every claim on this page traces to a survey answer, a process map, or a line of code.",
   "challenge": "Every month, participants in a state-funded qualification programme claim back their travel costs. On paper it is a form; in practice it was an ecosystem of disconnected spreadsheets held together by one administrative role. Attendance started as paper marks in the classroom, was retyped by lecturers into an attendance-only Excel shared over Teams — often late, often incomplete, always chased — and exported again by the admin. A hasty „A“ for a participant who left early could quietly become an unexcused „U“ if the follow-up excuse never arrived, unfairly costing attendance days and, with them, reimbursement money. Calculating each month’s totals followed rules so error-prone that I built myself a helper spreadsheet just to get them right. Around that sat a master overview file, one prefilled Abrechnung file per participant, and whatever month- or case-specific lists the situation required. Participants, meanwhile, submitted into a void: no visible calculation, no confirmation, no status — four of six survey respondents could not even say how long reimbursement takes. The failure was structural, not clerical.",
   "solution": "The app is one place where the whole monthly cycle happens: participants photograph and submit their proofs, lecturers keep attendance directly instead of retyping paper into a Teams spreadsheet, the admin sees every claim’s state and calculation, approvers release with one decision, and accounting reads the same numbers as everyone else. Five purpose-built role views replace the spreadsheet ecosystem. Participants get a mobile-first upload path with camera capture and an optional guided step-by-step mode for lower digital fluency, and the claim moves through an explicit state machine — “where is my money” has an on-screen answer for the first time. Amounts make the round trip instead of being stored: the database holds only the typed fields, and the amount is rebuilt from the same pure computation every time any role opens the record, with its full formula trace visible. Persistence sits behind adapters over a local SQLite database, with stored proofs mirrored to the institute’s own Nextcloud; the one named external call is a route lookup to Google Maps when staff check a driving distance, stated in the data-protection documentation rather than hidden.",
   "design": "The design system was extracted before the high-fidelity screens, not after them: brand colours, a nine-colour role palette carried unchanged from the research diagram’s lanes, note states, a type scale, and form-field states — so a lane in the research reads as the same actor as a badge in the app. How the screens themselves took shape, from paper sketch to wireframe to shipped view, is shown in the Wireframes section below.",
   "wireframe": "Before the high-fidelity screens were built, the layouts were drawn as wireframes against the numbered requirements from Phase 2. A wireframe fixes the structure of a screen — which elements it contains, in what order, and which rules apply — before colour and typography come in. Both stages were built as clickable prototypes in Figma Make — a low-fidelity set that decides structure in grey boxes, and a high-fidelity set that runs the same structure with the design system applied — so the navigation between screens could be walked through and not just imagined. The strip below shows the path for the attendance-month screen: the paper sketch from the process observation, the wireframe, and the screen as it shipped. The same screen then follows twice at full size, low fidelity and high fidelity, so the two stages can be held against each other.",
   "methodology": "The project runs as a user-centred design process in the shape of the double diamond. Discover: insider observation from more than a year inside the process, two expert interviews — project management and accounting — plus a working meeting with the administration team, and the participant survey (n=6 and open), which reversed one of my priorities and added six problems I had not seen from the inside; because I knew the workflow personally, the first research task was strictly about making my own assumptions falsifiable. Define: thematic clustering into a problem register where every entry carries an evidence grade — confirmed, indicative, hypothesis, untested — and counts confirm or reframe a problem, never size it; the clustered problems became numbered requirements, a role-based sitemap, and the IBS-DesignSystem, whose nine role colours are the nine lane colours of the research map. Develop: Phase 3 engineered the calculation rules as pure, unit-tested TypeScript, with a build-failing test that keeps every requirement citation in code traced to its source problem — and states its own limit: it catches a citation without a source, not a problem without an implementation. Deliver: the evaluation is built into the app itself — guided tasks, a pseudonymous local event log, an end-of-session questionnaire — and dogfooding it on my own development traffic already caught three of its own measurement bugs.",
   "results": "The baseline this project will be measured against — the paper process — is in the metrics above; the instruments that will measure the change are described in the methodology.",
   "limitations": [
    "I ran this process myself for more than a year, so the problem framing starts from my own experience. The survey was designed to make those assumptions falsifiable — and reversed one of my priorities — but no independent researcher has reviewed the problem register.",
    "The survey is n=6, self-selected, and so far entirely from the online (BL) cohort. The Präsenzkurs cohort and travel-pass (Abo-Karte) holders are absent, which is why findings are reported as counts: enough to confirm or reframe a problem, never to size it.",
    "Two expert interviews mean one voice per role — project management and accounting. Lecturers, who carry the attendance step the whole chain depends on, were not interviewed; their part of the process is mapped from artefacts and my own observation.",
    "The 43+ day figure is one claim traced end to end, and it is right-censored: the claim was still unpaid when the observation stopped. It shows how long the paper process can take — it is not an average and not a distribution.",
    "No usability evaluation has run. The instruments are built into the app and dogfooded, but every claim about the new system is a claim about a mechanism that exists — not about a measured improvement over the paper process.",
    "The traceability test guards citations, not coverage: it fails the build on a requirement citation without a source problem, and stays silent on a source problem with no implementation."
   ],
   "outcome": {
    "body": "Deferred by decision (status: August 2026): this space reports measured outcomes once the application is published and in daily use. The evaluation is already built into the app — guided tasks, an event log, an end-of-session questionnaire — so when the sessions run, what changed gets recorded here, not estimated beforehand.",
    "adoption": "deferred"
   },
   "verbatims": [
    {
     "quote": "No, I just take the amount as it comes.",
     "attribution": "Survey respondent, asked whether they check how their reimbursement is calculated — two of six answered in exactly these words (translated from German)"
    },
    {
     "quote": "The processing time is the hardest part for me.",
     "attribution": "Survey respondent — four of six named processing time as their main difficulty; translated from German"
    },
    {
     "quote": "I don’t check it.",
     "attribution": "Survey respondent, asked how they know their documents arrived — five of six have no reliable way of knowing: four wait for the money, one has stopped checking altogether (translated from German)"
    }
   ],
   "cardOutcome": "Rebuilt a 13-step paper reimbursement process as a working application the team now uses as a deployed demo."
  },
  {
   "title": "Encouraging Social Interactions in Hybrid Work",
   "page": "/projects/deskbird-hybrid-work",
   "status": "published",
   "subtitle": "Industry UX Research Project with deskbird × Bauhaus-Universität Weimar",
   "tagline": "Reconnecting hybrid teams through evidence-based social feature design.",
   "role": "UX Researcher (team of 6)",
   "year": "2023–2024",
   "timeline": "10/2023 – 03/2024",
   "context": "Industry project · deskbird",
   "tags": [
    "User-Centered Design",
    "Mixed-Methods Research",
    "Stakeholder Interviews",
    "Contextual Inquiry",
    "Survey Design",
    "Competitive Analysis",
    "Affinity Diagramming",
    "Requirements Engineering",
    "Concept Development",
    "Interaction Design",
    "High-Fidelity Prototyping",
    "Usability Testing",
    "Figma",
    "B2B SaaS"
   ],
   "techStack": [
    "Figma",
    "FigJam",
    "Online Survey Tools"
   ],
   "methods": [
    "Heuristic Evaluation (admin & end user)",
    "Competitive & State-of-the-Art Review",
    "Stakeholder Interviews",
    "Online Survey",
    "Remote Contextual Inquiry (90 min)",
    "Semi-structured Follow-up Interviews (30 min)",
    "Interpretation Sessions & Contextual Design Models",
    "Affinity Diagramming",
    "Requirements Engineering",
    "User Story Mapping & Release Planning",
    "Concept Development & Prototyping",
    "Usability Testing & Iteration"
   ],
   "metrics": [
    {
     "value": "57",
     "label": "survey respondents"
    },
    {
     "value": "6",
     "label": "contextual inquiries + follow-ups"
    },
    {
     "value": "~75%",
     "label": "say they relate more to colleagues whose personal details they know"
    },
    {
     "value": "3 → 1",
     "label": "concepts presented to deskbird; one selected by vote"
    }
   ],
   "about": "An industry UX research project with deskbird and Bauhaus-Universität Weimar on why hybrid teams lose their everyday social connection. In a team of six we ran the full user-centred design process — stakeholder interviews, a 57-person survey, and six contextual inquiries — to establish how a social feature should work before it reached the roadmap. The outcome is 'Interest-Based Communities', my concept, selected by deskbird's stakeholders and delivered as a research-backed high-fidelity prototype.",
   "challenge": "Hybrid work reduced spontaneous social interactions: employees felt less integrated and new joiners struggled to connect. deskbird — a B2B SaaS platform for desk booking and hybrid week planning — wanted evidence, not assumptions, on how a social feature should work before committing it to the product roadmap.",
   "solution": "We designed 'Interest-Based Communities': employees add interests to their profile, see colleagues' interests, and create or get invited to interest-based events. The concept connects both office-based and remote staff and was delivered as a high-fidelity prototype with development recommendations, grounded in every research finding along the way.",
   "methodology": "We followed the full UCD process in an industry setting. A state-of-the-art review of the hybrid-work tool landscape (Microsoft Viva, Workvivo, Donut for Slack, Happeo, and ~25 others) and a heuristic evaluation of the existing deskbird app — walked through as both admin and end user, with user-flow analysis — framed the scope. A literature review of social features in workplace systems, working from Lyons and Lessard's distinction between key and supportive social features, gave the concept work a vocabulary. Stakeholder interviews across marketing, product management, product design, and customer support defined brand identity, consumer aspirations, and the social-feature scope. An online survey (57 respondents, mainly aged 25–34, IT industry, hybrid workers recruited via convenience and snowball sampling) quantified work conditions, social interaction states, communication channels, and privacy preferences; its open-ended responses set the focus for what came next. Six 90-minute remote contextual inquiries — observing product managers, engineers, designers, and analysts in their real hybrid workday — were each paired with a 30-minute semi-structured follow-up interview, then worked through in team interpretation sessions.",
   "results": "Socialisation happens during breaks, and office breaks differ fundamentally from home-office breaks; the office is preferred for real interactions and faster communication while home office wins on convenience and fewer distractions; and nearly three-quarters of survey respondents agreed that knowing personal details about a colleague makes them relate more. Interaction across seniority levels and departments emerged as a persistent barrier. These findings shaped three competing concepts (Chat2Meet, Flows & Breaks, Interest-Based Communities); Interest-Based Communities was selected, refined into the final prototype, and validated in user testing sessions that returned positive feedback on usability and feature understanding.",
   "limitations": [
    "Survey respondents were recruited by convenience and snowball sampling, which biases the sample toward the team's own networks.",
    "Roughly three-quarters of respondents were aged 25–34 and about two-thirds worked in technology, so the sample under-represents deskbird's wider enterprise customer base.",
    "All six contextual inquiry participants worked in the IT industry, so the observed workday patterns are specific to that setting.",
    "Usability testing validated feature understanding and interaction, not adoption or effect on actual social connection — that would need a longitudinal study after launch."
   ],
   "outcome": {
    "body": "At the final presentation, deskbird's stakeholders said they liked the concept and intended to build it in upcoming sprints. That is a stated intention recorded at handover — not confirmed delivery. The research team had no visibility into deskbird's backlog after the project ended, and I have not since verified whether the feature shipped. It is listed here as unconfirmed rather than claimed as adoption.",
    "adoption": "unknown"
   },
   "process": [
    {
     "phase": "discover",
     "type": "Heuristic Evaluation & Competitive Review",
     "title": "Learning the Product and the Landscape",
     "annotation": "Before talking to anyone we walked the existing deskbird app end to end, once as an admin and once as an end user, mapping its user flows and its existing social surface. In parallel we reviewed the hybrid-work tool landscape — Microsoft Viva Engage, Workvivo, Happeo, Haiilo, Staffbase, Donut for Slack, Sococo, Gather Town and others — feature by feature.",
     "insight": "The competitors mostly added a social layer on top of work: a feed, a channel, a chat. deskbird's opening was different — it already knew who was in the office on which day, which is a starting point none of the others had."
    },
    {
     "phase": "discover",
     "type": "Stakeholder Interviews",
     "title": "Aligning on Scope with deskbird",
     "annotation": "Interviews across marketing, product management, product design, and customer support surfaced three insight clusters: brand identity (minimalist, usability-driven UX), consumer aspirations (fewer clicks, no extra browser tabs), and the social-feature mandate — transparent, non-intrusive, attracting people back to the office.",
     "insight": "The business goal ('attract people back to the office') and the user goal ('meaningful connection') were not the same thing — the requirements had to answer both."
    },
    {
     "phase": "discover",
     "type": "Online Survey",
     "title": "Quantifying Hybrid Social Life (N=57)",
     "annotation": "Multiple-choice, rating, and open-ended questions exploring work conditions, current state of social interactions, communication channels, and privacy preferences. Respondents were mainly juniors aged 25–34 in the IT industry, across various company sizes. Participation was screened on currently or recently working in a hybrid setting.",
     "insight": "Nearly three-quarters agreed that knowing personal details about a colleague makes them relate more — the single strongest signal pointing toward interest-based connection. Respondents were open about gender, relationship status, and birthday, but split on age, hobbies, and personal milestones, which set a boundary for what any profile could ask for."
    },
    {
     "phase": "discover",
     "type": "Remote Contextual Inquiry",
     "title": "Observing the Hybrid Workday in Context (N=6)",
     "annotation": "Six 90-minute remote observations of hybrid workers in their real workplace — product manager, software engineer, customer success manager, product designer, UX working student, business analyst — followed by 30-minute semi-structured interviews to clarify observations and capture desires for improvement. The open-ended survey answers set what we went looking for: how people decide between home and office, how they feel about office events, how they connect with colleagues.",
     "insight": "Breaks are when socialisation happens — and breaks at the office differ fundamentally from breaks at home. Participants wanted variety and meaningful social breaks — and to be left undisturbed when they needed focus."
    },
    {
     "phase": "define",
     "type": "Interpretation Sessions & Affinity Diagram",
     "title": "Six Workdays into One Picture",
     "annotation": "Each inquiry was worked through in a team interpretation session. Observations became numbered affinity notes tagged to the participant they came from, and each participant's workday was modelled from several angles — sequence, relationship, collaboration, identity, and physical setup. The wall was then built in five passes: gather every note, group by observed pattern, write blue labels, consolidate blue into pink, and read actionable ideas off the top.",
     "insight": "Six themes came out of the wall: interruption and focus, work breaks, socialising at the workplace, what drives the choice between home and office, communication habits, and bonding at work. Because every note stayed tagged to its participant, any requirement could be walked back to the observation behind it."
    },
    {
     "phase": "define",
     "type": "Requirements Synthesis",
     "title": "From Findings to Requirement Categories",
     "annotation": "Findings were synthesised into functional, environmental, user, and data requirements: foster interaction across seniority levels and around shared interests, integrate seamlessly on every platform, stay accessible to both remote and on-site staff, stay intuitive for all users, and collect data privacy-first. Each entry carried the interview or exploration it came from, and the matrix went through a second pass after critique — one round mixed ideas in with requirements, and those were pulled back out into the ideation phase where they belonged.",
     "insight": "Interaction between different seniority levels and departments was where connecting stayed hardest — any concept had to lower that threshold, not just add another chat channel. The questions the matrix could not answer became three scoped follow-up studies: social interaction at the workplace, privacy preferences around social data, and communication channels."
    },
    {
     "phase": "design",
     "type": "Concept Development",
     "title": "Three Concepts, One Winner",
     "annotation": "We developed and compared three concepts against the requirements: Chat2Meet (template-based event messaging), Flows & Breaks (focus/break status synced across tools), and Interest-Based Communities.",
     "insight": "Interest-Based Communities satisfied the requirements most completely — cross-seniority interaction, access for remote and on-site staff — and directly operationalised the survey's strongest finding on personal connection. deskbird's stakeholders selected it."
    },
    {
     "phase": "design",
     "type": "Story Mapping & User Flows",
     "title": "Slicing the Concept into Three Releases",
     "annotation": "The selected concept was mapped as a user story map across four epics — customising the profile, managing interests as admin, creating events as admin, and connecting users — sliced into three releases. User flows were drawn for the first release covering three paths: the end user selecting interests, a second user viewing someone's profile, and the admin creating a tagged event with its invitation and notification logic.",
     "insight": "Privacy was scoped into the first release rather than deferred — interest visibility could be switched off at the profile level from the start, with finer per-interest controls held back for release three. That sequencing came straight out of the survey's split reaction to sharing personal details."
    },
    {
     "phase": "deliver",
     "type": "High-Fidelity Prototype",
     "title": "Interest-Based Communities Prototype",
     "annotation": "Final prototype: add your own interests, see colleagues' interests, get invited to events, and create events for like-minded people — accessible to both remote and on-site staff, and extended into the Slack side panel so it did not become another browser tab. Validated in user testing sessions (feature understanding, usability issues), iteratively refined, and delivered to deskbird with documentation and development recommendations.",
     "insight": "Success indicators were defined up front: number of interests created, profiles with interests, interest-based events, and attendees — making the feature's impact measurable post-launch."
    }
   ],
   "cardOutcome": "Socialising happens in breaks, so the concept connects colleagues by shared interest rather than by shared calendar."
  },
  {
   "title": "Gaze-Assisted Input in Dual-Display Environments",
   "page": "/projects/gaze-assisted-input",
   "status": "published",
   "subtitle": "A Comparative Evaluation of MAGIC Pointing, Ninja Cursors, and a Mouse Baseline",
   "tagline": "Can gaze make cross-screen pointing faster — without sacrificing user trust?",
   "role": "UX Engineer (Master's Thesis)",
   "year": "2025–2026",
   "timeline": "10/2025 – 04/2026 · defence 05/2026",
   "context": "M.Sc. thesis",
   "tags": [
    "TypeScript",
    "React",
    "Python",
    "Eye-Tracking",
    "Real-Time API Integration",
    "Mixed-Methods Research",
    "Experimental Design",
    "Semi-Structured Interviews",
    "Thematic Analysis",
    "Quantitative UX Research",
    "Statistical Analysis (ANOVA)",
    "SUS Evaluation",
    "Figma"
   ],
   "techStack": [
    "TypeScript",
    "Pupil Labs Neon",
    "Real-Time API",
    "AprilTag Marker Mapping",
    "Python",
    "React"
   ],
   "methods": [
    "Custom TypeScript Architecture",
    "Within-Subjects Experiment (3×2×6)",
    "Real-Time Data Logging",
    "Repeated-Measures ANOVA",
    "SUS Evaluation",
    "Reflexive Thematic Analysis"
   ],
   "metrics": [
    {
     "value": "2",
     "label": "gaze techniques engineered from scratch in TypeScript"
    },
    {
     "value": "N=30",
     "label": "within-subjects experiment"
    },
    {
     "value": "η²ₚ=.690",
     "label": "technique × distance interaction"
    },
    {
     "value": "60%",
     "label": "preferred the gaze-hybrid (Ninja)"
    }
   ],
   "about": "A Master's thesis asking whether eye gaze can make pointing across two screens faster without costing users their trust in the cursor. I built the entire experiment software in TypeScript, connected it to a head-mounted eye tracker, and compared two gaze-assisted techniques — MAGIC Pointing and Ninja Cursors — against a plain mouse with 30 participants.",
   "challenge": "Multi-display workstations are everywhere, yet the mouse alone makes cross-display pointing costly: long pointer transits, cursor re-acquisition after bezel crossings, and attentional switches between screens. Prior work proposed gaze-assisted hybrids, but few controlled studies had compared MAGIC Pointing and Ninja Cursors against a mouse baseline in a dual-display setting — a comparison explicitly called for as future work by Räihä & Špakov (2009).",
   "solution": "I engineered the complete technical architecture and evaluation framework. This included building a dual-display eye-tracking apparatus (Pupil Labs Neon, real-time streaming API, AprilTag surface mapping) and developing performant TypeScript implementations of MAGIC Pointing (gaze-triggered cursor warp with manual fine-tuning) and a gaze-augmented Ninja Cursors variant (one persistent cursor per screen, activated by gaze). Both were then evaluated against a standard mouse baseline in reciprocal pointing tasks.",
   "methodology": "A two-phase mixed-methods design. Phase I: a formative pre-study (n=20) using semi-structured interviews and a Figma-based workspace visualisation task, analysed with reflexive thematic analysis, which grounded the lab configuration in real dual-display practice. Phase II: a controlled within-subjects experiment (N=30) with a 3×2×6 factorial design — input method × target size × distance (875–3226 px) — measuring movement time, repeat rate, and SUS, analysed with repeated-measures ANOVA (Greenhouse–Geisser corrected, Tukey post-hoc).",
   "results": "A significant technique × distance interaction (η²ₚ = .690) revealed a crossover: the mouse was fastest for short distances, but Ninja Cursors significantly outperformed it at the two intermediate cross-screen distances (1684 and 2243 px) and converged at the longest (3226 px). MAGIC was consistently slowest — its warp coupled gaze noise directly to landing accuracy, producing the highest repeat rate on small targets (4.69%), while Ninja's small-target repeat rate matched the mouse baseline (3.30%). SUS ranked Mouse (85.2) > Ninja (72.6) > MAGIC (55.9), with MAGIC alone falling below the 68-point acceptability threshold — yet 60% of participants named Ninja their most preferred method, and 63% named MAGIC their least preferred.",
   "limitations": [
    "Short-term exposure. The study captured first impressions, not long-term adaptation — and the mouse's familiarity is a confound the design could not remove. Whether the coordination overhead 18 of 30 participants described falls away as the gaze techniques are internalised needs a longitudinal design.",
    "Hardware-related discomfort. Fourteen of thirty participants reported frame pressure, eye fatigue, or degraded tracking as prescription-glasses wearers — all of which likely reflect the apparatus rather than gaze-based interaction as a paradigm.",
    "Laboratory task versus real work. Reciprocal pointing isolates target acquisition; it does not carry window management, context switching, variable target densities, or the periods of cursor disengagement in which the re-acquisition benefit of gaze would show most clearly.",
    "Missing endpoint data. Miss/timeout outcomes and trial-level endpoint coordinates were not retained in the cleaned export, so ISO-style effective measures and throughput could not be computed — and repeat rate could not be decomposed into its breakdown types.",
    "Sample characteristics. Participants were largely researchers and professionals in technology-related roles, which limits how far the results generalise to other populations.",
    "Distance and screen transition are confounded. The six distance levels do not pair within-screen and cross-screen movements at matched amplitudes, so the effect of crossing the bezel cannot be separated from the effect of distance — no claim about the boundary's own contribution is made from these data. The asymmetry was deliberate: the geometry copies a real dual-display workstation rather than an artificially symmetric one. A matched-pairs design would settle it."
   ],
   "implications": "Gaze assistance should be a context-aware accelerator, not an always-on replacement. Three design directions follow from the data: adaptive activation using the screen boundary itself as the trigger, semantic snapping toward UI elements to fix MAGIC's landing penalty, and stronger visual differentiation of the active cursor in multi-cursor designs. For UI engineers, predictability and system trust — not raw speed alone — determine whether users adopt a novel interaction pattern.",
   "outcome": {
    "body": "This is a Master's thesis, not a commercially deployed system — adoption in the product sense doesn't apply the way it would for a shipped feature. The three design directions named in the Implications section are the concrete output the completed work delivered.",
    "adoption": "academic"
   },
   "process": [
    {
     "phase": "discover",
     "type": "Semi-structured Interviews",
     "title": "Characterising Real Multi-Display Work",
     "annotation": "20 participants (researchers and tech/design professionals) recreated their workstation on a shared Figma canvas, then discussed screen roles, input preferences, and cross-display pain points in ~30-minute sessions. Analysed with reflexive thematic analysis.",
     "insight": "Cursor loss was a real, named pain point: participants described 'shaking' the mouse to find the pointer, and 14 of 20 reported neck strain or eye fatigue. This directly motivated the focus on cross-display target acquisition."
    },
    {
     "phase": "discover",
     "type": "Workspace Visualisation",
     "title": "Grounding the Lab Setup in Reality",
     "annotation": "Participants' recreated configurations revealed dominant patterns: side-by-side dual displays, laptop + external monitor (12/20), and near-universal mouse use (17/20) even on laptops.",
     "insight": "The lab apparatus copied what people actually use — side-by-side dual displays, mouse as the manual device, and a height-adjustable desk to address the ergonomic strain participants reported."
    },
    {
     "phase": "define",
     "type": "Experimental Design",
     "title": "A 3×2×6 Within-Subjects Protocol",
     "annotation": "Three input methods (Mouse, MAGIC Pointing, gaze-augmented Ninja Cursors) × two target sizes × six distances (875–3226 px); input-method and target-size order counterbalanced with a balanced Latin square. Measures: movement time, repeat rate, and SUS per method block.",
     "insight": "Treating distance as a categorical factor was deliberate — the six levels mix within-screen and cross-screen movements, which is exactly where the techniques were expected to diverge."
    },
    {
     "phase": "design",
     "type": "Frontend Engineering",
     "title": "TypeScript Architecture & Real-Time Gaze Pipeline",
     "annotation": "Engineered the complete experiment software from scratch in TypeScript. Interfaced with the Pupil Labs Neon head-mounted tracker via its real-time streaming API — a Python backend service relays the tracker's stream to the browser frontend — using AprilTag-based surface mapping to translate gaze onto each display. Implemented MAGIC (gaze-triggered warp, 20 px landing offset) and a gaze-augmented Ninja variant (one cursor per screen, gaze-based switching, 150 ms guard).",
     "insight": "The two techniques distribute risk differently on a system level: MAGIC couples gaze precision to every landing, while Ninja uses gaze only for the coarse display switch — an architectural difference that later explained the entire results pattern."
    },
    {
     "phase": "deliver",
     "type": "Quantitative Analysis",
     "title": "RM-ANOVA: A Distance-Dependent Crossover",
     "annotation": "Repeated-measures ANOVA on log-transformed movement time (n=24 after data-quality exclusions), Greenhouse–Geisser corrected, Tukey post-hoc, run in R. Significant technique × distance interaction (η²ₚ = .690, p < .001).",
     "insight": "Mouse won at short distances — but Ninja significantly beat it at the two intermediate cross-screen distances (1684 and 2243 px) and converged at the longest. Gaze assistance pays off precisely where the bezel crossing is the dominant cost."
    },
    {
     "phase": "deliver",
     "type": "SUS + Thematic Analysis",
     "title": "Trust Beats Speed",
     "annotation": "SUS after each block (N=30): Mouse 85.2, Ninja 72.6, MAGIC 55.9 (Friedman p < .001) — MAGIC the only technique below the 68-point acceptability threshold. Reflexive thematic analysis of open feedback surfaced seven primary themes, from the 'transport advantage' (23/30) to the 'landing penalty' (22/30).",
     "insight": "60% preferred Ninja despite the mouse's higher SUS — participants framed it as 'best of both worlds.' Predictability and trust, not raw speed, determined acceptance."
    }
   ],
   "verbatims": [
    {
     "quote": "Sometimes when I'm very much focused on the task, I just don't get [where the cursor] is, and then I have to shake it.",
     "attribution": "P03 (engineer), Phase I pre-study (n=20) — on losing the cursor in everyday multi-display work"
    },
    {
     "quote": "It's a mix of Mouse and MAGIC — you get the best out of both. It makes switching monitors faster while putting less strain on the eyes.",
     "attribution": "P21 on Ninja Cursors, Phase II study (N=30) — 60% preferred it despite the mouse scoring higher on SUS"
    }
   ],
   "cardOutcome": "Gaze wins over long cross-screen distances and loses over short ones; trust in the cursor decided preference."
  },
  {
   "title": "EmbraceMe – An Inflatable Soft Robot for Emotional Care",
   "page": "/projects/embraceme-soft-robotics",
   "status": "published",
   "subtitle": "A Pneumatic Soft-Robotic Hugging Interface, Exhibited & Evaluated in Public",
   "tagline": "Engineering a soft-robotic hug — and reporting where it fell short.",
   "role": "HCI Researcher & Prototyping Engineer (team of 3)",
   "year": "2023",
   "timeline": "Summer semester 2023",
   "context": "University research project",
   "tags": [
    "Soft Robotics",
    "Human-Robot Interaction",
    "Shape-Changing Interfaces",
    "Literature Review",
    "Competitive Analysis",
    "Physical Prototyping",
    "Material Testing",
    "Arduino",
    "Sensor Integration",
    "Interaction Design",
    "Data Physicalization",
    "Exhibition Research"
   ],
   "techStack": [
    "Arduino",
    "Festo 5/3 Solenoid Valve",
    "5-Pad Capacitive Touch Sensor",
    "TPU (heat-sealed)",
    "Foam Fabrication",
    "LED Feedback"
   ],
   "methods": [
    "Literature Review",
    "Comparative Analysis of Prior Systems",
    "Iterative Physical Prototyping",
    "Material Testing",
    "Public Exhibition & Observation",
    "Critical Reflection (Data Physicalization Framework)"
   ],
   "metrics": [
    {
     "value": "Public",
     "label": "exhibition with live user observation"
    },
    {
     "value": "3",
     "label": "prototype iterations to a working hug"
    },
    {
     "value": "3s / 9s",
     "label": "inflate–deflate cycle timing"
    },
    {
     "value": "80×16",
     "label": "cm PneuNet foam arms"
    }
   ],
   "about": "A soft-robotics project exploring whether a machine can deliver the calming effect of a hug. In a team of three I designed and built EmbraceMe, a standalone hugging robot with inflatable PneuNet foam arms driven by an Arduino and a capacitive touch sensor. We exhibited it publicly and observed real visitors using it — documenting both what delighted them and where the design fell short.",
   "challenge": "Physical touch like hugging releases oxytocin and measurably reduces stress — but not everyone has access to it: loved ones may be distant, or contact may be unsafe. We set out to build an inflatable soft-robotic interface delivering Deep Pressure Stimulation through a standalone hugging experience, gentle enough for direct human contact.",
   "solution": "A standalone hugging bot built on a mannequin frame with PneuNet bending-actuator arms: foam limbs (80×16 cm) with 45° triangular cuts housing heat-sealed TPU air chambers. A 5-pad capacitive touch sensor on the chest triggers inflation when a user leans in for a hug; a Festo 5/3 solenoid valve and timed Arduino logic (3s inflate, 9s deflate) regulate pressure, with an LED feedback cycle (green: ready, white: hugging, blinking red: resetting) communicating system state.",
   "methodology": "We grounded the design in a literature review of interpersonal touch, Deep Pressure Stimulation, and soft robotics, and a comparative analysis of prior hugging systems (Hug Over a Distance, Huggy Pajama, HugShirt, HuggieBot 3.0, MIT's Huggable, and Bauhaus's own Hugging Suit) to identify their gaps — partial body coverage, static holds, and no emotional context. Two actuation techniques were evaluated (soft-growing vs. PneuNet bending); the standalone form factor decided for inclusivity determined the PneuNet approach. The prototype then went through iterative material testing before public exhibition with observation and user feedback.",
   "results": "At a public university exhibition, visitors described the interaction as fun and surprising — the bot 'waking up' to hug back was the standout moment. The evaluation also surfaced honest design failures: some users read the pink, muscular arms as uncanny and avoided full contact, and without clear signifiers, nobody could guess how to initiate a hug unprompted. My individual follow-up applied Offenhuber's data physicalization framework to propose the next iteration: emotion-recognition data (wearables, mood tracking) mapped to arm extension and hug intensity, turning a binary-triggered mechanism into an emotionally adaptive interface.",
   "limitations": [
    "The exhibition evaluation was open observation and informal feedback, not a protocol: no task set, no structured interview, and no session notes were retained that would let a finding be recounted or a frequency stated.",
    "Nothing about the calming effect was measured. Deep Pressure Stimulation carries that claim in the literature; this prototype produced no physiological data and no self-reports of its own.",
    "Exhibition visitors are self-selecting and were watched in a social, playful setting — close to the opposite of the private moment of distress the concept was written for.",
    "There was one build and no comparison condition — no human hug, no static weighted alternative — so the observed reactions cannot be attributed to the soft-robotic actuation rather than to the novelty of the object.",
    "Arm length, cut geometry and the 3s/9s inflation timing were fixed for one body size. Fit, pressure and comfort across different bodies — and for the impaired users the concept names — were never tested.",
    "The redesign proposed in the individual reflection report — emotion-recognition data driving arm extension and hug intensity — was never built or evaluated; it remains an argument, not a result."
   ],
   "outcome": {
    "body": "EmbraceMe was not iterated into a second physical prototype after the exhibition — the group deliverable ended at the evaluated build. The follow-on work is a documented redesign proposal (individual report), not a shipped or roadmapped system, and no organisation has committed to building it.",
    "decisions": [
     "The visible design failures (uncanny arm aesthetics, no signifiers for initiating a hug) were not patched within the group project — they were carried into an individual critical-reflection report instead.",
     "The redesign proposal rejected the binary-trigger mechanism outright, replacing it with emotion-recognition data driving arm extension and hug intensity, with user autonomy, explicit consent, and privacy-first handling defined as guardrails before any such system would be built."
    ],
    "adoption": "academic"
   },
   "process": [
    {
     "phase": "discover",
     "type": "Literature Review",
     "title": "Deep Pressure Stimulation & Interpersonal Touch",
     "annotation": "Reviewed research on interpersonal touch, oxytocin response, and DPS therapy (weighted blankets as the canonical example), alongside soft robotics and shape-changing interface literature.",
     "insight": "Hugging is one of the most desired affectionate touches, with measurable stress-reduction effects — but replicating human hugging exactly was out of scope. The goal became a soft, warm embrace, not a simulation of a person."
    },
    {
     "phase": "discover",
     "type": "Comparative Analysis",
     "title": "Mapping the Gaps in Prior Hugging Systems",
     "annotation": "Analysed Hug Over a Distance, Huggy Pajama, HugShirt, HuggieBot 3.0, MIT's Huggable, and the Bauhaus Hugging Suit — comparing wearable vs. standalone forms, actuation, and sensing.",
     "insight": "Every prior system shared two gaps: partial-body sensory coverage and zero emotional context. Devices sense touch, not feelings — this framed both our prototype and my later data physicalization critique."
    },
    {
     "phase": "define",
     "type": "Form & Technique Decision",
     "title": "Backpack vs. Standalone",
     "annotation": "Two concepts sketched: a portable backpack using soft-growing (vine robot) arms, and a standalone figure using PneuNet bending actuators. Chose standalone after consultation, for inclusivity across body sizes and open access at the exhibition.",
     "insight": "The form-factor decision cascaded into the actuation technique: standalone required PneuNet bending arms that hold their position in space without a skeleton — the project's hardest engineering constraint."
    },
    {
     "phase": "design",
     "type": "Iterative Material Testing",
     "title": "Balloons → Transparent TPU → Yellow TPU",
     "annotation": "Proof-of-concept with balloons in slotted foam validated the bending mechanism. Transparent TPU replaced them for durability — but deformed irregularly after repeated inflation, breaking the curvature. Final iteration: stiffer yellow TPU chambers with regulated airflow to prevent bursting.",
     "insight": "Material properties drove interaction quality: consistent chamber volume was the difference between a controlled embrace and an erratic one. Slot spacing (10 cm) and chamber size (8×6 cm) were tuned empirically across numerous arm samples."
    },
    {
     "phase": "design",
     "type": "Sensing & Feedback System",
     "title": "Touch-Triggered Hugging with an LED Feedback Cycle",
     "annotation": "A 5-pad capacitive touch sensor on the bot's chest detects a user leaning in; Arduino opens the Festo 5/3 valve for 3 seconds to inflate, holds pressure during the hug, then vents for 9 seconds on release. LED states (green/white/blinking red) communicate readiness, hugging, and reset.",
     "insight": "Timings were derived through trial-and-error experimentation — long enough to hold a firm hug, short enough to protect the chambers from over-inflation."
    },
    {
     "phase": "deliver",
     "type": "Public Exhibition & Observation",
     "title": "What Visitors Actually Did",
     "annotation": "Exhibited at a university event open to academic and non-academic visitors. Observed interactions and collected impressions: delight at the bot 'waking up,' but also uncanny-valley reactions to its form and confusion about how to initiate contact without our explanation.",
     "insight": "Two design failures: aesthetic choices triggered avoidance in some users, and the interface lacked signifiers — curiosity did not translate into interaction without designer intervention."
    },
    {
     "phase": "deliver",
     "type": "Critical Reflection & Redesign Proposal",
     "title": "From Binary Trigger to Emotional Data (Individual Report)",
     "annotation": "Applied Offenhuber's data physicalization framework to critique the prototype: it followed a physical process triggered by binary signals and conveyed no emotional message. Proposed a redesign where emotion-recognition data (wearables, mood tracking) drives soft-growing arms — extension length and warmth mapped to the user's distress level, hug rhythm synced to heartbeat.",
     "insight": "The reflection reframed the project's failure as a data problem, not a hardware problem — and defined ethical guardrails: user autonomy over hug intensity, explicit consent, and privacy-first handling of emotional data."
    }
   ],
   "cardOutcome": "The hug delighted visitors — but without signifiers nobody could start one unprompted; the interaction, not the hardware, fell short."
  },
  {
   "title": "Smart Home Control for Shared Households",
   "page": "/projects/smart-home-control",
   "status": "published",
   "subtitle": "A Paper-Prototype Study of the Social Layer: Who May Add, Share, and Govern Devices",
   "tagline": "Who may add a device, remove a housemate, or override someone mid-use? The questions existing smart-home apps don't answer.",
   "role": "UX Researcher (team of 4)",
   "year": "2023",
   "timeline": "SoSe 2023",
   "context": "University course project",
   "tags": [
    "Questionnaire Study",
    "Think-Aloud Testing",
    "Paper Prototyping",
    "Qualitative Coding",
    "Thematic Analysis",
    "Information Architecture",
    "User Flow Mapping",
    "Iterative Design",
    "Accessibility",
    "Smart Home",
    "Google Forms"
   ],
   "techStack": [
    "Google Forms"
   ],
   "methods": [
    "Questionnaire study (N=24)",
    "Think-aloud usability testing (N=2)",
    "Low-fidelity paper prototyping",
    "Qualitative coding & thematic analysis",
    "Information architecture & flow mapping",
    "Iterative design revision"
   ],
   "metrics": [
    {
     "value": "24",
     "label": "questionnaire responses (of 30 people approached)"
    },
    {
     "value": "2",
     "label": "think-aloud usability test participants"
    },
    {
     "value": "12",
     "label": "screens across 4 documented task flows"
    },
    {
     "value": "4",
     "label": "design changes made from test findings"
    }
   ],
   "about": "A four-person course project at Bauhaus-Universität Weimar (summer semester 2023) about what smart-home apps get wrong about shared living. The design problem was never device control — existing apps solve that. It was the social layer of a shared household: who may add a device, who may remove a housemate, who may override someone else mid-use. A questionnaire study (24 responses) framed the territory, a 12-screen paper prototype made a governance model tangible, two think-aloud sessions tested it, and four design changes — each documented as a verbatim participant quote, the change it prompted, and a before/after photograph pair — closed the loop.",
   "challenge": "Smart-home apps model a home as one owner and a set of devices. A shared flat fits neither assumption: residents come and go, devices belong to some people and are used by everyone, and the moment two people want the same lamp at once is a social negotiation, not a technical conflict. The project framed exactly that gap — membership, permissions, and simultaneous use — as the design problem.",
   "solution": "A 12-screen paper prototype covering four documented task flows, all anchored on one home screen. Onboarding runs scanning → naming → access → confirmation, with a three-step progress indicator that deliberately stops at the confirmation screen. Governance is built into the everyday paths rather than an admin area: who may use a device is chosen at setup, residents are invited by link, and a device in use can be locked while in use — resolving simultaneous access without a queue. The galleries below show the tested v1 version, grouped by flow.",
   "design": "The revision is the most documented part of the project. Both test transcripts were coded into four categories — positive feedback, negative feedback, questions, ideas and suggestions — and four changes were made, each traceable to a verbatim quote from the sessions. They are shown below exactly as they happened: the quote, the change it prompted, and both photographs — the tested v1 screen on the left, the revised v2 screen on the right. The revision also fixed a defect the test itself exposed only indirectly: the resident roster differed across three v1 screens — two residents on one, three on another, five on a third, with the same person written “Drake” on one card and “Jake” on another. The v2 screens normalise the roster everywhere.",
   "methodology": "Phase 1 — Discovery. A questionnaire (Google Forms) was chosen over interviews, focus groups, and shadowing: it fit the timeline, and it let respondents answer at their own pace, which supported confidentiality and autonomy. It was piloted with a small group before distribution to check for ambiguity and leading questions; consent was obtained and responses were anonymous. Questions were sequenced deliberately — demographics, then habits, then needs — so respondents were not steered toward an attitude about smart homes early. Of 30 people approached, 24 responded. Roughly a third reported difficulty syncing devices; a quarter named remote adjustment of settings as a persistent pain point. Segmentation produced two named groups — students and part-time employees, and full-time employees — plus an “others” bucket, each with a documented attitude toward smart-home apps and a separate attitude toward mobile services generally. The user profile explicitly included cognitive, visual, and mobility impairment: accessibility was scoped at discovery, not bolted on later. Phase 2 — Evaluation. Two think-aloud sessions in a controlled setting, each participant seated individually with a facilitator. Audio was recorded and photographs taken; participants were briefed on recording and anonymity. The facilitator used probing questions when participants went quiet and observed facial expressions; each session ended with a retrospective debrief. Participant A — 31, a junior software developer. Participant B — 43, with a degree in an unrelated field. Both are iOS users; neither had used a smart-home app before. Transcripts were coded into four categories: positive feedback, negative feedback, questions, and ideas/suggestions.",
   "results": "The findings worth keeping are the ones that did not become quick fixes. A dead end surfaced in a flow we thought was finished: Participant A selected both devices at the scanning step, but only one carried into setup, and the confirmation screen had no way back — she noticed immediately and asked what had happened to the second device. Frames were read as the only tappable things: Participant B tapped only elements with a visible button border, engaging the boxed room selector on the device settings screen and treating the unframed rows beside it as labels. Destructive actions produced anxiety before they produced errors: encountering “delete this room”, Participant A worried aloud about triggering it accidentally and proposed moving room management to a dedicated screen — a structural objection, not a cosmetic one. The method itself was a finding: both participants needed to backtrack, neither could do it while holding the cards, and both ended up laying the prototype out on the floor — A sorting it into order first, B improvising late. And both participants opened every screen by reading its title aloud, which is why the “which home am I in?” gap surfaced on four separate screens. Two participants is a thin sample, and the original report says so. Revisiting the artifacts, the resident roster inconsistency across three tested screens is a defect a heuristic review would have caught before it reached a participant. The same revisiting surfaced a documentation lesson: most of the report's session photographs turn out to show the revised cards rather than the ones tested — the set was re-photographed after the changes were made. The sessions themselves are evidenced by the transcript and by the four changes that came out of them, but I'd now photograph artifacts at the moment of testing rather than afterwards.",
   "limitations": [
    "Two think-aloud participants is enough to expose a dead end and a misread affordance, not to establish how often either occurs or how severe it is. The original report says so, and no wider round followed.",
    "Both testers were iOS users who had never used a smart-home app, and neither was tested inside an actual shared household — the social situation the design is about was described to them, not lived during the session.",
    "The questionnaire (24 of 30 people approached) was distributed through the team's own reach, so it framed the territory and named pain points; it was never a representative sample of shared-flat residents.",
    "A paper prototype cannot produce the conflict the project is about: no device latency, no second resident acting at the same moment. Simultaneous use could only be walked through, never experienced.",
    "The v2 revision was never put in front of a participant, so the four changes are reasoned responses to observed problems — not changes shown to have fixed them.",
    "The photographic record is weaker than the sessions were: most session photographs in the report show the revised cards, because the set was re-photographed after the changes. What was tested is evidenced by the transcript, not by the photos."
   ],
   "outcome": {
    "body": "A university course project — adoption in the product sense doesn't apply. What the course closed on is the revised v2 prototype: four changes, each documented as a participant quote, the change it prompted, and a before/after photograph pair. The revision itself was never put in front of another participant — re-testing it is where a next session would have to start.",
    "adoption": "academic"
   },
   "verbatims": [
    {
     "quote": "Now I can go to the device… but what happened to the other device that I selected two steps ago? … there is not even any back button here…",
     "attribution": "Participant A, screen E — discovering the onboarding dead end"
    },
    {
     "quote": "I'm worried about this option... What if I delete it accidentally?",
     "attribution": "Participant A, screen F (room view) — on “delete this room”, before proposing a dedicated room-management screen"
    },
    {
     "quote": "what can I do with this radar? Is it clickable?",
     "attribution": "Participant B, screen B — the frames-are-tappable pattern, in his own words"
    }
   ],
   "cardOutcome": "Two think-aloud sessions turned verbatim quotes into four documented design changes, each shown as a before-and-after pair."
  },
  {
   "title": "Designing This Portfolio",
   "page": "/projects/designing-this-site",
   "status": "published",
   "subtitle": "A Case Study in Designing Under Constraint — One Person as Researcher, Designer, Engineer, and QA",
   "tagline": "The site itself, documented as a case study: one codebase for screen, print, and two languages — every claim measured or marked pending.",
   "role": "Researcher, Designer, Frontend Engineer & QA (solo)",
   "timeline": "Ongoing · continuously iterated",
   "tags": [
    "React",
    "Vite",
    "Tailwind CSS",
    "Framer Motion",
    "React Router",
    "OpenAI API",
    "Prompt Engineering",
    "Design Systems",
    "Component Architecture",
    "Information Architecture",
    "Responsive Design",
    "Accessibility",
    "Performance Optimization",
    "SEO",
    "Internationalization (i18n)",
    "Print CSS",
    "Automated Testing (Vitest)"
   ],
   "techStack": [
    "React",
    "Vite",
    "Tailwind CSS",
    "Framer Motion",
    "React Router",
    "Vitest",
    "Testing Library",
    "ESLint"
   ],
   "methods": [
    "Component Architecture & Design Systems Engineering",
    "Bilingual Content Architecture (EN/DE)",
    "Print-CSS Engineering (screen-to-A4)",
    "Invariant / Contract Testing (Vitest)"
   ],
   "metrics": [
    {
     "value": "99",
     "label": "Lighthouse — Performance"
    },
    {
     "value": "100",
     "label": "Lighthouse — Accessibility"
    },
    {
     "value": "100",
     "label": "Lighthouse — Best Practices"
    },
    {
     "value": "100",
     "label": "Lighthouse — SEO"
    },
    {
     "pending": true,
     "label": "WCAG 2.1 AA contrast, all token pairs"
    },
    {
     "pending": true,
     "label": "Keyboard-only + first-click task success"
    },
    {
     "pending": true,
     "label": "CV print length (target: 1 A4 page)"
    },
    {
     "pending": true,
     "label": "5-second test — time to answer ‘what does she do?’"
    }
   ],
   "about": "A case study on the site you are reading. I built it alone: research, design, frontend, QA. It is React and Tailwind, and it has to work for three readers at once — a recruiter with thirty seconds, an engineer who opens the source, and a hiring manager holding the printed A4 CV. What follows are the trade-offs that came out of that.",
   "wireframe": "Every case study here uses one layout. Above the xl breakpoint it runs in three tracks: a sticky numbered section rail on the left that collapses to a 56-pixel number strip, the prose column in the middle at a 68ch measure (88ch once the rail is collapsed), and a pull-quote rail on the right. Below md the rail becomes a horizontal pill bar under the header. Below xl the pull-quote is dropped: it only repeats a sentence from the paragraph next to it. The order is not just convention. Every case study renders through the same ProjectTemplate({ meta, children }), and a fixed SECTIONS array decides what can appear and when — a data key that is not in it cannot render. One caveat on the figures below: I wireframed this site in the browser, so they are drawn from the shipped layout code, not from sketches that came first.",
   "designSystem": "Ink & Bloom, in short: a warm paper-and-ink palette, one loud coral accent, and a gold highlighter used at most once per page. Bricolage Grotesque for display type, DM Sans for body, Caveat for handwritten notes, and Framer Motion draw-ins that all share one easing curve. The table below reads its values from theme.css at render time instead of copying them, so it updates with the site rather than drifting from it. Two rules the numbers don't state on their own: each accent has a -500 step for large text and shapes and a -600 step for anything small enough that WCAG AA bites, and the gold sits outside that split — it is a background wash, never a text colour. Every icon in the interface, from arrows and chevrons to the ? and ! marks, is drawn with the same ~1.6–1.8px nib in one component file, so no icon font or library ships in the bundle. The full specimen sheet is the living style guide linked under Prototype. The same system is also published as a Figma Make kit — tokens, styles, components and the drawn-line rules, linked below.",
   "results": "Lighthouse 13.4.0 against production (emulated desktop, 24 August 2026): Performance 99, Accessibility 100, Best Practices 100, SEO 100. Mobile emulation the same day: 77, held down by a 4.4-second Largest Contentful Paint. Ten days earlier performance was 66, with a 0.261 layout shift, 340 ms blocking time and roughly 733 KiB of unused JavaScript. What closed the gap: a route-skeleton fix for the layout shift, lazy loading on every case-study figure, dead chunks removed, and a card/data split that took all five case studies' prose off the shared path (aggregator chunk 57 KB → 3.9 KB gzipped). Two optimisations I looked at and dropped: LazyMotion would save an estimated 20–25 KB gzipped but touch 35 files in the hand-drawn animation system, and splitting the profile data would break the local editor that writes it. Neither is worth it at these scores. The honest gap left is mobile LCP — a client-rendered hero can't paint before the JavaScript lands. Still open: the manual WCAG 2.1 AA contrast pass across every token pair (the automated audit found no failing pair, which is not the same thing), the keyboard-only run through the primary path, confirmation the CV prints to exactly one A4 page, and the two planned tests — time to answer 'what does she do?' and first-click success on the navigation.",
   "limitations": [
    "Sole author and sole evaluator. Every judgement here — structure, wording, visual system — is mine and unreviewed; there is no second designer on record who disagreed with any of it.",
    "No user research has run on the site itself. The 5-second test and the first-click test are defined and pending, so every usability claim here describes a mechanism in the source, not an observed effect on a reader.",
    "The Lighthouse numbers are single lab runs under emulation, from one machine and one network. There is no field data from real visitors, and mobile LCP in particular is the metric emulation flatters least.",
    "An automated accessibility score of 100 is not conformance. The manual contrast pass across every token pair and the keyboard-only walkthrough are still open, and nobody has run the site with a screen reader or with assistive technology in an actual user's hands."
   ],
   "outcome": {
    "body": "No outcome yet. Once the sessions run, whatever actually changed goes here: a shipped fix, a reprioritised backlog item, or a finding that changed nothing.",
    "adoption": "deferred"
   }
  }
 ],
 "voluntary": [
  {
   "title": "Awareness Member",
   "year": "2024 – Present",
   "org": "Bauhaus-Universität Weimar",
   "desc": "Awareness team member supporting university-wide student initiatives — helping keep them safe, inclusive, and accessible."
  },
  {
   "title": "Welcome Tutor",
   "year": "2022 – 2024",
   "org": "BUW International Office",
   "desc": "Guided incoming international students through arrival, cultural adjustment, and the administrative processes of their first semesters."
  },
  {
   "title": "Student Volunteer",
   "year": "2024",
   "org": "Digital Leute"
  },
  {
   "title": "Student Volunteer",
   "year": "2022",
   "org": "JCSG & Mensch und Computer",
   "desc": "Session and workshop support at Mensch und Computer (TU Darmstadt) and conference operations at JCSG in Weimar."
  }
 ],
 "pages": {
  "home": "/",
  "projects": "/projects",
  "about": "/about",
  "cv": "/cv",
  "contact": "/contact",
  "credentials": "/credentials",
  "voluntary": "/voluntary"
 }
};
